- examples/form/index.html
- packages/core/dist/components/Spinner/Spinner.js
- packages/core/src/components/Spinner/Spinner.example.jsx
- packages/core/src/components/Spinner/Spinner.jsx
- packages/core/src/components/Spinner/Spinner.scss
- packages/core/src/components/_index.scss
- packages/core/src/components/index.js
- packages/support/src/settings/_variables.animation.scss
The documentation text is unfinished, and I'd like feedback on that. I'd like design and accessibility feedback as well.
- Spinner component and classes
- Changed the form example to show a spinner button in action
> [HDSG-72] Spinner component

- examples/form/index.html
- packages/core/dist/components/Spinner/Spinner.js
- packages/core/src/components/Spinner/Spinner.example.jsx
- packages/core/src/components/Spinner/Spinner.jsx
- packages/core/src/components/Spinner/Spinner.scss
- packages/core/src/components/_index.scss
- packages/core/src/components/index.js
- packages/support/src/settings/_variables.animation.scss
Relevant discussion for this feature is available in #126.
This PR is specifically for reverting the merge commit from that PR, so we can do a squash merge instead.
> Squash merge: [HDSG-72] Spinner component #126

- packages/core/src/components/ChoiceList/Choice.jsx
- packages/core/src/components/ChoiceList/Choice.scss
- packages/core/src/components/ChoiceList/Choice.test.jsx
- packages/support/src/settings/_variables.forms.scss
- `ds-c-choice--small` class and prop and tests
> Added a "small" size variant to the Choice component

- tools/gulp/docs/index.js
- tools/gulp/watch.js
- KSS now parses JSX files as well when looking for documentation comments
> KSS looks in JavaScript files for documentation comments

- packages/docs/src/styles/components/_preview.scss
- packages/layout/src/_col.scss
- packages/layout/src/_row.scss
- packages/layout/src/index.scss
- packages/support/src/settings/_variables.layout.scss
- packages/support/src/tools/_mixins.layout.scss
- New grid features: 
- Added `ds-l-form-row` to provide tighter spacing on form fields layed out using grid classes:
- Added `ds-l-col--auto` to allow grid columns to span their content's natural width (useful for form fields)
> Add "ds-l-form-row" and "ds-l-col--auto"

- packages/core/src/components/Spinner/Spinner.test.jsx
* Confirm basic shallow component mount
* Confirm default props
* Confirm default classes
* Confirm added classes
* Confirm wrong size class not added
> [HDSG-118] Unit tests for Spinner.jsx

- packages/core/src/components/Alert/Alert.test.jsx
Breaking this out into its own branch to make #187 easier to review.
> Refactor Alert tests

- package.json
- packages/docs/package.json
- packages/docs/yarn.lock
- yarn.lock
Tested by successfully building assets and smoke testing the docs site.
> Minor update to dependencies

- .prettierignore
- packages/generator-cmsgov/generators/app/templates/index.scss
- packages/generator-cmsgov/package.json
- yarn.lock
> Internal: Fix Yeoman generator issue caused by Prettier

- packages/core/src/components/DateField/DateField.test.jsx
- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/FormLabel/FormLabel.example.jsx
- packages/core/src/components/FormLabel/FormLabel.jsx
- packages/core/src/components/FormLabel/FormLabel.scss
- packages/core/src/components/FormLabel/FormLabel.test.jsx
- Changed weight of `requirementLabel` in `FormLabel` from bold to normal, based on a design chat with @cindyphan
> Change style of requirementLabel in Form labels

- packages/core/src/components/DateField/DateField.example.jsx
- packages/core/src/components/DateField/DateField.jsx
- packages/core/src/components/DateField/DateField.test.jsx
- `onComponentBlur` hook for `<DateField>` component
> DateField adding onComponentBlur

- package.json
- packages/core/src/components/Autocomplete/Autocomplete.jsx
- yarn.lock
* Array.find polyfill for full IE11 support in cases where the method hadn't been polyfilled previously
> Adding Array.find polyfill to support IE11 fully.

- packages/core/src/components/Dialog/Dialog.jsx
- packages/core/src/components/Dialog/Dialog.test.jsx
- packages/core/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
- `size` prop to `<Dialog>` component
- `className`, `actionsClassName`, and `headerClassName` props to `<Dialog>` component
- Snapshot unit test
> Adds size and additional className props to Dialog component

- packages/core/dist/components/DateField/DateField.js
- packages/core/dist/components/FormLabel/FormLabel.js
- packages/core/src/components/DateField/DateField.jsx
- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/FormLabel/FormLabel.jsx
- packages/core/src/components/FormLabel/FormLabel.scss
- packages/core/src/components/FormLabel/FormLabel.test.jsx
- packages/core/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
- packages/core/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
Made form labels bold.
Before:
After:
> [HDSG-196] Bold form labels

- packages/core/src/components/ChoiceList/ChoiceList.example.jsx
Removed console.log left in from https://github.com/CMSgov/design-system/pull/250
> Remove console.log

- packages/core/src/components/TextField/Mask.jsx
- packages/core/src/components/TextField/Mask.test.jsx
- Accept a negative number in a masked currency text field
> Accept negative currency masked values

- packages/core/src/components/TextField/CurrencyField.example.jsx
- packages/core/src/components/TextField/CurrencyField.scss
- packages/core/src/components/TextField/Mask.jsx
- packages/core/src/components/TextField/Mask.test.jsx
- packages/core/src/components/TextField/TextField.jsx
- packages/core/src/components/TextField/TextField.test.jsx
- packages/core/src/components/TextField/__snapshots__/TextField.test.jsx.snap
- packages/core/yarn.lock
- tools/gulp/docs/parseReactFile.js
- Export an `unmaskValue` method which can be called to remove any masking characters from a text field's `value`
> Export unmaskValue method

- .github/PULL_REQUEST_TEMPLATE.md
note about updating snapshots to PR template
> Add note about updating snapshots to PR template

- packages/core/src/components/Badge/Badge.scss
- packages/core/src/components/Dialog/Dialog.scss
- packages/core/src/components/Spinner/Spinner.scss
- packages/core/src/components/StepList/StepList.scss
- packages/core/src/components/Tabs/Tabs.scss
Remove maturity badges from a few components
> Remove maturity badges until we have defined maturity states

- guides/CODING-GUIDELINES.md
- guides/FAQ.md
- guides/GUIDING-PRINCIPLES.md
- guides/PATTERN-LIFECYCLE.md
- guides/RELEASE-PROCESS.md
- guides/SITE-PACKAGES-AND-THEMES.md
- guides/VERSIONING.md
- guides/WRITING-DOCUMENTATION.md
This PR adds wiki pages to a guides folder. No content changes. This closes #320
> Copy wiki pages over to guides directory

- README.md
- Removed some redundancy in the packages explanation.
- Removed extra text for running locally.
> Minor text updates to README

- packages/core/src/components/TextField/TextField.scss
A border to disabled text boxes 
This closes #409
> Add border to disabled field

- guides/RELEASE-PROCESS.md
Reviewing and updating release documentation
> Update release documentation

- guides/RELEASE-PROCESS.md
- Switched the command being run in step 3 of _Publish to NPM_
- Added `git push` to the list of commands in step 2 of _Create a release commit_
> Update release process documentation

- guides/SITE-PACKAGES-AND-THEMES.md
Update the definition of site package to be more clear about what a site package is and add a definition for what a theme is.
> Updating the definition of site package and theme

- packages/docs/src/scripts/components/Footer.jsx
Changes to on click function for the privacy settings link and adding missing `titlelink` class
> Update onclick function for footer link

- .travis.yml
- package.json
- tools/jest/e2e.config.js
- yarn.lock
Also add a few flags: `--no-sandbox --disable-dev-shm-usage` which probably don't help but can't hurt either.
cf https://github.com/angular/webdriver-manager/issues/404#issuecomment-516952359
> Travis' chrome is broken, so pin chromedriver to the random version they have lying around on their system

- packages/core/src/utilities/font-family.scss
> Fix typo in left nav

- packages/core/src/components/ChoiceList/Choice.jsx
- packages/core/src/components/ChoiceList/ChoiceList.jsx
- packages/core/src/components/ChoiceList/ChoiceList.test.jsx
https://jira.cms.gov/browse/WNMGDS-222
`inputRef` prop to `<Choice>`
`onComponentBlur` prop to `<ChoiceList>`
> [WNMGDS-222] Add onComponentBlur to <ChoiceList>

- .prettierignore
- package.json
- packages/core/src/components/Alert/alert.example.html
- packages/core/src/components/Button/button-icons.example.html
- packages/core/src/components/Button/button-inverse.example.html
- packages/core/src/components/Button/button.example.html
- packages/core/src/components/ChoiceList/checkbox-radio-inverse.example.html
- packages/core/src/components/ChoiceList/checkbox-radio-right-to-left.example.html
- packages/core/src/components/ChoiceList/checkbox-radio-size.example.html
- packages/core/src/components/ChoiceList/checkbox-radio.example.html
- packages/core/src/components/ChoiceList/select.example.html
- packages/core/src/components/Dialog/dialog.example.html
- packages/core/src/components/Dropdown/Dropdown.example.html
- packages/core/src/components/HelpDrawer/help-drawer.example.html
- packages/core/src/components/Review/review.example.html
- packages/core/src/components/Spinner/spinner.example.html
- packages/core/src/components/StepList/steplist.example.html
- packages/core/src/components/Table/table-complex.example.html
- packages/core/src/components/Tabs/tabs.example.html
- packages/core/src/components/TextField/textfield-inverse.example.html
- packages/core/src/components/TextField/textfield.example.html
- packages/core/src/components/VerticalNav/verticalnav.example.html
- packages/docs/src/pages/patterns/documentation-page.example.html
Added linting to Markdown and HTML files that happens during lint-staged when committing automagically.
> [WNMGDS-240] - Adding linting for Markdown and HTML that happens on lint-staged

- packages/core/src/components/DateField/DateField.jsx
> [WNMGDS-299] Update datefield component to use inputRef 

- packages/core/src/components/Badge/Badge.example.jsx
- packages/core/src/components/Badge/Badge.jsx
- packages/core/src/components/Badge/_Badge.docs.scss
- packages/core/src/components/Badge/badge.example.html
- packages/core/src/components/Button/Button.jsx
<Badge> react component and updated react examples.
> [WNMGDS-92] Add react badge component

- lerna.json
- packages/core/package.json
- packages/docs/package.json
- packages/layout/package.json
- packages/support/package.json
Had an issue with NPM not publishing all the packages. Take 2.
> Release v3.4.1

- packages/core/src/utilities/flexbox/_flexbox.docs.scss
- packages/core/src/utilities/flexbox/align-items.example.html
- packages/core/src/utilities/flexbox/flex-direction.example.html
- packages/core/src/utilities/flexbox/flex-wrap.example.html
- packages/core/src/utilities/flexbox/flexbox-responsive.example.html
- packages/core/src/utilities/flexbox/flexbox.scss
- packages/core/src/utilities/flexbox/justify-content.example.html
- `.ds-u-flex-direction-[]` utility and documentation
- Updated the flex-wrap documentation
> [WNMGDS-309] Create flex utilities

- packages/core/src/components/Tabs/Tabs.scss
Commented out animation scss in Tab
> [WNMGDS-366] Remove animation on Tab

- packages/core/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
- packages/core/src/components/Dropdown/Dropdown.example.jsx
- packages/core/src/components/Dropdown/Dropdown.jsx
- `children` prop to `<Dropdown>` to allow for custom options
- additional example for custom options
> [WNMGDS-343] Update dropdown to allow custom options

- packages/docs/src/scripts/components/Header.jsx
- packages/docs/src/scripts/components/UsaBanner.jsx
- packages/docs/src/styles/components/_UsaBanner.scss
- Used responsive flexbox to style banner
- Improved spacing
- Unnecessary USWDS styles including grid classes and css
- Test new banner in multiple browsers and on mobile
> [WNMGDS-345] Improve USA Banner

- packages/core/src/components/Dropdown/Dropdown.jsx
> Add id prop to dropdown 

- packages/core/src/components/Button/Button.jsx
- packages/core/src/components/ChoiceList/Choice.jsx
- packages/core/src/components/ChoiceList/ChoiceList.jsx
- packages/core/src/components/Dropdown/Dropdown.jsx
- packages/core/src/components/FormLabel/FormLabel.jsx
- packages/core/src/components/MonthPicker/MonthPicker.jsx
- packages/core/src/components/MonthPicker/MonthPicker.test.jsx
- packages/core/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
- packages/core/src/components/TextField/TextField.jsx
- `textClassName` prop to replace `labelClassName`
- `labelClassName` prop from `<FormLabel>`
- `labelClassName` prop from `<MonthPicker>`
> [WNMGDS-353] Rename labelClassName prop in <FormLabel>

- .travis.yml
- package.json
- packages/core/src/base/typography/link.scss
- packages/core/src/components/HelpDrawer/HelpDrawer.scss
- tools/jest/e2e.config.js
- tools/jest/e2e.environment.js
- yarn.lock
- Reverted temporary fix [here](https://github.com/CMSgov/design-system/pull/471)
- Run `yarn test:e2e` locally to confirm the e2e tests are working correctly. You might need to update your Chrome for this to work.
- Make sure the travis tests are working
> [WNMGDS-231] Remove chromedriver temporary fix

- .eslintrc
- package.json
- packages/core/src/base/typography/link.scss
- packages/core/src/components/Alert/Alert.scss
- packages/core/src/components/Button/Button.scss
- packages/core/src/components/Dropdown/Dropdown.scss
- packages/core/src/components/HelpDrawer/HelpDrawer.scss
- packages/core/src/utilities/background-color/background-color.scss
- packages/core/src/utilities/text-color/_text-color.docs.scss
- packages/core/src/utilities/text-color/text-color.scss
- packages/docs/src/styles/components/_UsaBanner.scss
- packages/layout/src/index.scss
- yarn.lock
- Upgraded husky and lint-staged
- Added eslint-prettier-config
- Use prettier for scss precommit
> [NO TICKER] Fix precommit hooks

- README.md
> Fix name of USWDS and add link

- package.json
- packages/core/src/components/Button/Button.jsx
- packages/docs/src/scripts/components/GitHubLinks.jsx
- yarn.lock
- react-docgen@5.3.0 for typescript support
- Also includes a small doc site update to fix the inverse button (I included because I didnt want to make a separate branch)
> [WNMGDS-405] Upgrade react-docgen

- packages/design-system-docs/src/pages/components/DateField/datefield.example.html
Update Date field html example to include the autocomplete attributes for birthday.
> [WNMGDS-466] Update Datefield html example

- packages/design-system-docs/src/index.scss
- packages/design-system-docs/src/pages/components/Button/button-icons.example.html
- packages/design-system-docs/src/pages/components/Tabs/tabs.example.html
- packages/design-system-docs/src/pages/styles/icons/interaction-icons.example.html
- packages/design-system-docs/src/pages/styles/icons/status-icons.example.html
- packages/design-system-docs/src/pages/styles/icons/supplemental-icons.example.html
- packages/design-system-docs/src/styles/components/_UsaBanner.scss
- packages/design-system-docs/src/styles/settings/_color.scss
- packages/design-system-docs/src/styles/settings/_index.scss
- packages/design-system-docs/src/styles/utilities/_colors.scss
- packages/design-system-docs/src/styles/utilities/_index.scss
- Fixes image paths for certain examples
- Removes unused doc site SCSS
> [NO_TICKET] Fix icon paths and other misc SCSS updates

- cmsds.config.js
- lerna.json
- package.json
- packages/design-system-docs/.npmignore
- packages/design-system-docs/package.json
- packages/design-system-docs/src/scripts/components/Header.jsx
- packages/design-system-docs/src/scripts/components/Nav.jsx
- packages/design-system-docs/src/scripts/components/UsaBanner.jsx
- packages/design-system-scripts/.npmignore
- packages/design-system-scripts/cli.js
- packages/design-system-scripts/gulp/common/replaceTemplateTags.js
- packages/design-system-scripts/gulp/docs/docs.js
- packages/design-system-scripts/gulp/docs/generatePages/generateDocPage.js
- packages/design-system-scripts/gulp/docs/generatePages/generateHtmlExample.js
- packages/design-system-scripts/package.json
- packages/design-system/.npmignore
- packages/design-system/package.json
- prepublish.sh
- yarn.lock
- Update files from linter
- Remove `rootPath` and `gh-pages`,  no longer needed now that the CBJ jobs are confirmed to be working
> [NO_TICKET] Misc beta updates

- packages/design-system-docs/package.json
Update design-system-docs @cmsgov/design-system dependencies to "2.0.0-beta.5"
> [NO_TICKET] Update dependencies version

- design-assets/cms-design-system-ui-kit.xml
- examples/child-design-system/package.json
- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-docs/src/pages/startup/child-design-systems.md
- packages/design-system-docs/src/pages/startup/installation.md
- packages/design-system-docs/src/scripts/components/Header.jsx
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/design-system/src/components/__tests__/smoke.e2e.test.js
- packages/eslint-config-design-system/package.json
- packages/stylelint-config-design-system/package.json
- prepublish.sh
- Bumped `design-system`, `design-system-docs`, `design-system-scripts` to 2.0.0
- Bumped `eslint-config-design-system` and `stylelint-config-design-system` to 2.0.0
- Updated example package.jsons
- Updated v2 banner copy
- Fixed an e2e test regarding copy
> Release 2.0.0

- babel.config.js
- packages/design-system-scripts/package.json
- yarn.lock
Run site locally, run it on IE11 with sauce labs or virtualbox. I used ngrok to surface my localhost to a public url
> [WNMGDS-592] Add IE11 polyfill

- packages/design-system/src/types/ChoiceList/ChoiceList.d.ts
- packages/design-system/src/types/StepList/StepList.d.ts
- packages/design-system/src/types/VerticalNav/VerticalNav.d.ts
- packages/design-system/src/types/index.d.ts
- Update imports in definition files to not include `d.ts`
> [NO_TICKET] Remove .d.ts from imports

- packages/design-system-scripts/package.json
- packages/design-system/src/components/ChoiceList/ChoiceList.e2e.test.js
- packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/design-system/src/components/FormLabel/FormLabel.jsx
- yarn.lock
- Update chromedriver to 85
- Fix Choice e2e test error
- Add another e2e test specifically for `<Choice>`
> [NO_TICKET] Fix E2E

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> Release 2.0.2

- README.md
- guides/RELEASE-PROCESS.md
- package.json
- prerelease.sh
Update the release process guide.
> [WNMGDS-637] Update release process guide

- packages/design-system-docs/src/scripts/components/CodeSnippet.jsx
- packages/design-system-docs/src/scripts/components/Frame.jsx
- packages/design-system-docs/src/scripts/components/HtmlExample.jsx
- packages/design-system-docs/src/scripts/components/PageHeader.jsx
- packages/design-system/src/components/Tooltip/Tooltip.e2e.test.js
- packages/design-system/src/styles/settings/uswds/_uswds-theme-utilities.scss
> [NO-TICKET] ESLint fixes

- packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
- packages/design-system-docs/src/pages/components/DateField/datefield.example.html
- packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
- packages/design-system-docs/src/pages/components/FormLabel/_FormLabel.docs.scss
- packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
- packages/design-system-docs/src/pages/components/TextField/textfield.example.html
- packages/design-system-scripts/gulp/sass.js
- packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/design-system/src/components/FormLabel/FormLabel.jsx
- packages/design-system/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
- packages/design-system/src/styles/components/_FormLabel.scss
- packages/design-system/src/styles/settings/uswds/_index.scss
This PR fixes the USWDS import to specify the full path, not requiring any additional webpack configuration
This PR also temporarily reverts a ticket merged by NI so our hotfix doesnt introduce any changes
Use the `create-react-app` example to test the local version of the CMSDS
> [WNMGDS-656] Fix USWDS import

- packages/design-system-docs/src/pages/components/Dropdown/Dropdown.example.jsx
- packages/design-system-docs/src/pages/components/Dropdown/_Dropdown.docs.scss
- packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
- Added examples of dropdowns with placeholders
- Added guidance for when to use a placeholder vs a selected default
- run the doc site locally 
- visit the dropdown page and see the updated guidance and examples with placeholders
> [WNMGDS-546] - Add guidance for placeholder dropdowns

- packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
- packages/design-system-docs/src/pages/components/DateField/datefield.example.html
- packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
- packages/design-system-docs/src/pages/components/FormLabel/_FormLabel.docs.scss
- packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
- packages/design-system-docs/src/pages/components/TextField/textfield.example.html
- packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/design-system/src/components/FormLabel/FormLabel.jsx
- packages/design-system/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
- packages/design-system/src/styles/components/_FormLabel.scss
This PR adds back the field error message class work that was reverted for the hotfix
> [NO_TICKET] Add back styles for field error message class

- examples/create-react-app-typescript/package.json
- packages/design-system/src/types/StepList/Step.d.ts
- packages/design-system/src/types/StepList/StepList.d.ts
- packages/design-system/src/types/StepList/SubStep.d.ts
This PR adds changes to StepList definition files that were already incorporated in the HC.gov DS. https://github.cms.gov/CMS-WDS/ds-healthcare-gov/pull/64
Test `StepList` with substeps in the CRA typescript example.
> [NO_TICKET] Update StepList definitions

- design-assets/cms-design-system-ui-kit.xml
- Added a date picker Symbol
- Updated to use Sketch color variables
- Fixed body font in the Sketch file to be 1Body Text as Open Sans, 16`
> Sketch library Release-2.2.0

- packages/design-system/src/types/StepList/Step.d.ts
- packages/design-system/src/types/StepList/StepList.d.ts
- packages/design-system/src/types/StepList/SubStep.d.ts
> Fix substep definition file

- packages/design-system-docs/src/pages/components/HelpDrawer/_HelpDrawer.docs.scss
- Add guidance for help drawer usage
- Refer to [Help drawer link enhancements efforts](https://miro.com/app/board/o9J_kklLajE=/) for further iteration of the guidance content and [help drawer links research](https://miro.com/app/board/o9J_kqbwNQg=/)
- Run the doc site locally
- Visit the help drawer page to check the updated guidance
> [WNMGDS-691] Add guidance for help drawer

- guides/RELEASE-PROCESS.md
- Updated release-process.md to reference the new CBJ url
> [NO_TICKET] Update url for release process

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> Release 2.3.0

- lerna.json
- packages/design-system/src/components/FieldContainer/FieldContainer.tsx
These 2 changes were automatically updated by eslint/prettier after running `yarn test`
> [NO-TICKET] Code format changes by eslint

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> Release 2.4.0

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> Release 2.4.1

- packages/design-system-docs/src/pages/components/Review/Review.example.jsx
- packages/design-system/src/styles/components/_Review.scss
[WNMGDS-764](https://jira.cms.gov/browse/WNMGDS-764)
According to the ticket above, `The Review component includes a grey divider after the last review item, which is not necessary`
[Example below](https://design.cms.gov/patterns/review/), notice that after the last review item, there is an unnecessary gray line:
When viewing this change at [http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-764/remove-review-line](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-764/remove-review-line), the last line of a review item is removed:
- Changed css so that it looks for `last-of-type` with class `ds-c-review` and removes the border on that item
**Some caveats**
- I had to change the example page to make the single component make more sense. It needed to be in …
> [WNMGDS-764] Remove line on last review item

- packages/design-system-docs/src/pages/components/Tooltip/_Tooltip.docs.scss
- packages/design-system/src/styles/components/_Tooltip.scss
- packages/design-system/src/styles/components/_TooltipIcon.scss
When I was looking at the tooltip code a few of the variable names were not very descriptive. 
- I updated a few of them to be more explicit 
- I also added descriptions of what the variables do to the doc site
> [NO-TICKET] Update tooltip variable names and documentation 

- examples/child-design-system/tsconfig.json
- guides/GOVERNANCE.md
- lerna.json
- packages/design-system/src/components/InlineError/InlineError.tsx
- packages/design-system/src/components/flags.ts
- tsconfig.json
Fixes from running `yarn cmsds lint`
> [NO-TICKET] Yarn lint fixes

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> Release 2.5.0

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> Release 2.6.0

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> Release 2.6.1

- guides/WRITING-DOCUMENTATION.md
Added info for what page views are available
> [NO-TICKET] Add page view info

- guides/RELEASE-PROCESS.md
- guides/WRITING-DOCUMENTATION.md
- lerna.json
- packages/design-system/src/components/Alert/Alert.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/TextField/TextField.tsx
- packages/design-system/src/components/TextField/TextInput.tsx
`yarn lint` changes
http://design-system-demo.s3-website-us-east-1.amazonaws.com/ni/lint-fixes
> [NO-TICKET] Lint changes

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> Release core-2.7.0

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
**Please follow the format below and remove any sections that aren't relevant.**
Release 2.7.2
> core-2.7.2

- packages/design-system/src/styles/components/_Button.scss
- packages/design-system/src/styles/settings/variables/_forms.scss
- This is a small addition to the button styling work from https://github.com/CMSgov/design-system/pull/1106 
- Add text decoration variable to button scss
> [NO-TICKET] Add text-decoration to buttons

- packages/design-system/src/components/Button/Button.tsx
Similar to other TS type updates, this PR is to ensure that the appropriate Button types are exported for consumers. This work was originally included in the Button analytics PR, but that work is paused for the forseeable future.
Button component types. Made sure original definition types get exported here too.
http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1010/button-ts-update
Navigate to the Button component in the demo site. Confirm that props table looks okay. Confirm no runtime or build errors.
The original TS definition file for reference: https://github.com/CMSgov/design-system/blob/3515401d3d4da2dc11dcf566f6dad65d7e42b28c/packages/design-system/src/types/Button/Button.d.ts
> button ts type updates

- packages/design-system/src/styles/base/_link.scss
Summary
ISSUE: Mobile view: Underlines in various texts seems to be broken 
DESCRIPTION: When PCII is open in mobile view, texts which are underlined, there seems to be line that is broken in pieces instead of continuous line.
https://jira.cms.gov/browse/WNMGPCII-1515
Fixed
changed value of text-underline-offset from 0 to auto where the browser chooses the appropriate offset for underlines.
https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset
How to test
take a look at the demo url on an iOS device to ensure that the links are not looking broken
http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1064-text-underline-fix-master
**Note:** 
- Add the [Jira ticket number](https://jira.cms.gov/projects/WNMGDS/) to the PR title like this `[WNMGDS-10] - title of …
> WNMGDS-1064 - Fix text-underline bug

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
> core-2.7.4

- packages/design-system-docs/src/pages/components/Button/button.example.html
- packages/design-system/src/components/Button/Button.tsx
- packages/design-system/src/styles/components/_Button.scss
- packages/design-system/src/styles/settings/variables/_color.scss
- packages/design-system/src/styles/settings/variables/_forms.scss
- packages/design-system/src/styles/settings/variables/_index.scss
Revert #1106 and #1117 for now until we can do more discovery and get full buy-in from stakeholders
> Revert #1106 and #1117 (secondary/tertiary buttons)

- packages/design-system/src/components/Alert/Alert.tsx
This must happen before https://github.com/CMSgov/design-system/pull/1143 can be merged successfully
> Merge master into development to resolve conflicts

- lerna.json
- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
Forgot to make a PR for this after last release
> core-2.8.0

- guides/RELEASE-PROCESS.md
- packages/design-system-docs/src/pages/components/Table/table.example.html
- packages/design-system-scripts/helpers/e2e/assertNoAxeViolations.js
- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/Autocomplete/keepInputDownshiftStateReducer.ts
- packages/design-system/src/types/index.d.ts
These commits weren't on `master`. I'm going to delete `development` after this 🤞
> Update master from dev again

- publish.sh
- Fixed syntax error in the publish script
> [NO-TICKET] Fix syntax error in publish bash script

- lerna.json
- packages/design-system/src/styles/base/_link.scss
- packages/ds-healthcare-gov/README.md
- packages/ds-healthcare-gov/docs/src/pages/components/Button/button-secondary.example.html
- packages/ds-healthcare-gov/docs/src/pages/components/DateField/datefield.example.html
- packages/ds-healthcare-gov/src/__mocks__/react-i18next.js
- packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.jsx
- packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.test.jsx
- packages/ds-healthcare-gov/src/components/Footer/Logo.jsx
- packages/ds-healthcare-gov/src/components/Footer/LogosRow.jsx
- packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.jsx
- packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.jsx
- packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.test.jsx
- packages/ds-healthcare-gov/src/components/Header/localeLink.test.js
- packages/ds-healthcare-gov/src/components/Header/loginLink.js
- packages/ds-healthcare-gov/src/components/Header/loginLink.test.js
- packages/ds-healthcare-gov/src/components/Logo/Logo.jsx
- packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsTable.jsx
- packages/ds-healthcare-gov/src/components/PrivacySettings/privacySettings.test.js
- packages/ds-healthcare-gov/tsconfig.json
See https://github.com/CMSgov/design-system/pull/1201. This PR is separate because it touches a lot of files. When running the linter, it automatically updates files that changed after running prettier.
> [WNMGDS-1175] Run prettier on ds-healthcare-gov files

- guides/RELEASE-PROCESS.md
After Sarah ran through the new release script on Friday for the beta release, she identified some holes in the docs.
> [NO-TICKET] Update the release docs to address beta releases

- rfcs/2021-10-icons-in-core-DS.md
As part of some icon work discovery, it was called out that Mgov overwrites icons in some components using CSS. Updated the RFC to propose a plan to address that
* Are there other considerations that need to be accounted for?
> [WNMGDS-1178] icon rfc update for mgov

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
Merge the version bumps into master
> Release 2.10.0

- packages/design-system/src/components/Pagination/Pagination.stories.jsx
- packages/design-system/src/components/Tabs/Tabs.stories.jsx
Added a storybook story for the Pagination component
Default Pagination
Pagination with hidden next/prev on extremities
Compact Pagination
run `yarn storybook` and see the new pagination stories, play with args to confirm they update
> [WNMGDS-1243] Add Storybook stories for Pagination

- packages/design-system/src/components/Autocomplete/Autocomplete.stories.jsx
Added storybook stories for the Autocomplete component
run `yarn storybook` and see the new Autocomplete stories, play with args to confirm they update
> [WNMGDS-1150] Add Storybook stories for Autocomplete

- packages/design-system/src/components/StepList/StepList.stories.jsx
Adding story for Step List pattern. I copied the test data from the current doc site example.
❓ The current doc site example, doesn't really have any interactivity, so I'm not sure if this story should ❓ 
Run `yarn storybook` and examine the Step List story.
> [WNMGDS-1152] step list story

- examples/create-react-app-typescript/package.json
- examples/create-react-app-typescript/src/components/Examples/PaginationExample.tsx
- packages/design-system/src/types/Dialog/Dialog.d.ts
- packages/design-system/src/types/HelpDrawer/HelpDrawer.d.ts
Integration tests for three downstream products were failing due to these TypeScript errors.
This will be cherry-picked onto the current beta release, and we'll release a new beta.
- Fixed optional prop in Dialog being marked as required in TypeScript definitions
- Fixed optional props in HelpDrawer being marked as required in TypeScript definitions
- Fixed TypeScript example project missing required props for Pagination
1. Build core package with `yarn build`
2. In the `examples/create-react-app-typescript` example project, set the core package version to `file:../../packages/design-system`
3. Clear the example's `node_modules` if it's old
4. In `examples/create-react-app-typescript`, `yarn install`
5. In `examples/create-react-app-typescript`, `yarn start`. The example app should work
> [NO-TICKET] Fix known typing bugs

- guides/RELEASE-PROCESS.md
Updating release process docs to encourage usage of Jenkins job
> [NO-TICKET] updated release process docs

- packages/design-system/src/components/Button/Button.tsx
See notes in code. This needs more thorough testing.
> Simplify Button types

- packages/design-system/src/components/Button/Button.stories.jsx
- packages/design-system/src/components/Button/Button.test.tsx
- packages/design-system/src/components/Button/Button.tsx
- Deprecated `Button` component's `component` prop
> [NO-TICKET] Deprecate Button's "component" prop

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- @cmsgov/design-system-docs@3.0.2-beta1
- @cmsgov/design-system-scripts@3.0.2-beta1
- @cmsgov/design-system@3.0.2-beta1
- @cmsgov/ds-healthcare-gov@7.0.2-beta1
- @cmsgov/ds-medicare-gov@5.0.2-beta1
> Beta Release 02/01/22 - 3.0.2-beta1

- packages/design-system-docs/src/pages/utilities/layout-grid/_grid.docs.scss
Minor content adjustments based on PR feedback
> [NO-TICKET] PR feedback - Update the grid guidance

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- @cmsgov/design-system-docs@3.1.0-beta.1
- @cmsgov/design-system-scripts@3.1.0-beta.1
- @cmsgov/design-system@3.1.0-beta.1
- @cmsgov/ds-healthcare-gov@7.1.0-beta.1
- @cmsgov/ds-medicare-gov@5.1.0-beta.1
> Beta release 3.1.0-beta.1

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
Bumping tags for release
@cmsgov/design-system-docs@3.3.0-beta.1
@cmsgov/design-system-scripts@3.3.0-beta.1
@cmsgov/design-system@3.3.0-beta.1
@cmsgov/ds-healthcare-gov@7.3.0-beta.1
@cmsgov/ds-medicare-gov@5.3.0-beta.1
> 3.3.0-beta.1 tag bump to master

- packages/design-system/src/components/FilterChip/FilterChip.test.jsx
- packages/design-system/src/components/FilterChip/FilterChip.tsx
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-1247)
Update component to follow prescribed screenreader readout.
Overview of changes
- Updated markup to support `aria-describedby` attribute
- Updated tests to account for new text node in component
Visit [FilterChip](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1247/update-filterchip-label/core/storybook/?path=/story/components-filter-chip--single-chip) in Safari and use Mac VoiceOver to navigate example. 
Expected readout should be along the lines of:
> Filter label [pause] remove filter label [pause] button
> [WNMGDS-1247] Update screen reader readout

- packages/design-system/src/components/MonthPicker/MonthPicker.tsx
> [WNMGDS-1580] Use i18n for MonthPicker content

- packages/design-system/src/components/Pagination/Pagination.test.tsx
- packages/design-system/src/components/Pagination/Pagination.tsx
- packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/design-system/src/components/locale/en.json
- packages/design-system/src/components/locale/es.json
> [WNMGDS-1580] Use i18n in Pagination and migrate tests to testing-library

- packages/design-system/src/components/Review/Review.tsx
- packages/design-system/src/components/SkipNav/SkipNav.tsx
- packages/design-system/src/components/Spinner/Spinner.tsx
- packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.test.tsx
- packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.tsx
- packages/design-system/src/components/VerticalNav/__snapshots__/VerticalNavItemLabel.test.tsx.snap
- packages/design-system/src/components/locale/en.json
- packages/design-system/src/components/locale/es.json
> [WNMGDS-1580] Use i18n for remaining components

- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/DateField/DateField.tsx
- packages/design-system/src/components/DateField/DateInput.tsx
- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Drawer/Drawer.tsx
- packages/design-system/src/components/FilterChip/FilterChip.test.jsx
- packages/design-system/src/components/FilterChip/FilterChip.tsx
- packages/design-system/src/components/locale/en.json
- packages/design-system/src/components/locale/es.json
> [WNMGDS-1580] Use i18n for components A-F

- packages/design-system/src/components/Accordion/AccordionItem.tsx
- packages/design-system/src/components/locale/en.json
- packages/design-system/src/components/locale/es.json
> [WNMGDS-1580] Use i18n in Accordion

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- @cmsgov/design-system-docs@3.4.0-beta.1
- @cmsgov/design-system-scripts@3.4.0-beta.1
- @cmsgov/design-system@3.4.0-beta.1
- @cmsgov/ds-healthcare-gov@7.4.0-beta.1
- @cmsgov/ds-medicare-gov@5.4.0-beta.1
Please review the draft release notes here: https://github.com/CMSgov/design-system/releases/edit/untagged-b371298e3c7e182edbf9
> Beta release 3.4.0-beta.1

- packages/docs/content/5_components/alert.mdx
- packages/docs/content/5_components/button.mdx
- packages/docs/content/5_components/checkbox-and-radio.mdx
- packages/docs/content/5_components/date-field.mdx
- packages/docs/content/5_components/drawer.mdx
- packages/docs/content/5_components/dropdown.mdx
- packages/docs/content/5_components/filter-chip.mdx
- packages/docs/content/5_components/form-label.mdx
- packages/docs/src/components/PropTable.tsx
Content migration for following components:
* Button
* Checkbox / Radio
* Date Field
* Drawer
* Dropdown
* Filter chip
* Form label
Also had to update the PropTable component because it wasn't showing simple types like `string` or `boolean`. But now it is!
`yarn build-storybook:gatsby` to build storybook once
`yarn build:gatsby && yarn serve:gatsby` to see doc site locally with storybook
> [WNMGDS-1597] component content pt 2

- packages/docs/content/1_getting-started/1_using-sass-and-cSS.mdx
- packages/docs/src/components/DocSiteSidebar.tsx
- packages/docs/src/components/InfoPage.tsx
- packages/docs/src/components/Layout.tsx
- packages/docs/src/helpers/graphQLTypes.ts
* Using gatsby-provided `location` variable to determine current place in nav
* Set 'selected' attribute in nav
* Renaming the `using sass & CSS` page. Not content changes
If you want to just see the nav in action, can run `yarn start:gatsby`
> [WNMGDS-1599] state for vertical nav

- packages/design-system/src/components/StepList/StepList.stories.jsx
- packages/design-system/src/components/patterns/documentationPage.stories.tsx
- packages/design-system/src/components/patterns/thirdPartyExternalLinks.stories.tsx
- packages/docs/content/6_patterns/1_overview.mdx
- packages/docs/content/6_patterns/documentation-page.mdx
- packages/docs/content/6_patterns/review.mdx
- packages/docs/content/6_patterns/step-list.mdx
- packages/docs/content/6_patterns/third-party-external-link.mdx
- packages/docs/src/pages/index.tsx
* Content migration for:
* Documentation Page pattern
* Review pattern
* Step List pattern
* Third party, external link pattern
`yarn build-storybook:gatsby` to build storybook once
`yarn build:gatsby && yarn serve:gatsby` to see doc site locally with storybook
> [WNMGDS-1598] patterns content

- packages/docs/package.json
- release.sh
updates doc site package definition for use with release.sh to be tagged appropriately.
> No Ticket - ignoring private branches during lerna version

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- @cmsgov/design-system-docs@3.6.0-beta.1
- @cmsgov/design-system-scripts@3.6.0-beta.1
- @cmsgov/design-system@3.6.0-beta.1
- @cmsgov/cms-design-system-docs@3.6.0-beta.1
- @cmsgov/ds-healthcare-gov@7.6.0-beta.1
- @cmsgov/ds-medicare-gov@5.6.0-beta.1
> 3.6.0-beta.1 Release Version Bump

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- @cmsgov/design-system-docs@3.6.0-beta.2
- @cmsgov/design-system-scripts@3.6.0-beta.2
- @cmsgov/design-system@3.6.0-beta.2
- @cmsgov/cms-design-system-docs@3.6.0-beta.2
- @cmsgov/ds-healthcare-gov@7.6.0-beta.2
- @cmsgov/ds-medicare-gov@5.6.0-beta.2
> 3.6.0-beta.2 Release version bump

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- @cmsgov/design-system-docs@3.6.0-beta.3
- @cmsgov/design-system-scripts@3.6.0-beta.3
- @cmsgov/design-system@3.6.0-beta.3
- @cmsgov/cms-design-system-docs@3.6.0-beta.3
- @cmsgov/ds-healthcare-gov@7.6.0-beta.3
- @cmsgov/ds-medicare-gov@5.6.0-beta.3
> Release 3.6.0-beta.3

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- @cmsgov/design-system-docs@3.7.0-beta.1
- @cmsgov/design-system-scripts@3.7.0-beta.1
- @cmsgov/design-system@3.7.0-beta.1
- @cmsgov/cms-design-system-docs@3.7.0-beta.1
- @cmsgov/ds-healthcare-gov@7.7.0-beta.1
- @cmsgov/ds-medicare-gov@5.7.0-beta.1
> Release 3.7.0-beta.1

- packages/design-system/src/styles/settings/variables/_reference.scss
- Fixes backward compatibility for token update
> [BUGFIX] Restore a reference to an old sass variable

- packages/docs/content/not-in-sidebar/intro.mdx
> [NO-TICKET] Fix typos in Introduction

- packages/docs/content/components/button.mdx
- packages/docs/content/getting-started/migrating-to-new-buttons.mdx
- packages/docs/src/components/ButtonMigrationTable.tsx
- packages/docs/src/components/ButtonVariationsTable.tsx
- packages/docs/src/components/ContentRenderer.tsx
- packages/docs/src/components/ThemeContent.tsx
- packages/docs/src/styles/components/buttonMigrationTable.scss
- packages/docs/src/styles/index.scss
https://jira.cms.gov/browse/WNMGDS-1727
I created a button migration page with the script section left blank for now.
[Demo link](https://cmsgov.github.io/design-system/branch/pwolfert/new-button-migration-docs)
> [WNMGDS-1727] Add button migration doc page

- README.md
- packages/docs/README.md
Updated / added some documentation for commands to be used for gatsby doc site
> [NO-TICKET] documentation updates for running the gatsby doc site

- packages/design-system/src/components/Icons/icons.stories.tsx
- packages/docs/content/components/card.mdx
- packages/docs/content/components/footer/medicare-footer.mdx
- packages/docs/content/components/header/medicare-header.mdx
- packages/docs/content/components/icon.mdx
- packages/docs/content/components/logos/hhs-logo.mdx
- packages/docs/content/components/logos/medicare-logo.mdx
- packages/docs/content/components/stars.mdx
- packages/docs/gatsby-config.ts
- packages/docs/src/components/InfoPage.tsx
- packages/docs/src/components/StorybookExample.tsx
- packages/ds-healthcare-gov/src/components/Accordion/Accordion.stories.jsx
- packages/ds-healthcare-gov/src/components/Footer/Footer.stories.jsx
- packages/ds-healthcare-gov/src/components/Header/Header.stories.jsx
- packages/ds-healthcare-gov/src/components/Logo/Logo.stories.tsx
- packages/ds-medicare-gov/src/components/Card/Card.stories.jsx
- packages/ds-medicare-gov/src/components/Card/Card.tsx
- packages/ds-medicare-gov/src/components/GlobalHeader/GlobalHeader.stories.jsx
- packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.jsx
- packages/ds-medicare-gov/src/components/Icons/icons.stories.tsx
- packages/ds-medicare-gov/src/components/MedicaregovLogo/medicaregovLogo.stories.tsx
- packages/ds-medicare-gov/src/components/Navbar/Navbar.stories.jsx
- packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.stories.jsx
- packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
- packages/ds-medicare-gov/src/components/Stars/Stars.tsx
- packages/ds-medicare-gov/src/components/Stars/stars.stories.tsx
Adding docs for medicare's `Card`, `Stars`, Header & Footer. This includes adding some storybook stories to support these components.
`yarn build-storybook:gatsby` `yarn build:gatsby` `yarn serve`
> [WNMGDS-1830] pt 2 mgov components

- packages/docs/src/pages/feedback.tsx
- packages/docs/src/pages/index.tsx
- Configures the feedback page to...
- Have a sidebar with table of contents
- Have the intro text in the header from the mdx frontmatter
> [NO-TICKET] Add sidebar TOC and header intro text to the feedback page

- packages/docs/src/components/TableOfContents.tsx
https://jira.cms.gov/browse/WNMGDS-1866
- Change the copy used in the discussion link
> [WNMGDS-1866] Change the discussion link text

- packages/design-system/src/components/TextField/Mask.test.tsx
- packages/design-system/src/components/TextField/__snapshots__/Mask.test.tsx.snap
https://jira.cms.gov/browse/WNMGDS-1871
> [WNMGDS-1871] Migrate unit tests for Mask to RTL

- packages/docs/src/components/DocSiteFooter.tsx
- `console.log`'ging the address change requested for gameday
1. `yarn install && yarn start` - validate address shows in console
> [GAMEDAY] Adding console log to footer with gameday address change

- packages/docs/content/foundation/typography/body.mdx
- packages/docs/content/patterns/phone-numbers.mdx
- Moved phone number pattern from body typography page to it's own page under patterns.
1. Run the doc site locally `yarn start` and view the phone numbers page under patterns.
> [NO-TICKET] Phone number pattern

- packages/design-system/src/components/StepList/Step.test.jsx
- packages/design-system/src/components/StepList/StepLink.test.jsx
- packages/design-system/src/components/StepList/StepList.test.jsx
- packages/design-system/src/components/StepList/SubStep.test.jsx
- packages/design-system/src/components/StepList/__snapshots__/Step.test.jsx.snap
- packages/design-system/src/components/StepList/__snapshots__/StepList.test.jsx.snap
- Updates of `StepList`, `SubStep`, `Step`, and `StepLink` to react testing library
- https://jira.cms.gov/browse/WNMGDS-1874
1. `yarn install && yarn test:unit`
> [WNMGDS-1874] StepList rtl conversion

- packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-1954)
Update mgov footer link because [Slack said so](https://cmsgov.slack.com/archives/CT169N26L/p1664807173241069).
1. Pull this branch
2. Build for mgov Storybook
3. Visit http://localhost:6006/?path=/story/medicare-simplefooter--default&globals=theme:medicare and confirm url for "Using this site" has been updated
> [WNMGDS-1954] Update mgov footer link

- packages/design-system/src/components/Drawer/Drawer.test.tsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.test.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeout.test.tsx
- packages/design-system/src/components/TextField/TextField.stories.jsx
- packages/design-system/src/components/utilities/useClickOutsideHandler.test.tsx
- packages/docs/gatsby-node.js
- packages/ds-healthcare-gov/src/components/Logo/Logo.stories.tsx
- Fixed several linting warnings in javascript, mostly tests
- It looks like with the upgrade to React 17 we'll get a bunch of the remaining ones fixed as well, mostly around the no-unused-vars not being picked up when they shouldn't
1. `yarn lint && yarn test`
> [WNMGDS-1928] EsLint Linting Fixes

- packages/design-system/src/components/Alert/Alert.stories.jsx
- packages/design-system/src/components/Autocomplete/Autocomplete.stories.jsx
- packages/design-system/src/components/Badge/Badge.stories.jsx
- packages/design-system/src/components/ChoiceList/Choice.stories.jsx
- packages/design-system/src/components/DateField/SingleInputDateField.stories.jsx
- packages/design-system/src/components/Dialog/Dialog.stories.jsx
- packages/design-system/src/components/Drawer/Drawer.stories.jsx
- packages/design-system/src/components/FilterChip/FilterChip.stories.jsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.stories.jsx
- packages/design-system/src/components/IdleTimeout/IdleTimeout.stories.jsx
- packages/design-system/src/components/Pagination/Pagination.stories.jsx
- packages/design-system/src/components/Review/Review.stories.jsx
- packages/design-system/src/components/TextField/TextField.stories.jsx
Relates to https://github.com/CMSgov/design-system/pull/2174 and https://github.com/CMSgov/design-system/pull/2193.
- Improves the story controls and action logging for stories so they live up to the standards laid out in [our maturity checklist criteria](https://github.com/CMSgov/design-system/pull/2193)
Browse the stories in Storybook
> [NO-TICKET] Improve controls and action logging for stories

- .stylelintrc.js
- packages/docs/src/styles/components/embeddedExamples.scss
- packages/docs/src/styles/components/footer.scss
- packages/docs/src/styles/components/maturityChecklist.scss
- packages/docs/src/styles/components/navigation.scss
- packages/docs/src/styles/components/responsiveExample.scss
- packages/docs/src/styles/components/spacingUtilityExampleList.scss
- packages/docs/src/styles/components/storybookExample.scss
- packages/docs/src/styles/components/syntaxHighlighting.scss
- packages/docs/src/styles/components/tableOfContents.scss
- packages/docs/src/styles/pages/contact.scss
- packages/docs/src/styles/pages/layout.scss
https://jira.cms.gov/browse/WNMGDS-1950
This is to merge some more work into Forrest's delinting branch that resolves errors back to the baseline we have on `main`.
`yarn lint:stylelint`
> [WNMGDS-1950] Contribute to a CSS delinting branch

- README.md
> [NO-TICKET] Remove documentation about a loki-runner error in readme

- packages/docs/content/blog/index.mdx
- packages/docs/src/components/content/PageFeedback.tsx
Asks readers of the blog whether it was helpful and reports the answer to NewRelic.
1. Go to https://cmsgov.github.io/design-system/branch/pwolfert/blog-article-feedback/blog, and scroll to the bottom
2. Click yes or no
> [NO-TICKET] Add a feedback widget to the blog article

- README.md
- From #1952 
- Updates contact information from broken email address to our doc site contact page.
> [NO-TICKET] updating contact information in README.md

- packages/docs/content/components/button.mdx
- Updates from DSM on button guidance
1. run `yarn start` and visit the button page and see that the guidance has been added for Mgov
> [WNMGDS-2020] Updates from DSM on button guidance

- packages/design-system/src/components/StepList/StepList.tsx
WNMGDS-2005
Removing prop from wrapper StepList component.
> [WNMGDS-2005] Remove prop from StepList

- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- @cmsgov/design-system@5.0.0
- @cmsgov/cms-design-system-docs@5.0.0
- @cmsgov/ds-healthcare-gov@9.0.0
- @cmsgov/ds-medicare-gov@7.0.0
> Version bump for 5.0.0

- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 11/23 Version bump main

- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 12/08 Version bump main

- README.md
Creating a copy of https://github.com/CMSgov/design-system/pull/2290 so we can update it with `main`
> [NO-TICKET] Update link to lerna site in the readme

- package.json
- scripts/maturityCheck.sh
- A simple bash script to show current maturity model completion
1. `yarn check:maturity`
> [NO-TICKET] check:maturity script

- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 01/13 Version bump main

- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 01/20 Version bump main

- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 01/23 Version bump main

- packages/docs/content/foundation/theme-colors.mdx
- Better organized and categorized the theme color page
1. `yarn start` and visit the theme color page and see the colors contain a neutrals category as well as sub categories for status (success, warn, error)
> [NO-TICKET] Theme color organization

- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 01/26 Version bump main

- packages/docs/content/foundation/system-color-tokens.mdx
- Adding more textual context to our system tokens page.
- non ticked change
> [NO-TICKET] Adding more context to our system color tokens.

- .storybook/static/healthcare-theme.css
- packages/docs/static/themes/healthcare-theme.css
- packages/ds-healthcare-gov/src/styles/healthcare-theme.css
I'm not sure how this change didn't get committed in #2384, but the current head of `main` outputs these changes when you build. According to the changes in #2384, these are what these values should be.
> [NO-TICKET] Update built healthcare theme from #2384

- packages/design-system-tokens/sketch/cmsds-token-importer/README.md
- Add more details for how to get the theme exported as JSON
> [NO-TICKET] Adding detail to the readme

- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-cms-gov/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 03/22 Version bump main

- examples/create-react-app-typescript/package.json
- examples/create-react-app-typescript/src/index.tsx
- examples/create-react-app-typescript/src/styles/index.scss
- packages/design-system/package.json
- packages/ds-cms-gov/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
[Slack context](https://adhoc.slack.com/archives/C645GLLNN/p1682958496215719?thread_ts=1682950441.379409&cid=C645GLLNN).
Fix for importing CSS
> [NO-TICKET] Fix package exports

- packages/docs/content/guidelines/accessibility.mdx
- Added table of devices and systems tested with to the a11y page on the doc site 
- This information was migrated from the assets.cms.gov site and updated with the help of @SparrowSpit 
1. run the doc site with `yarn-start` visit the a11y page under guidelines and see the table listing OSs tested with
> [WNMGDS-2306] Add devices tested with to a11y page - part of assets migration

- packages/ds-healthcare-gov/src/components/Footer/LogosRow.tsx
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.tsx.snap
- packages/ds-healthcare-gov/src/components/locale/en.json
- packages/ds-healthcare-gov/src/components/locale/es.json
WNMGDS-2404
Update language in mgov footer.
English translation has trademark language.
Spanish translation does have trademark language. Also corrected incorrect Spanish language.
> [WNMGDS-2404] Update language in mgov footer to remove trademark language 

- packages/docs/content/blog/release-7.0.mdx
- Edit some wording in the v7 blog post to avoid giving the impression that teams should change the dropdown style
> [NO-TICKET] Wording change to v7 blog post

- packages/design-system/src/components/Dropdown/index.ts
WNMGDS-2441
Export all types related to the dropdown component
> [WNMGDS-2441] Export all types related to the dropdown component

- packages/design-system/src/styles/components/_Dropdown.scss
WNMGDS-2451
Adding ability for keyboard scrolling in Dropdown
> [WNMGDS-2451] Add ability for keyboard scroll in dropdown list

- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
WNMGDS-2453
Added `type="button"` to dropdown toggle to prevent form submissions
> [WNMGDS-2453] Add `type="button"` to dropdown toggle to prevent form submissions

- packages/design-system/src/components/SkipNav/SkipNav.stories.tsx
- packages/docs/content/layouts/Healthcare/one-col-page-layout.stories.tsx
- [Make it easier to see the SkipNav working in the story](https://github.com/CMSgov/design-system/commit/e8da6f70aae24000f2738462a3c2c1f2f98f9a83)
- [Further refine the SkipNav story content](https://github.com/CMSgov/design-system/commit/a6af29d96fed0e600a48b3c65935bbad43de68c6)
- [The one-page-layout is only for healthcare, so make it healthcare themed](https://github.com/CMSgov/design-system/commit/1b8e31d7fc37bb2f66f75bdbfc58af7b94dfd99d)
Start Storybook
> [NO-TICKET] Story refinement (SkipNav, one-col-page layout)

- packages/design-system/src/components/Drawer/Drawer.tsx
- packages/design-system/src/components/Drawer/DrawerManager.tsx
- packages/design-system/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap
- packages/design-system/src/components/Dropdown/Dropdown.test.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/design-system/src/components/FilterChip/FilterChip.test.tsx
- packages/design-system/src/components/FilterChip/FilterChip.tsx
- packages/design-system/src/components/FilterChip/__snapshots__/FilterChip.test.tsx.snap
- packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawer.test.tsx.snap
One of several PRs into https://github.com/CMSgov/design-system/pull/2633, this PR updates the following components:
- Drawer/HelpDrawer
- Dropdown
- FilterChip
> [WNMGDS-2369] Id update set 1

- packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.tsx
- packages/design-system/src/components/ChoiceList/__snapshots__/Choice.test.tsx.snap
- packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap
- packages/design-system/src/components/DateField/DateInput.test.tsx
- packages/design-system/src/components/DateField/DateInput.tsx
- packages/design-system/src/components/DateField/MultiInputDateField.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.tsx
- packages/design-system/src/components/DateField/__snapshots__/DateInput.test.tsx.snap
- packages/design-system/src/components/DateField/__snapshots__/MultiInputDateField.test.tsx.snap
- packages/design-system/src/components/DateField/__snapshots__/SingleInputDateField.test.tsx.snap
- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/design-system/src/components/FormLabel/useFormLabel.tsx
- packages/design-system/src/components/InlineError/InlineError.tsx
- packages/design-system/src/components/InlineError/__snapshots__/InlineError.test.tsx.snap
- packages/design-system/src/components/MonthPicker/MonthPicker.tsx
- packages/design-system/src/components/MonthPicker/__snapshots__/MonthPicker.test.tsx.snap
- packages/design-system/src/components/PrivacySettingsDialog/__snapshots__/PrivacySettingsTable.test.jsx.snap
- packages/design-system/src/components/TextField/LabelMask.test.tsx
- packages/design-system/src/components/TextField/Mask.test.tsx
- packages/design-system/src/components/TextField/TextField.test.tsx
- packages/design-system/src/components/TextField/TextField.tsx
- packages/design-system/src/components/TextField/TextInput.test.tsx
- packages/design-system/src/components/TextField/__snapshots__/LabelMask.test.tsx.snap
- packages/design-system/src/components/TextField/__snapshots__/Mask.test.tsx.snap
- packages/design-system/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/design-system/src/components/TextField/__snapshots__/TextInput.test.tsx.snap
- packages/design-system/src/components/TextField/__snapshots__/useLabelMask.test.tsx.snap
- packages/design-system/src/components/TextField/useLabelMask.test.tsx
- packages/design-system/src/components/TextField/useLabelMask.tsx
One of several PRs into https://github.com/CMSgov/design-system/pull/2633, this PR updates the following components:
- All components that use form labels
> [WNMGDS-2369] Id update set 2

- packages/design-system/src/components/ChoiceList/__snapshots__/Choice.test.tsx.snap
- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/design-system/src/components/FilterChip/FilterChip.tsx
- packages/design-system/src/components/FilterChip/__snapshots__/FilterChip.test.tsx.snap
- packages/design-system/src/components/InlineError/InlineError.tsx
- packages/design-system/src/components/InlineError/__snapshots__/InlineError.test.tsx.snap
- packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
Remove icon ids that are now optional as of https://github.com/CMSgov/design-system/pull/2644
> [WNMGDS-2369] Remove icon ids that are now optional

- packages/design-system/src/components/DateField/SingleInputDateField.test.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.tsx
- packages/design-system/src/components/DateField/__snapshots__/SingleInputDateField.test.tsx.snap
Fix dynamic icon ids in SingleInputDateField
> [WNMGDS-2369] Fix dynamic icon ids in SingleInputDateField

- packages/docs/content/foundation/typography/headings.mdx
> [NO-TICKET] Correct typo on heading docs

- packages/docs/content/guidelines/accessibility.mdx
WNMGDS-2158
We don't mention the maturity model checklists anywhere on our Accessibility page, so I've added it.
> [WNMGDS-2158] Mention our component maturity checklists on the Accessibility page

- packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
WNMGDS-2509
Update the URL for the "Linking Policy" link in the medicare footer
View the medicare footer story, and click the "Linking Policy" link. It should go to a real page and not a 404
> [WNMGDS-2509] Update the URL for the "Linking Policy" link in the medicare footer

- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
Add some basic documentation for Autocomplete in Storybook and the code for how it should fit together.
> [WNMGDS-2512] Document how Autocomplete should work in React

- packages/design-system/src/styles/_mixins.scss
- packages/design-system/src/styles/components/_Accordion.scss
- packages/design-system/src/styles/components/_Alert.scss
- packages/design-system/src/styles/components/_Autocomplete.scss
- packages/design-system/src/styles/components/_Badge.scss
- packages/design-system/src/styles/components/_ChoiceList.scss
- packages/design-system/src/styles/components/_Dialog.scss
- packages/design-system/src/styles/components/_Drawer.scss
- packages/design-system/src/styles/components/_Dropdown.scss
- packages/design-system/src/styles/components/_FilterChip.scss
- packages/design-system/src/styles/components/_Pagination.scss
- packages/design-system/src/styles/components/_Review.scss
- packages/design-system/src/styles/components/_SingleInputDateField.scss
- packages/design-system/src/styles/components/_Spinner.scss
- packages/design-system/src/styles/components/_StepList.scss
- packages/design-system/src/styles/components/_SvgIcon.scss
- packages/design-system/src/styles/components/_Tabs.scss
- packages/design-system/src/styles/components/_TextField.scss
- packages/design-system/src/styles/components/_Tooltip.scss
- packages/design-system/src/styles/components/_TooltipIcon.scss
- packages/design-system/src/styles/components/_VerticalNav.scss
- packages/docs/src/styles/components/filterDialog.scss
- packages/docs/src/styles/components/navigation.scss
- packages/docs/src/styles/components/syntaxHighlighting.scss
- packages/ds-healthcare-gov/src/styles/components/_Accordion.scss
WNMGDS-2502
- Remove IE prefixed HCM query (it's deprecated)
> [WNMGDS-2502] Remove IE prefixed HCM query

- packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
- packages/design-system/src/components/Dropdown/DropdownMenu.tsx
- packages/design-system/src/components/Dropdown/DropdownMenuOption.tsx
WNMGDS-2531
- Fixes a behavior on mobile devices where tapping an option in the dropdown menu will accidentally click any elements behind the menu
Here's a video showing the red button's click event being triggered accidentally. It shouldn't do this in this branch. To test, check out one of the commits before 0a7354024cdf450a8a8540ad58b4f477732ac694.
https://github.com/CMSgov/design-system/assets/7595652/1da8b4a0-c384-4b49-a2f8-e8f2899d9aa5
See also: [Demo story with fix](https://cmsgov.github.io/design-system/branch/pwolfert/fix-dropdown-tap-through/storybook/?path=/story/components-dropdown--tap-through)
If you take a look at the commit messages and the Jira ticket comments, I mention that the workaround this is based on does not work well with scrolling. The first version of the …
> [WNMGDS-2531] Fix dropdown tap-through

- packages/design-system/src/components/ChoiceList/Choice.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.tsx
- packages/design-system/src/components/DateField/MultiInputDateField.tsx
- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Hint/Hint.tsx
- packages/design-system/src/components/Label/Label.tsx
- packages/design-system/src/components/MonthPicker/MonthPicker.tsx
- packages/design-system/src/components/TextField/TextField.tsx
- packages/design-system/src/components/VerticalNav/VerticalNav.stories.tsx
- packages/design-system/src/components/VerticalNav/VerticalNav.tsx
- packages/design-system/src/components/VerticalNav/VerticalNavItem.tsx
- packages/docs/content/components/dropdown.mdx
- packages/docs/content/foundation/layout-grid/layout-grid.mdx
WNMGDS-2540
- Fixes a bunch of references to the `{{root}}` template string that no longer exists
- In some cases replacing that link with one that is up-to-date
- In some cases removing the link and providing better information
1. Check the affected links in storybook and the doc site
> [WNMGDS-2540] Fix dead links in docs

- .storybook/static/cmsgov-theme.css
- .storybook/static/core-theme.css
- .storybook/static/healthcare-theme.css
- .storybook/static/medicare-theme.css
- packages/design-system/src/styles/core-theme.css
- packages/docs/static/themes/cmsgov-theme.css
- packages/docs/static/themes/core-theme.css
- packages/docs/static/themes/healthcare-theme.css
- packages/docs/static/themes/medicare-theme.css
- packages/ds-cms-gov/src/styles/cmsgov-theme.css
- packages/ds-healthcare-gov/src/styles/healthcare-theme.css
- packages/ds-medicare-gov/src/styles/medicare-theme.css
These CSS token files got out of date on main
> [NO-TICKET] Update CSS files after token changes

- .github/PULL_REQUEST_TEMPLATE.md
No ticket.
Updating PR template to include design approval requirement if VRTs have been updated.
> [NO TICKET] Include designer approval as requirement

- packages/docs/content/foundation/layout-grid/responsive-design.mdx
- Update list of items that support breakpoint prefixes
- Add the display property and alphabetize the list for easier searching
> [NO-TICKET] Update list of items that support breakpoint prefixes

- packages/docs/content/components/spinner.mdx
Fix a dead link in the Spinner guidance
> [NO-TICKET] Fix a dead link in the Spinner guidance

- packages/docs/static/themes/cmsgov-theme.css
This didn't get built and added to version control in #2882. We probably need to update our build system or CI to make sure we can't make it all the way to merging without this getting built.
> [NO-TICKET] Rebuild theme file in static doc-site files

- packages/design-system/src/components/IdleTimeout/IdleTimeout.test.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeout.tsx
- packages/design-system/src/components/locale/en.json
- packages/design-system/src/components/locale/es.json
- tests/browser/snapshots/storybook-docs/Docs-Components-IdleTimeout-Docs-prop-table-matches-snapshot-1.txt
WNMGDS-2637
Add i18n to IdleTimeout component.
> [WNMGDS-2637] Idle timeout spanish translations

- packages/docs/content/blog/release-7.0.mdx
See affected release blog post.
> [NO-TICKET] Add warning in docs to skip v7

- packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.test.tsx
- packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.tsx
Fix typo in `ds-dropdown` `requirement-label` attribute definition. Didn't affect storybook docs because we got it right there.
> [NO-TICKET] 

- packages/design-system/src/components/Drawer/Drawer.tsx
- packages/design-system/src/components/Drawer/DrawerManager.stories.tsx
- packages/design-system/src/components/Drawer/DrawerManager.tsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.test.tsx
> [WNMGDS-2737] Add ability to spread props on drawer

- .storybook/preview.tsx
Update some settings after a live debug session with the analytics team. See comments for details.
> [NO-TICKET] Small changes for analytics testing

- packages/docs/content/components/analytics.mdx
> [NO-TICKET] Update analytics docs page with recent changes

- packages/docs/content/blog/release-10.1.mdx
- Added a `Release 10.1` blog post
[Demo](https://cmsgov.github.io/design-system/branch/pwolfert/release-10.1-blog-post/blog/release-10.1)
> [WNMGDS-2770] New blog post for 10.1

- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
WNMGDS-2779 (related to #3099)
- Update snapshots for 🚾 
- Add logic supporting inverse labels
> [WNMGDS-2779] Update wc snaps, add component logic to fix wc test

- README.md
- package.json
Updated package script documentation in the README. Some entries were missing, and some were outdated.
> [NO-TICKET] Update package script documentation in the README

- examples/astro/package.json
- examples/preact-app/package.json
- examples/preact-react-app/package.json
- examples/react-app/package.json
- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-cms-gov/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 7/3 Version bump main

- COMPONENT_MATURITY.md
@jack-ryan-nava-pbc's [new broken-link-finding script](https://github.com/CMSgov/design-system/pull/3185#pullrequestreview-2211219976) found these broken links, so I'm fixing them.
[Here's the rendered markdown view of that file](https://github.com/CMSgov/design-system/blob/28405ecf0bdfd5325d504257b602fc61597c9a93/COMPONENT_MATURITY.md)
> [NO-TICKET] Fix broken links in `COMPONENT_MATURITY.md`

- examples/astro/package.json
- examples/preact-app/package.json
- examples/preact-react-app/package.json
- examples/react-app/package.json
- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-cms-gov/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
> [RELEASE] 9/18 Version bump main

- packages/docs/content/blog/release-12.0.mdx
[WNMGDS-2916](https://jira.cms.gov/browse/WNMGDS-2916)
Text is based off of @pwolfert's earlier draft https://github.com/CMSgov/design-system/commit/f3c5fbb5e13374cc9baf19d3b679362ff4ce7d88 before the removal of the privacy settings dialog was identified for the sole contribution to v12 of the design system.
> [WNMGDS-2916] Release v12 Blogpost

- scripts/release.ts
Quick update of the release script
> [no-ticket] Updates release script

- packages/design-system/README.md
- yarn.lock
Update the description of the design system package dist folder to match the current state of the build output.
> [NO-TICKET] Update the description of the design system package dist folder

- packages/docs/content/components/alert.mdx
- packages/docs/src/components/content/SeeStorybookForGuidance.tsx
- packages/docs/static/themes/cmsgov-theme.css
- packages/docs/static/themes/core-theme.css
- packages/docs/static/themes/healthcare-theme.css
- packages/docs/static/themes/medicare-theme.css
- yarn.lock
- [Ticket](https://jira.cms.gov/browse/WNMGDS-3144)
1. View the demo deployment [Link](https://cmsgov.github.io/design-system/branch/jryan/wnmgds-3144-alert-guidance) and check that the content matches the [final review doc](https://confluence.cms.gov/download/attachments/1173982534/New%20Alert%20Guidance_WNMGDS-3020_Final.docx?version=1&modificationDate=1733872883000&api=v2) for each theme. 
2. Note that for the Lightweight option it is not shown for the Medicare child theme
> [WNMGDS-3144] Alert Guidance updates

- packages/docs/content/components/drawer.mdx
- Added additional guidance to the drawer component page
1. Navigate to drawer page and confirm that the copy matches what is in the Jira ticket, and that the sections are ordered according to [our new content outline](https://confluence.cms.gov/pages/viewpage.action?pageId=1127491012).
2. Refer to the Jira ticket for pdf of copy.
> [WNMGDS-3194] Adds new guidance and reordered sections for the drawer/help drawer page

- packages/docs/content/components/third-party-external-link.mdx
Added "Accessibility" and "Accessibility testing" sections to the [third part external link page](https://design.cms.gov/components/third-party-external-link/?theme=core) on the docsite.
1. Navigate to third party link page and confirm that "Accessibility" and "Accessibility testing" sections are added for each theme.
2. Refer to the Jira ticket for pdf of copy.
OR
Check out the attached video!
> [WNMGDS-3246] Added a11y guidance to third part external link page

- packages/docs/content/components/usa-banner.mdx
Adds `Accessibility testing` sections to the USA Banner documentation page. See [jira ticket](https://jira.cms.gov/browse/WNMGDS-3219) for details.
Compare the **Accessibility testing** sections (**Keyboard testing** & **Screen reader testing**) in the [demo branch page](https://cmsgov.github.io/design-system/branch/tamara/WNMGDS-3219/add-usa-banner-a11y-guidance/components/usa-banner/?theme=core#accessibility-testing) to the corresponding sections in the [PDF document](https://docs.google.com/document/d/1QERh2bmyyLA-mfmIwTxP4eBO5Gx4VnuzkQX2sMMQjcA/edit?tab=t.0#heading=h.b3ynznh7u0fb).
> [WNMGDS-3219] Adds a11y testing guidance to USA banner documentation page.

- packages/docs/content/components/text-field/masked-field.mdx
- Adds accessibility guidance for Masked Field. See [jira ticket](https://jira.cms.gov/browse/WNMGDS-3261) for details.
Compare the highlighted new sections under "Accessibility" in the [demo branch](https://cmsgov.github.io/design-system/branch/tamara/WNMGDS-3261/add-a11y-guidance-for-masked-field/components/text-field/masked-field/#accessibility:~:text=Accessibility,accessibility%20tests.) to the corresponding sections in the attached PDF document in this [jira ticket](https://jira.cms.gov/browse/WNMGDS-3261).
> [WNMGDS-3261] Adds accessibility guidance for masked field inputs

- packages/docs/content/components/date-field/date-picker.mdx
- packages/docs/content/components/date-field/multi-input-date-field.mdx
- packages/docs/content/components/date-field/single-input-date-field.mdx
- Overview of changes
- A link to the Jira ticket for quick reference
1. Navigate to single-input-field page and confirm that both links under "Related components" goes to the correct page.
> [WNMGDS-3345] Fixed broken links on single-input-field page

- packages/docs/src/components/content/ComponentThemeOptions.tsx
- packages/docs/src/helpers/urlUtils.ts
- We're checking for window on the server and it's breaking our deployment. Could confirm that we're on production via if (typeof window === 'undefined') but I'm just gonna inline this and save the lines of code.
1. Nightly tests should deploy now
> [NO-TICKET] Fix bad check for window

- packages/docs/src/components/layout/Layout.tsx
Reverts CMSgov/design-system#3591
> Revert "[NO-TICKET] Remove useRef and useEffect from Layout.tsx to correct analytics functioning"
