- packages/core/src/components/Alert/Alert.scss
Updated the styles for the Alert component to match the new [USWDS styles](https://github.com/18F/web-design-standards/pull/2095).
Old:
New:
> Update alert styles to match new USWDS styles

- packages/docs/src/scripts/Docs.jsx
- packages/docs/src/scripts/components/Footer.jsx
- packages/docs/src/scripts/components/GitHubLinks.jsx
- packages/docs/src/styles/components/_Docs.scss
- Added footer to docs site with required links
@shashashasha @allypalanzi @cindyphan Does anyone have a strong preference for either of these? The light blue is what USWDS uses for footers, so that's what I currently have implemented:
> Docs: Add footer

- CONTRIBUTING.md
- package.json
Please follow the format below. Feel free to remove any sections that aren't relevant.
- New package script `lint` with documentation in `CONTRIBUTING.md`
- Changed commands found in `CONTRIBUTING.md` to change `yarn run <SCRIPT>` to `yarn <SCRIPT>`
> Linting documentation update

- package.json
- tools/gulp/common/packageVersions.js
- tools/gulp/index.js
- tools/gulp/sass.js
- yarn.lock
- This fixes an issue where the wrong version number might be included in a package's compiled top-level `index.css` file
> Use each package's version in compiled index.css

- packages/core/src/components/Spinner/Spinner.jsx
Renamed `ariaValueText` prop to `aria-valuetext` to be consistent with default ARIA prop names in React. 
> Note that all aria-* HTML attributes are fully supported in JSX. Whereas most DOM properties and attributes in React are camelCased, these attributes should be lowercased
More info: https://facebook.github.io/react/docs/accessibility.html
> Change ariaValueText to aria-valuetext

- packages/core/src/components/ChoiceList/Choice.scss
Changed the way the Choice input is hidden via its left margin property by using `-999em` instead of negative percent to allow Choice inputs to be side-by-side without unexpected behavior.
> Use negative ems instead of negative percentage on Choice margin

- packages/core/src/components/ChoiceList/Choice.jsx
- packages/core/src/components/ChoiceList/Choice.scss
- packages/core/src/components/ChoiceList/Choice.test.jsx
There is now an option to put the label for a checkbox or radio button on the left side instead of the right.
- `ds-c-choice--left-label` puts the label on the left side of the checkbox/radio button
> RTL Choice components

- package.json
- tools/gulp/stats/getValues.js
- tools/gulp/stats/stats.js
- yarn.lock
- Replaced `nodegit` dependency with a GitHub API library. Now when we gather the stats that are output when `yarn build` is ran, the stats from the `master` branch are pulled directly from the GitHub repo, rather than your local `.git`. This resolves a few things: most notably it allows us to start using Node 8, and it also ensures the stats are accurate.
> Replace nodegit with GitHub API calls

- package.json
- packages/core/package.json
- packages/core/src/components/VerticalNav/VerticalNavItem.test.jsx
- packages/core/yarn.lock
- packages/docs/package.json
- packages/docs/src/scripts/components/PageHeader.jsx
- packages/docs/src/scripts/components/__tests__/Frame.test.js
- packages/docs/src/scripts/helpers/polyfills.js
- packages/docs/src/scripts/index.jsx
- packages/docs/yarn.lock
- tools/gulp/docs/generatePage.js
- tools/jest/polyfills.js
- tools/jest/setupEnzyme.js
- yarn.lock
- Add support for React 16.x to `design-system-core`
- Fixed invalid `heading` tag (should have been `header`) on docs site 🙈 
- Major updates to React and Enzyme, which required updating some tests and changing how we render the docs when server-side rendering is used.
~There are still a few things I'm keeping an eye on before merging this in:~
> Add support for React 16

- packages/core/src/components/Button/Button.scss
- packages/docs/src/scripts/components/GitHubLinks.jsx
- packages/support/src/settings/_variables.forms.scss
Updated the padding on the Button component to `0.5em 1.25em`.
Before:
After:
----
For https://jira.cms.gov/browse/HDSG-151
> Update button spacing to make top/left different from right/left

- packages/docs/src/scripts/components/ReactExample.jsx
Quick fix for weird spacing when there isn't a React example heading or description:
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/371943/32032545-c432980c-b9d5-11e7-88d3-d063e1c0d5dc.png) | ![image](https://user-images.githubusercontent.com/371943/32032526-b27c704c-b9d5-11e7-8db8-64badae67de3.png) |
> Internal: Add margin to React examples

- packages/core/src/components/Tabs/Tabs.scss
- packages/core/src/components/VerticalNav/VerticalNav.scss
🤔 Seems like Chrome introduced a default `4px` `border-radius` on `button` elements. This removes that radius on the tabs and vertical nav items, which may be used on a `button` element.
| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/371943/32031070-026486fc-b9cd-11e7-84aa-9d426035eb06.png) | ![image](https://user-images.githubusercontent.com/371943/32031073-0492cf7e-b9cd-11e7-8fbd-62f001eb3b28.png) |
> Fix:  Remove Chrome's default border-radius

- package.json
- packages/core/src/components/ChoiceList/Choice.scss
- packages/core/src/components/Spinner/Spinner.scss
- packages/core/src/generics/_fonts.scss
- packages/core/src/utilities/flexbox.scss
- packages/docs/src/styles/base/_details.scss
- packages/docs/src/styles/base/_syntax-highlighting.scss
- packages/docs/src/styles/components/_Docs.scss
- packages/docs/src/styles/settings/_typography.scss
- packages/generator-cmsgov/generators/app/templates/index.scss
- packages/stylelint-config-design-system/index.js
- packages/support/src/settings/_override.uswds.scss
- packages/support/src/settings/_variables.color.scss
- packages/support/src/settings/_variables.layout.scss
- packages/support/src/vendor/uswds/core/_variables.scss
- stylelint.config.js
- yarn.lock
When I added prettier, I only ran it on `js` and `jsx` files, but not `scss` files. This does that, and also adds `stylelint-config-prettier` to disable any conflicting Stylelint rules.
> Internal: Run prettier on Sass files

- packages/core/src/components/ChoiceList/Select.jsx
- packages/core/src/components/ChoiceList/Select.scss
- packages/core/src/components/ChoiceList/Select.test.jsx
- Removed `.ds-c-field--select`. This seems unnecessary, and we can look at whether `ds-c-field` is added to a `select` element instead. I can't think of any use cases where it would be added to some other form element. (This is not a breaking change).
- Added padding to the select element so that text doesn't overlap with the icon when the field's width is set to `auto`:
> Remove ds-c-field--select + Fix overlapping select icon

- packages/core/src/components/Alert/Alert.scss
Added a modifier class for the alert component, `.ds-c-alert--hide-icon`, to hide the icon and adjust the left padding.
> Add modifier to hide alert icon

- .travis.yml
- CONTRIBUTING.md
- scripts/prepublish.sh
Rather than merging feature branches into `staging` first, then merging `staging` into `master`, we'll now squash merge directly into `master`. 
Previously, `master` reflected whatever the public release was, and historically this was because we used to use GitHub Pages as our documentation hosting. That's no longer the case, and this change should simplify things, as well as make it easier to consistently use squash merging and keep our history clean.
> Replace references to staging branch with master

- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/TextField/TextField.jsx
- packages/core/src/components/TextField/TextField.test.jsx
- The `TextField` component was not passing through certain DOM properties so I created a fix to let it pass additional DOM attributes to the `input` or `textarea` DOM components.
> fix: Pass-through properties for TextField component

- packages/core/src/components/Dialog/Dialog.scss
- Replaces relative image link with customizable `$image-path` variable.
> Use image-path variable rather than relative link

- packages/core/src/components/StepList/StepList.scss
Fixes a CSS bug wherein a `<Step>`'s the completed text can drop down to the line below its check mark depending on the size of the description and substep content.
- Added `white-space: nowrap;` to `.ds-c-step__completed-text`
Fixed to
> Fix wrapping completed text in <Step> component

- packages/core/src/components/Autocomplete/Autocomplete.example.jsx
- packages/core/src/components/Autocomplete/Autocomplete.jsx
- packages/core/src/components/Autocomplete/Autocomplete.test.jsx
* `onInputValueChange` prop was added to `Autocomplete` for gathering child input value
* documentation for new method
* `listboxId` class attribute
* `aria-controls=this.listboxId` to the `getInputProps` method for building out TextField
* child cloned `onBlur, onChange, onKeyDown` events
* undocumented Autocomplete props can be passed to Downshift
* hard-coded `aria-controls` attribute in examples
> [AUTOCOMPLETE] Hotfix to add onInputValueChange prop to component

- packages/docs/webpack.config.js
- tools/gulp/docs/generateReactExample.js
- Update our UglifyJS configs so that `console.log` is preserved in the React examples since we use these for demo purposes.
- Re-enable mangling on the docs JS now that React examples are compiled using a separate process.
> Docs: Retain console.log in React examples

- packages/core/src/components/ChoiceList/Choice.jsx
- packages/core/src/components/ChoiceList/ChoiceList.jsx
- packages/core/src/components/DateField/DateField.jsx
- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/FormLabel/FormLabel.jsx
- packages/core/src/components/MonthPicker/MonthPicker.jsx
- packages/core/src/components/TextField/TextField.jsx
- packages/docs/src/scripts/components/ReactPropDoc.jsx
- Props which were set to `PropTypes.oneOfType([PropTypes.string, PropTypes.node])` were changed to `PropTypes.node`, since `node` includes `string`.
- Updated the `DateField` `hint` to include slashes, based on feedback from the CMS content team. It's now `For example: 4/25/1986`.
- In the docs, use a verbose description of `PropTypes.node` since it could be confused with "DOM node".
- Some props that were passed through to a child component were stricter than the original PropType. These were loosened in most cases from `string` to `node`.
- Added `number` as a valid PropType to `TextField`'s `defaultValue` and `value`.
> Small PropTypes refactor; Fix inconsistent PropTypes

- packages/core/src/components/DateField/DateField.example.jsx
- packages/core/src/components/DateField/DateField.jsx
- packages/core/src/components/DateField/DateField.test.jsx
- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- `dayInvalid`, `monthInvalid`, `yearInvalid` boolean props added to `DateField` to support error styling on the individual `input` elements
> Add dayInvalid, monthInvalid, yearInvalid props to DateField

- packages/core/src/components/Autocomplete/Autocomplete.example.jsx
- packages/core/src/components/Autocomplete/Autocomplete.jsx
- packages/core/src/components/Autocomplete/Autocomplete.test.jsx
Allows items prop to be optional and doesn't render the list if it doesn't exist and it's not loading. Also added a unit test for the item rendering
- Unit test for `<Autocomplete>` to make sure it renders items
- `<Autocomplete>`'s `items` prop is now optional
> Autocomplete items prop to be optional

- packages/core/src/components/MonthPicker/MonthPicker.jsx
Wrapped the `<Choice />` elements in list items because axe-core said ordered lists must have list items as the immediate child node.
> Wrapping the controlled grid of checkboxes in list items

- packages/core/src/components/Button/Button.jsx
Opens up the `variation` prop on the `<Button>` component so we can have arbitrary variation classes in site packages and themes.
- `variation` prop on `<Button>` now accepts all strings
> Button component allows all strings for variation prop

- CONTRIBUTING.md
- lerna.json
- package.json
- packages/docs/webpack.config.js
- tools/gulp/build.js
- tools/gulp/common/buildPath.js
- tools/gulp/docs/__tests__/generateDocPage.test.js
- tools/gulp/docs/__tests__/generateHtmlExample.test.js
- tools/gulp/docs/generateDocPage.js
- tools/gulp/docs/generateHtmlExample.js
- tools/gulp/docs/generatePage.js
- tools/gulp/docs/generateReactExample.js
- tools/gulp/docs/index.js
- tools/gulp/docs/savePage.js
- tools/gulp/index.js
- tools/gulp/sass/index.js
- tools/gulp/server.js
- Now when you run `yarn start:theme` or `yarn build:theme`, the `docs/` directory is placed into the theme's directory. This is useful for generating documentation for a theme and we'll use this for the HealthCare.gov site package's docs.
> Internal: Add option to build docs/ into theme folder

- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/FormLabel/FormLabel.example.jsx
- packages/core/src/components/FormLabel/FormLabel.jsx
- packages/core/src/components/FormLabel/FormLabel.test.jsx
- packages/core/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
- packages/core/src/components/TextField/TextField.example.jsx
- Removed the need for adding punctuation to `requirementLabel` on the label and field components. This avoids adopters accidentally having a field description that says stuff like _"Optional Enter the ID from your card"_, and should be more future-proof if we ever to decide to place the requirement label elsewhere.
> Change: Dynamically add punctuation after requirementLabel

- packages/core/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
- packages/core/src/components/StepList/StepList.scss
IE11 doesn't automatically fill the entire horizontal space for child elements set to space-between. By adding a `margin-left: auto` to the step actions, the layout issue is resolved. Screenshots attached.
* `.ds-c-step__actions` has had a margin-left: auto added to force full width in all browsers
> [HOTFIX] steplist-flexbox IE11 layout issue

- packages/core/src/components/TextField/TextField.scss
- Use Open Sans on `ds-c-field` inputs, rather than the system font 🙈
> Fix: Use Open Sans in input fields

- package.json
- yarn.lock
* event-source-polyfill was not needed for IE11, so it has been removed
> Removing unneeded shim for webpack-dev-server

- packages/eslint-config-design-system/index.js
- packages/eslint-config-design-system/package.json
- Ignore the `t` prop passed into components via react-i18next
> eslint-config: Ignore i18next HOC t prop

- packages/core/src/utilities/border.scss
- packages/support/src/settings/_variables.color.scss
- New `ds-u-border--dark` utility class to set the border to a dark gray.
- New `$border-color-dark` Sass variable
These are useful for situations where the background isn't white, and you need a darker neutral border color.
> Add ds-u-border--dark utility class

- packages/docs/src/styles/example.scss
- tools/gulp/build.js
- tools/gulp/sass/index.js
- Fixed `postcss-image-inliner` configuration
- Added support for previewing themes which `@import` the design system's files directly within the theme's Sass file. This doesn't introduce duplicate declarations thanks to [cssnano](http://cssnano.co/optimisations/discardduplicates/).
- Added support for compiling a theme's JS files
> Internal: Add support for theme's including design system Sass imports + Theme React files

- packages/support/package.json
- packages/support/yarn.lock
- Locked `uswds` package at `1.3.x`. `1.4` renamed some variables that we depend on, so upgrading will require additional changes on our end in order to not break things.
> Lock uswds package version

- tools/gulp/build.js
- tools/gulp/docs/generatePage.js
- tools/gulp/watch.js
This will create the `dist/` folder for all packages as the first task in the `yarn start` script. This handles a scenario where the `dist/` folder doesn't yet exist but another dependency is relying on a compiled component.
> Internal: Compile JS components in watch task

- packages/docs/src/scripts/components/ReactExample.jsx
- Fixes an issue related to GitHub Pages redirecting paths not ending in a trailing slash to an `http` page, which breaks iframe examples.
> Docs: Add trailing slash to React example iframe paths

- packages/core/src/utilities/color.scss
- packages/support/src/settings/_variables.color.scss
- Change `$color-muted` to reference `$color-gray`, rather than `$color-gray-medium`. This means the muted color becomes darker and can now be combined with a background that is `$color-gray-lightest` while still being accessible. This also brings the color inline with what we've been using in the latest HealthCare.gov design updates.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/371943/35924049-f274fbda-0bef-11e8-8f26-d6d7636013e1.png) | ![image](https://user-images.githubusercontent.com/371943/35923991-c8a82570-0bef-11e8-97cc-d08b163a618a.png) | 
| ![image](https://user-images.githubusercontent.com/371943/35924105-1c574b1a-0bf0-11e8-8bb7-8aa5ddaf2406.png) | ![image](https://user-images.githubusercontent.com/371943/35924124-2bf65732-0bf0-11e8-851b-c …
> Change muted color

- packages/core/src/components/DateField/DateField.jsx
- packages/core/src/components/DateField/DateField.scss
- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- Removed slashes from the date field's example based on guidance from content team. This reverts things back to how they were, and is consistent with the USWDS.
>  Update example text of DateField

- packages/core/src/components/SkipNav/SkipNav.jsx
- packages/core/src/components/SkipNav/SkipNav.test.jsx
For apps that use hash routing, the existing skipNavHref will not work (unless we inject JavaScript in the href, but that's icky). Adds the ability to provide an onClick handler so we can manually set the focus to the main element in those scenarios.
- Added an onClick prop to SkipNav component
https://jira.cms.gov/browse/HDSG-192
> Added an onClick prop to SkipNav component

- packages/layout/src/_col.scss
- tools/gulp/server.js
- Removed `relative` positioning from grid columns so a developer can position a child element relative to an ancestor farther up the chain. For context: We need to do that for the help drawer in App 3. Based on my testing in Chrome, Firefox, and IE 11, this property doesn't seem like it was necessary and may have been an artifact from older browser support we no longer need. 
- Snuck in the ability to pass in a `--port` argument to `yarn start`. This lets me run the design system locally alongside another app running on port `3000`. For example, you can now run `yarn start --port 1337`
> Change: Remove relative positioning from grid columns

- packages/support/src/settings/_variables.forms.scss
Changed the `$input-border-width` variable from 1px to 2px.
Before:
After:
> [HDSG-197] Change default input width from 1px to 2px

- packages/core/src/components/Dialog/Dialog.jsx
- packages/core/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
Give the dialog element the `ds-base` class so it looks like it's supposed to independent of the main site content
- Adds the `ds-base` class to the `Dialog`'s main dialog element
> Style Dialog element with ds-base class

- packages/core/src/components/Dialog/Dialog.jsx
Need to be able to change the size of the close button as well
- `closeButtonSize` prop to `Dialog` component
- Documentation for this prop and `closeButtonVariation` that links back to the button component docs
> Add closeButtonSize to Dialog component

- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/TextField/CurrencyField.example.jsx
- packages/core/src/components/TextField/CurrencyField.scss
- packages/core/src/components/TextField/TextField.example.jsx
- packages/core/src/components/TextField/TextField.jsx
- packages/core/src/components/TextField/TextField.scss
- packages/core/src/components/TextField/TextField.test.jsx
- packages/core/src/components/TextField/__snapshots__/TextField.test.jsx.snap
- packages/core/src/components/_index.scss
- tools/gulp/docs/processKssSection.js
- Added a "Currency field" component. This extends the default text field component and applies additional styling to indicate the expected value (by default: a dollar amount). To use in React, add a `mask="currency"` prop to the `TextField` component.
Note: this only includes styling at the moment, and additional masking/validation functionality may come later.
> Add currency field component/text field mask prop

- packages/core/package.json
- Moved `react` and `react-dom` to `peerDependencies` for our core package so webpack can automatically deduplicate in target applications
> Moved react and react-dom to peerDependencies

- packages/core/src/base/typography.scss
- packages/core/src/components/ChoiceList/Select.scss
- packages/core/src/components/DateField/DateField.jsx
- packages/core/src/components/DateField/DateField.scss
- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/support/src/settings/_override.uswds.scss
- Fixed responsive styling of `ds-h1` so page titles scale down on small screens
- Fixed obnoxious size of dropdown arrow to be consistent with USWDS styling
- Fixed weight of the date fields labels
> Visual bug fixes

- packages/core/src/components/DateField/DateField.jsx
- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/FormLabel/FormLabel.jsx
- packages/core/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
Fulfills HSDG-199 by adding the id and aria-describedby attributes to `<DateField>`.
- Added the id and aria-describedby fields to `<DateField>`
- Added an optional `id` prop to `<FormLabel>`
- 9 snapshots
- I could have avoided changing all these snapshots but figured it was better to change those than add extra code to the component
Tested with VoiceOver
> Aria-describedby attributes for the DateField fields

- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/FormLabel/FormLabel.jsx
- packages/core/src/components/FormLabel/FormLabel.test.jsx
- packages/core/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
Fixed bug in FormLabel where the hint text would render incorrectly if it is a node and there is a `requirementLabel`. Updated snapshots may look like they're wrong, but it renders correctly when it goes into the DOM.
- Added to the FormLabel test to make sure we handle the case when those props are nodes.
- Had to separate out the hint destructuring to a const because of the linter even though it doesn't look as good
- HDSG-203
> [HDSG-203] Fix hint+requirementLabel bug in FormLabel component

- packages/core/src/components/TextField/Mask.jsx
- packages/core/src/components/TextField/TextField.test.jsx
Masked fields weren't being re-rendered when the child `TextField` received new props (like `errorMessage`).
> Fix: Ensure masked field re-render when TextField receives new props

- packages/core/src/components/TextField/Mask.jsx
- packages/core/src/components/TextField/Mask.test.jsx
This is a quick fix for formatting partially-obfuscated SSNs in App3 (but will also format fully obfuscated SSNs). Currently when we try to format a value like `*****1234` by passing it to a `<TextField mask="ssn" ...`, it formats it like `*****123-4`, when we really want `***-**-1234`.
Because these functions and our needs for the component are growing in complexity, I would like to in the near future change the `mask` prop to accept either one of those four strings **or** a masking function so developers can do the masking themselves while retaining the accessibility benefits of the debounced formatting.
- SSNs obfuscated by replacing digits with asterisks still get formatted by the `Mask` component
> HSDG-213: Allow for masked, partially obfuscated SSNs

- README.md
Added contact details to the README for teams outside of WDS who want to contact the product owners directly. This has come up a few times, some people reaching out to me directly since I'm a contributor on the repo. I've confirmed with Melissa that this is the email address we can publish.
> Add email address for point of contact

- package.json
- yarn.lock
The previous version of Webpack's hot module swap runtime was using the `Array.prototype.includes` method, and breaking in IE11. I've bumped the version of Webpack to use at least 4.16.1, with the package.json file for Webpack showing 4.16.3.
The HMR file can be viewed here: https://github.com/webpack/webpack/commit/fcf634c81956b7959f83bc9f140db37cc628e92a#diff-f995afcfa4e47968fef81836a5da0bca
* Webpack from 4.0.1 to 4.16.3
* Fixes a bug where the dev server will not render any output in IE11
* IE11 - Windows 10
* Edge - Windows 10
* Chrome - Windows 10
* Firefox - Windows 10
* Safari - MacOS High Sierra
* Chrome - MacOS High Sierra
* Firefox - MacOS High Sierra
> [feature-webpack-IE11-fix]: Bumping Webpack to fix dev server IE11 error.

- packages/core/src/components/TextField/Mask.jsx
- packages/core/src/components/TextField/Mask.test.jsx
There was an error in app3 that allowed a user to enter a zip code like `1234-5`. While this was a problem with the app3 validation, it was pointed out that the zip code masking could be improved to strip out the `-`, since it appeared to do so if you provided a 9 digit zip with some extra `-`s.
- `TextField/Mask.jsx` -- updated the regex for the zip code masking to allow it to trigger when only a 5 digit zip code is provided. Provided a couple new test cases to cover these scenarios.
Notice that the masking doesn't kick in with just 5 digits, only once we have 9.
Here the masking kicks in and corrects format when only providing 5 digits as well.
> Improve zip code masking

- packages/core/src/components/Review/Review.example.jsx
- packages/core/src/components/Review/Review.jsx
- packages/core/src/components/Review/Review.test.jsx
- packages/core/yarn.lock
Healthcare.gov needs the ability to have 2 buttons in `<Review>`. While this can be achieved through the `editText` prop, this wraps the content with an `<a>`, which breaks tabbing & screenreader experiences. 
This PR adds an optional `editContent` prop to `<Review>` to provide functionality for custom edit links. 
Tests and an example were also added. Happy to change the documentation copy or naming.
Example using new `editContent` prop
> Allow custom edit content in <Review>

- packages/core/dist/components/Tabs/Tabs.js
- packages/core/src/components/Tabs/Tabs.jsx
Changed the isTabPanel function to check for child.props.tab instead of child.attributes.tab. This will still support Preact, but will also account for wrapped TabPanel React components where the type is not TabPanel.
Fixes #271
> Allow Tabs to detect TabPanels in React

- packages/core/src/components/TextField/Mask.jsx
Sawyer pointed out in [#285](https://github.com/CMSgov/design-system/issues/285) that we started using `Array.prototype.includes` in [Mask.jsx](https://github.com/CMSgov/design-system/commit/752e14fd848c2ab26c2550e5f8e1142e7be3c88e#diff-bc403a3448d8591da046ffb97228eab1R102) without a polyfill (required for IE11 support). This happens elsewhere in our app where we include specific `core-js` polyfills (example: [MonthPicker.jsx](https://github.com/CMSgov/design-system/blob/master/packages/core/src/components/MonthPicker/MonthPicker.jsx#L1)).
- Added polyfill for `Array.prototype.includes` in the `Mask.jsx` module for IE11 support
> Fix IE11 support for masked components with Array.prototype.includes polyfill

- packages/core/src/components/Autocomplete/Autocomplete.jsx
- packages/core/src/components/Autocomplete/Autocomplete.scss
Axe.js was reporting two errors, one critical and one serious, about invalid ARIA markup and improper autocomplete attribute values. This PR fixes both of those issues and improves documentation around the focusTrigger prop, based on things I've learned working with Downshift and local state management.
* Improved documentation for `focusTrigger` prop
* `aria-controls` attribute is now added dynamically, to remove an axe.js error
* `autocompleteLabel` default text changed from "nope" to "off". Fixes another axe.js error.
> Fixing two ARIA bugs, adding documentation for Autocomplete.

- packages/core/src/components/index.js
`<HelpDrawerToggle />` wasn't being properly exported - I think this should do it.
> Export HelpDrawerToggle component

- packages/core/src/components/HelpDrawer/HelpDrawer.jsx
The `HelpDrawer` not has a `closeButtonText` prop so developers can customize the text inside the button that hides the drawer. Defaults to "Close".
> Set HelpDrawer close button text via props

- packages/core/src/components/HelpDrawer/HelpDrawerToggle.jsx
I moved the `buttonRef.focus()` for the `HelpDrawerToggle` from `render` to `componentDidUpdate`.
I ran into an issue in tax tools with the button ref focus when it used to be in `render` causing `Cannot update during an existing state transition` warnings because state change in a parent component was causing a re-render. I don't fully understand why this was happening (the parent state change was via an onBlur event related to another ref), but I do think handling the focus in `componentDidUpdate` rather than `render` here makes sense. Please let me know if you see any concerns with this.
> Add ref focus for HelpDrawerToggle to componentDidUpdate

- packages/docs/src/pages/index.md
Per https://jira.cms.gov/projects/WNMGDS/issues/WNMGDS-3, added a blue info alert to the home page of the design system pointing people to a survey we'd like them to take.
> add link to CMS survey per https://jira.cms.gov/browse/WNMGDS-3

- packages/core/src/components/ChoiceList/ChoiceList.jsx
- packages/core/src/components/ChoiceList/Select.jsx
* A new prop - `ariaLabel` - to the `ChoiceList` component. `ChoiceList` will pass the value of this prop as the `aria-label` attribute when it renders a `Select` component. This addition is necessary for 508 compliance in some instances. See https://jira.cms.gov/browse/WNMGAPPIII-201.
> ChoiceList: add `ariaLabel` prop for select component type

- packages/core/src/components/Alert/Alert.scss
Broken link to the measure utility from the alerts component page. 
Before fix link was: https://design.cms.gov/components/alert/%7B%7Broot%7D%7D/utilities/measure
After fix link is: https://design.cms.gov/utilities/measure/
> Fix broken link to the measure utility

- packages/core/src/components/ChoiceList/Choice.example.jsx
- packages/core/src/components/ChoiceList/Choice.jsx
- packages/core/src/components/ChoiceList/ChoiceList.example.jsx
- packages/core/src/components/MonthPicker/MonthPicker.test.jsx
- packages/core/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
- `aria-live="polite" and aria-relevant="additions text" and aria-atomic="false"` to choice when  `checkedChildren` prop is used. 
- Example of `checkedChildren` to `choice` example for both radios and checkboxes 
This is working to fix an issue where the choice element is not to announcing the content in `checkedChildren` when it is revealed.
> Add ARIA roles to child content container

- packages/core/src/components/ChoiceList/Choice.example.jsx
- packages/core/src/components/ChoiceList/Choice.jsx
- packages/core/src/components/ChoiceList/Choice.scss
* Fixed the CSS and class placement
* Verified the inverse theme is working correctly
* Updated docs to call out `checkedChild` handling
* CSS support for the `<Choice />` checked children prop to match the older Healthcare.gov site package expose within pattern
* Documentation for proper use of the expose within pattern
---
> [WNMGDS-6/checked-child-css] Adding CSS support for Choice checked children

- packages/core/src/components/VerticalNav/VerticalNav.example.jsx
- packages/core/src/components/VerticalNav/VerticalNav.scss
Fixes #313 
Added Caret to the vertical navigation and updated the HTML and React versions to be the same.
**I'm not sure how many levels the caret is supposed to be on**
> Fix differences between vertical nav HTML and React versions

- packages/core/src/components/ChoiceList/Choice.example.jsx
- packages/core/src/components/ChoiceList/Choice.scss
* CSS for proper handling of checked children with small inputs
* CSS for checked children with right to left order
* `<Choice />` component examples to support the previous two items
* Documentation for using these examples
* Fixed the choice frame example by setting all children open with `defaultChecked`
I made a few judgment calls on the inputs to the right of labels, with regard to padding and margin. Please advise if these need tweaked. The full-width didn't feel right, so I capped width, and sight-adjusted, dipping back into UI design for a moment.
* Closes https://github.com/CMSgov/design-system/issues/333
* Closes https://github.com/CMSgov/design-system/issues/337
---
> Adding small and right inputs, fixing frame height on Choice.

- packages/docs/src/scripts/components/Header.jsx
This makes it more clear that it is the CMS Design System. 
CMS is already being used in the `<title>` tag.
> Add CMS to the Design System header

- packages/core/src/utilities/display-visibility.scss
- `ds-u-#{$breakpoint}-display--flex` utility classes that were missing from the set of responsive utility classes for `display`-property values
> Added missing "flex" option for responsive display utilities

- packages/core/src/components/Button/Button.scss
- packages/support/src/settings/_variables.forms.scss
- Defined the button component's border width with a variable (`$button-border-width`) so we can easily override it in site packages
> Use variable for button border width

- packages/docs/src/scripts/components/PageHeader.jsx
Fix formatting for when there is only one link in the page header.
Removing the bullet and adding margin does the trick
**Screenshot**
the left is updated and right is the current
> [WNMGDS-50] - Fix formatting of docs page heading links 

- package.json
End to End tests were failing because chromedirver needed to be updated
```
FAIL  packages/core/src/components/Badge/Badge.e2e.test.js
● Test suite failed to run
SessionNotCreatedError: session not created: Chrome version must be between 70 and 73
(Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-101-generic x86_64)
at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:585:15)
at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:533:13)
at Executor.execute (node_modules/selenium-webdriver/lib/http.js:468:26)
```
> Updating chromedriver to 2.46.0

- CONTRIBUTING.md
- README.md
* Made the title of the contributing page more clear 
* Updated links still going to the wiki to go to guides pages
* Fixed broken link to the code of conduct page
> Update links in GitHub

- packages/core/src/components/Autocomplete/Autocomplete.scss
This was missed in the previous update to remove maturity badges until we got the audit completed.
> Remove beta status from autocomplete

- packages/core/src/utilities/index.scss
- packages/core/src/utilities/measure/measure.example.html
- packages/core/src/utilities/measure/measure.scss
- packages/support/src/settings/_variables.type.scss
List new features or components. Include a screenshot for new visual elements.
- Changed the variables for `base`, `narrow` and `wide` from `em` values to `ex`. `Ex` is a better path than `ch` which was what was originally proposed. 
- https://www.w3schools.com/cssref/css_units.asp
- https://v2.designsystem.digital.gov/design-tokens/typesetting/measure/
- Updated the measure utility to have a separate HTML example and it's own folder (similar to components) There could be some follow on work to placing utilities inside folders to follow a consistent approach. 
- Showing each example `base`, `narrow` and `wide` in its own code snippet instead of combined. This follows the convention of the components which I think is stronger than grouping everything into one code snippet box. This also …
> [WNMGDS-81] Updating measure variables to use ex instead of em.

- packages/core/src/components/Button/Button.scss
- Solid-colored buttons now have transparent borders (which fills the space with the background color) rather than having a border width of 0, which makes those buttons smaller than the default buttons.
> Give solid buttons transparent borders rather than no borders

- guides/RELEASE-PROCESS.md
Add additional clarifications and updates to the release process 🚀 
- Added `git pull` and `git status` to the steps 
- Moved `yarn test` up to release commit section. It was previously run too late in the order of operations.
- Changed the add process to use `--all` instead of `-a` to capture new files in addition to modifications.
- Simplified the doc site CBJ section a bit as well
> Update release documentation

- packages/docs/src/scripts/components/Footer.jsx
- Privacy policy link to footer
- Privacy settings link to footer 
- Contact link to screendoor form to the footer 
**_I'm unsure if the privacy settings link works because we don't have an imp or dev environment to test on._**
> [WNMGDS-157] [WNMGDS-53] - Add privacy and contact links to footer

- CONTRIBUTING.md
Most folks don't have write access to the design system and would need to create a fork in order to submit a PR.
> Adding info about creating a fork to contributing doc 

- packages/docs/src/pages/startup/examples.md
Added descriptions for the various examples that we have in the GitHub repo to help people find them easier. 
I'm not sure how helpful the form and article examples are and am thinking that the responsive examples could be explained in the context of the https://design.cms.gov/utilities/display-visibility/ page
> Add info about examples

- packages/core/src/components/Button/Button.jsx
I wanted to focus a `<Button>` in https://jira.cms.gov/browse/MEA-846 but realized we didn't expose the ref callback in the design system.
- Allow components using `<Button>` to grab a reference to the underlying DOM element using a new prop called `buttonRef`.
> [MEA-846] Enable manual focusing of Button components.

- packages/core/src/components/Autocomplete/Autocomplete.example.jsx
- packages/core/src/components/Autocomplete/Autocomplete.jsx
- packages/core/src/components/Autocomplete/WrapperDiv.jsx
- packages/core/src/components/__tests__/index.test.js
- Fixed a bug where if the `Autocomplete` component were to be rendered in any kind of stateful tree (stateful parent or ancestor) and that state were to change (even if it didn't directly relate to one of the Autocomplete's props), the component would not be able to maintain its browser focus and would start to behave erratically.
- The root cause of this was the `MyDiv` that functional component that was being defined inside the render function. It was not able to persist the instance of `MyDiv` between renders because the component function itself could not persist between renders. Moving it out of the render function fixed it.
- I wanted to define it at the top of the `Autocomplete.jsx` module, but that generated too many eslint errors that I was not able to suppress with a reasonable …
> [WNMGWINSHOP-196] Fix broken autocomplete in stateful tree

- packages/core/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/core/src/components/FormLabel/FormLabel.jsx
- packages/core/src/components/FormLabel/FormLabel.scss
- packages/core/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
Previously, examples of `inversed` in other components simply use `ds-base--inverse` on the container div to correctly style the inversed components. However, a user should be able to inverse a component using just the provided `inversed` prop, and also the error message was never styled correctly in either case. 
The `inversed` prop now styles the label and error message of a `FormLabel` and no longer relies on the  container's styling
Go to a component like `TextField` or `Select` and add an `inversed` prop to the react example. If you darken the background you should see something like this:
Notice the label is white, the requirement label is lighter, and the error message is lighter.
> [WNMGDS-210] Fix Inversed FormLabel

- packages/core/src/components/Autocomplete/Autocomplete.jsx
- packages/core/src/components/Autocomplete/Autocomplete.test.jsx
- packages/core/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
Fixed
As put forth in the [new 2.1 criteria](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name.html), the aria label must match or start with the same text as the visual text. Given this, I edited the aria so that the:
beginning of the aria label of the autocomplete component is the same as the visual label.
> [MCT1802] - Update aria text on autocomplete to match visual

- packages/core/package.json
- packages/core/yarn.lock
- Upgrade the version of Downshift we use from `3.0.0` to `3.2.10` to get various bugfixes, including IE bugfixes
https://github.com/downshift-js/downshift/releases
> [WNMGWINSHOP-196] Upgrade Downshift from 3.0.0 to 3.2.10

- packages/core/src/components/StepList/Step.jsx
- packages/core/src/components/StepList/Step.test.jsx
- packages/core/src/components/StepList/StepList.jsx
- packages/core/src/components/StepList/StepList.scss
- packages/core/src/components/StepList/SubStep.jsx
- `StepList` steps now support a `linkText` property which allows for alternative text for that step's start/continue/edit links.
- Added the `steps` property to the documentation of `step` objects, which was previously missing
To see it in action, change the `StepList` example by adding the `linkText` property to one of the steps, like
```js
{
id: 'household.overall',
title: 'Overall household',
href: '#step-2a',
started: true,
completed: true,
linkText: 'Hello'
},
```
after [this line](https://github.com/CMSgov/design-system/blob/master/packages/core/src/components/StepList/StepList.example.jsx#L34) or [this line](https://github.com/CMSgov/design-system/blob/master/packages/core/src/components/StepList/StepList.example.jsx#L27)
> [WNMGWINSHOP-226] Can have alternative linkText for steps in StepList

- .travis.yml
- package.json
- tools/jest/e2e.config.js
- yarn.lock
This is a hack to get our tests to pass right now. It matches our chromedriver version to the arbitrary version that is sitting on Travis CI servers. This is not a good long-term solution but is necessary right now because using the latest stable version of Chrome does not work with the latest chromedriver. 
[The Travis CI addon for Chrome only allows either the latest stable or beta version of chrome to be downloaded](https://docs.travis-ci.com/user/chrome). [According to these logs](https://api.travis-ci.org/v3/job/565743388/log.txt), the version of chrome that is being downloaded at the moment by the `google-chrome-stable` addon is `76.0.3809.87-1`. This should be supported by the latest stable version of `chromedriver` ([76.0.3809.68](https://chromedriver.storage.googleapis.com/76.0.38 …
> Fix CI tests by updating chromedriver

- package.json
pre-commit hook to the package.json file
Showing the pre-commit finding an SCSS issue
> [WNMGDS-226] - Add SCSS to pre-commit hook

- packages/core/dist/components/Dropdown/Dropdown.js
- packages/core/src/components/Dropdown/Dropdown.jsx
- packages/core/src/components/Dropdown/__snapshots__/Dropdown.test.jsx.snap
This should be a pretty straightforward change, but let me know if I did something wrong!
Fixed an issue where the `<option/>` tags under the `<select/>` generated by `<Dropdown/>` did not have `value` attributes.  This caused the function provided to `onChange` to be unable to grab the option's value via `event.target.value` (since it would return the option's label instead).
> [NO-TICKET] Fix issue in <Dropdown/> where <option/>s do not have `value` attributes.

- packages/core/src/components/Button/Button.scss
- Made the default button have background fill (with inverse fill for inverse buttons). This maintains proper contrast levels when default buttons are on various backgrounds.
> [WNMGDS-244][WNMGWINSHOP-277] Fill for default buttons

- packages/core/src/components/DateField/DateField.scss
- packages/core/src/components/Tabs/_Tabs.docs.scss
- packages/core/src/components/_index.scss
With backstop I discovered 2 regressions introduced by the separating out inline CSS/HTML work. This PR fixes them before the release
1. Date field css is changed
https://gyazo.com/ca29a5ed8363562539f9d5dd4f3b3609
2. Documentation for <Tab> is no longer there https://gyazo.com/56a87571e1af402778258009bcd893d7
> Fix visual regressions

- packages/core/src/components/Alert/Alert.example.jsx
- packages/core/src/components/Alert/Alert.jsx
`children` is no longer a required prop in <Alert>, and an error is added for empty Alerts.
Added missing React prop documentation and some extra React examples
Previously empty headers would still cause a small margin to be added, this was fixed so a header would only be included in the HTML if its not empty
> [WNMGDS-269] Make children not required in <Alert>

- packages/core/src/components/Alert/Alert.example.jsx
Added `<p>` tags with the class of `ds-c-alert__text` to the React Alert examples to bring them in line with the HTML alert examples and make them all consistent
> [WNMGDS-177] Add P tag to React alert component 

- packages/docs/src/scripts/components/PageHeader.jsx
View source link in page header because only React components need a view source
> [WNMGDS-268] Remove source link in page headers

- guides/RELEASE-PROCESS.md
- scripts/publish.sh
Remove **cmsgov** user check from publish script. 
That user account is no longer usable and you must have an individual NPM account and get access to the **cmsgov** NPM org
> [WNMGDS-261] - Update NPM publish script

- packages/core/src/components/Dropdown/Dropdown.jsx
*** Summary
While moving all KSS comments to the correct .doc.scss file, I forgot to delete 1 comment in Dropdown, resulting in 2 description. This PR removes it.
> Remove duplicate dropdown text

- packages/core/src/components/Button/Button.scss
- packages/core/src/components/Button/_Button.docs.scss
- packages/core/src/components/Button/button.example.html
Currently, the disabled button styling is the same for all non-inverse button styles. We should change the default disabled to match the default outline style, similar to USWDS
> [WNMGDS-290] - Update disabled styling for buttons

- packages/core/src/components/DateField/DateField.jsx
Added a check for invalid refs in DateField blur.
Unsure how to reprod the original issue
> [WNMGDS-297] Prevent accessing null refs on DateField

- packages/core/src/components/Review/Review.example.jsx
- packages/core/src/components/Review/Review.jsx
- packages/core/src/components/Review/ReviewLink.jsx
<ReviewLink> takes an `ariaLabel` prop to add extra info for screenreaders, but <Review> did not use this prop.
This PR adds `editAriaLabel` to <Review>, and passes that along to <ReviewLink>
> [WNMGDS-282] Add editAriaLabel to Review

- packages/core/src/components/Autocomplete/_Autocomplete.docs.scss
This should be pretty straightforward; while working on [CMS-WDS/flh-consumer#249](https://github.cms.gov/CMS-WDS/flh-consumer/pull/249) I was running into issues with setting an initial value for the `<Autocomplete>` component as well as keeping the input from clearing "on blur" while using the existing props in the documentation. Once I did a bit of digging, I realized I could pass props specific to the `<Downshift>` component via the `<Autocomplete>` component, so I just wanted to add a note about that in case it's useful to others in the future.
* a brief note about providing `<Downshift>` props to the `<Autocomplete>` component
* a reference to the version of `<Downshift>` being used since it would be difficult to keep this updated
> [FLH-108] Add a note about using <Downshift> props on the <Autocomplete> component.

- packages/core/src/components/Badge/Badge.example.jsx
- packages/core/src/components/Button/Button.example.jsx
- packages/core/src/components/Button/Button.jsx
- packages/core/src/components/Button/Button.scss
- packages/core/src/components/Button/Button.test.jsx
- CSS that makes `.ds-u-button--transparent.ds-u-button--inverse` equivalent to `.ds-u-button--transparent-inverse`.
- Fixed `<Button>` to use the new styles and fully apply relevant classes
- Expanded `<Button>` react examples to showcase different props.
- Updated `<Button>` tests
1. Modify `Button.test.jsx` to use all different permutations of `disabled`, `inverse`, `variation` to ensure all styles are being used correctly.
> [WNMGDS-326] Fix react button styling

- packages/docs/src/pages/index.md
Removed survey alert from the homepage of the design system site
> [WNMGDS-322] - Remove survey alert from homepage

- guides/RELEASE-PROCESS.md
- packages/docs/src/pages/index.md
- packages/docs/src/pages/startup/installation.md
- packages/docs/src/scripts/components/GitHubLinks.jsx
The "download code and design files" button no longer uses the default source code zip file, it uses the following URL:
```
https://github.com/CMSgov/design-system/releases/download/3.4.2/design-system-v3.4.2.zip
```
From now on, each release should have a zip uploaded with build files named in the following format:
`design-system-v${pkg.version}.zip`
> [NO TICKET] Update github link to use uploaded zip

- packages/core/src/components/ChoiceList/ChoiceList.jsx
Used `size` prop in `ChoiceList`, removed ability to pass in a 'medium' size value which only applied to  `Select`, which is currently deprecated and discouraged from use anyway
> [WNMGDS-89] Use size prop

- packages/core/src/base/body.scss
- packages/core/src/base/typography/link.scss
- packages/core/src/components/Button/Button.jsx
- packages/core/src/components/Button/Button.scss
- packages/core/src/components/Button/Button.test.jsx
- packages/core/src/components/Button/button.example.html
- packages/docs/src/scripts/components/GitHubLinks.jsx
- Allow the usage of `ds-u-button--inverse` with primary/success/danger variations
- Fix border color not styled correctly for inverse buttons
- Fix disabled styling for buttons using the `href` prop
- Use updated buttons on doc site GithubLinks
- Fix doc site GithubLink styling
> [WNMGDS-341] Misc Button fixes

- packages/core/src/base/typography/link.scss
- packages/core/src/components/Button/Button.test.jsx
- packages/core/src/components/Button/__snapshots__/Button.test.jsx.snap
Previously a button with `inverse`, `disabled`, and an `href` prop would be styled incorrectly (color: white). Now it should look the same as a normal inverse disabled button. 
To test, add this code to `button.example.html` to test:
```
<a href="https://www.google.com" class="ds-c-button ds-c-button--inverse ds-c-button--disabled">
Disabled
</a>
```
> [NO-TICKET] Fix inverse disabled link button styling

- packages/core/src/utilities/background-color/background-color.example.html
Noticed that when running locally I was getting an error on the background-color.example.html file.
Prettier was formatting the var block in a way that wasn't allowing it to render 
it was doing this, which was causing issues 
```
<% Object.keys(groups).forEach(fill
=> { -%>
```
> No ticket/background color utility page fix

- packages/core/src/components/Alert/Alert.jsx
- packages/core/src/components/Button/Button.jsx
- packages/core/src/components/ChoiceList/Choice.jsx
- packages/core/src/components/ChoiceList/Select.jsx
- packages/core/src/components/TextField/TextField.jsx
- Removes console.error in favor of warn
- Scopes logs to development and test envs only
> [WNMGDS-346] Use console warn and remove logs from production

- tools/gulp/watch.js
Some changes needed to be made to the watch file after upgrading to Gulp 4 to get watch working again.
> get gulp watch working

- package.json
- yarn.lock
postcss-image-inliner was tied to other dependencies and I think this should eliminate some additional GitHub security issues. 
**91 vulnerabilities found - Packages audited: 46858**
**Severity: 72 Low | 14 Moderate | 5 High**
**70 vulnerabilities found - Packages audited: 47751
Severity: 69 Low | 1 Moderate**
> [WNMGDS-365] - Update postcss-image-inliner

- packages/docs/src/scripts/components/UsaBanner.jsx
I noticed when looking at the Medicare and Healthcare design system doc sites that the USA flag in the top banner is broken due to an incorrect reference.
This PR is to fix the broken USA flag in the USA banner for both medicare and healthcare doc sites 
https://github.cms.gov/pages/MedicareGov/ds-site-package/
https://github.cms.gov/pages/CMS-WDS/ds-healthcare-gov/
The path to the USA flag is currently
https://github.cms.gov/public/images/us_flag_small.png (which 404s)
and after the update, the path works as expected. 
https://github.cms.gov/pages/CMS-WDS/ds-healthcare-gov/public/images/us_flag_small.png
> [NO-TICKET] doc site update to usa flag path for header

- package.json
- tools/gulp/stats/__tests__/getValues.test.js
- tools/gulp/stats/getValues.js
- tools/gulp/stats/stats.js
- yarn.lock
Ever since we removed the `dist` folder from Github, our `stats` task is unable to compare the css using the Github repo, so it has not been working properly. This PR updates the task to compare with the latest `@cmsgov/design-system-core` release in `node-modules`. It also simplifies the task to only support running stats on the entire css bundle, and not on a specific file. I removed this feature because I figured it's better to make the gulp task simpler and easier to maintain than to support a use case we current aren't even using.
One downside is that `@cmsgov/design-system-core@latest` is a new dev dependency, and we will need to do a `yarn install` after each release for accurate stats (I believe we do this anyway during releases)
- Install gulp globally if you have not already
- …
> Fix gulp stats task

- packages/core/src/components/Alert/Alert.jsx
- packages/core/src/components/Dialog/Dialog.example.jsx
- packages/core/src/components/Dialog/Dialog.jsx
- packages/core/src/components/Dialog/Dialog.test.jsx
- packages/core/src/components/Dialog/ThirdPartyLink.example.jsx
- packages/core/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
- packages/core/src/components/Dialog/dialog-size.example.html
- packages/core/src/components/Dialog/dialog.example.html
- packages/core/src/components/HelpDrawer/HelpDrawer.example.jsx
- packages/core/src/components/HelpDrawer/HelpDrawer.jsx
- packages/core/src/components/HelpDrawer/help-drawer.example.html
- packages/core/src/components/Review/Review.jsx
- packages/core/src/components/StepList/Step.jsx
- packages/core/src/components/StepList/Step.test.jsx
- packages/core/src/components/StepList/StepList.example.jsx
- packages/core/src/components/StepList/StepList.jsx
- packages/core/src/components/StepList/StepList.scss
- packages/core/src/components/StepList/SubStep.jsx
- packages/core/src/components/StepList/SubStep.test.jsx
- packages/core/src/components/StepList/_StepList.docs.scss
- packages/core/src/components/StepList/steplist.example.html
- packages/docs/src/scripts/example.js
This PR makes `heading` and `headingLevel` props more consistent across the design system. Prior to this PR, only some components used `headingLevel`, and some components used the prop name `title` instead of `heading`. 
- `headingLevel` prop to `HelpDrawer`, `StepList`, `Alert`, `Review`, 
- Renamed `title` prop to `heading` in `StepList`, `HelpDrawer`, `Dialog`
- Added deprecation console warnings and updated documentation
> [WNMGDS-384] Allow custom heading level

- packages/core/src/components/Autocomplete/Autocomplete.jsx
- packages/core/src/components/MonthPicker/MonthPicker.jsx
- packages/core/src/components/Tabs/Tabs.jsx
- packages/core/src/components/TextField/Mask.jsx
Our babel uses `corejs@3`, so this PR removes a few unnecessary imports
> [NO-TICKET] Remove unnecessary core js imports

- packages/design-system/src/styles/icons/interaction-icons.example.html
- packages/design-system/src/styles/icons/status-icons.example.html
- packages/design-system/src/styles/icons/supplemental-icons.example.html
* Add download attribute to specify that the icon will be downloaded when user clicks on the Download SVG link
* Style Icons page - Ensure the style icon is downloaded when the user clicks on the Download SVG link
> [WNMGDS-427] Update Download SVG links for Style Icons

- packages/design-system/src/components/Autocomplete/Autocomplete.example.jsx
- packages/design-system/src/components/Autocomplete/_Autocomplete.docs.scss
- Remove `focusTrigger` prop for basic example. This isn't needed for this example.
- Update docs in Autocomplete for better guidance around `focusTrigger`
See: #667
> Remove `focusTrigger` prop from basic Autocomplete example

- packages/design-system-docs/src/pages/components/DateField/DateField.example.jsx
- packages/design-system/src/scripts/components/DateField/DateField.jsx
Add autoComplete prop to Date field component to enable autofill of birthday day, month and year.
- New `autoComplete` prop to set the `autocomplete` attribute on the date fields to `bday-day`, `bday-month` and `bday-year`.
Go to Components "Date field" page and check React props table for `autoComplete` prop
[https://github.com/CMSgov/design-system/issues/565]
[https://design-system.service.gov.uk/components/date-input/]
> [WNMGDS-350] Add autoComplete prop to Date field component

- packages/design-system-docs/src/pages/components/TextField/Mask.example.jsx
- packages/design-system/src/components/TextField/Mask.jsx
- packages/design-system/src/components/TextField/__snapshots__/Mask.test.jsx.snap
- Changed the regex for the currency mark pattern to be `^[0-9,]+(.[0-9]{1,2})?$`
- Removed pattern attribute from examples as it is defined and added from the Mask.jsx 
- This fixes #702 
**How to test**
- Test the regex here - you can test here https://regex101.com/r/TEwmdB/1
- Run the site locally and open up firefox and navigate to the masked field page
- Enter numbers in the currency field and ensure that no browser error is triggered
> [WNMGDS-483] Fix currency mask for Firefox

- packages/design-system/src/components/VerticalNav/VerticalNav.jsx
This PR fixed the VerticalNav warning message shown on developer console. 
I was not able to reproduce the other issues with failed tests on running `yarn test` and `yarn test:e2e`.
- Changed items PropTypes to check for object type instead of `shape` of object type
- Run the design system site locally and check the developer console to ensure that no warning message is displayed for VerticalNav
> [WNMGDS-444] Fix dev console warning msg for VerticalNav

- packages/design-system-docs/src/pages/components/Dropdown/Dropdown.example.jsx
- packages/design-system/src/components/Dropdown/Dropdown.jsx
- packages/design-system/src/components/Dropdown/Dropdown.test.jsx
- Add red border to dropdown with error message
- Add example of dropdown with error message
- Run the design system site locally and check that dropdown with error message is displayed with red border
> [WNMGDS-459] Add red border to Dropdown with error message

- packages/design-system-docs/src/pages/components/StepList/StepList.example.jsx
- packages/design-system/src/components/StepList/Step.jsx
- packages/design-system/src/components/StepList/StepList.jsx
- Removed `aria-label` attribute for list items with no label text
- Add the below lines of code to StepList.example.jsx file, just below line 18 `<StepList` 
```
descriptionLabelText=""
substepsLabelText=""
actionsLabelText=""
```
- Run the design system site locally and inspect the html elements to ensure that aria-label is not shown for the step's description, step's actions and step's substeps.
> [WNMGDS-456] Remove aria-labels from StepList list items

- packages/design-system-docs/src/pages/utilities/display-visibility/_display-visibility.docs.scss
- packages/design-system-docs/src/pages/utilities/display-visibility/display.example.html
- packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx
- packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawerToggle.test.jsx.snap
- packages/design-system/src/styles/utilities/_display-visibility.scss
- Change to use inline style when `inline` prop is set for `<HelpDrawerToggle>` component
- Update HelpDrawer.example.jsx to replace this section `<HelpDrawerToggle ... </HelpDrawerToggle>` with below code
`        <p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua. <span> </span>
<HelpDrawerToggle
inline
helpDrawerOpen={this.state.showHelp}
showDrawer={() => this.handleDrawerOpen()}
>
Toggle the help drawer Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua
</HelpDrawerToggle>
.
</p>`
- Run the design system site locally and check that the drawer text link stays on the same line as the paragraph.
- Fixes #689
> [WNMGDS-457] Change HelpDrawerToggle to use inline instead of inline-block

- package.json
- packages/design-system-scripts/cli.js
- packages/design-system-scripts/gulp/build.js
- packages/design-system-scripts/gulp/docs/webpack/createReactExampleWebpackConfig.js
- packages/design-system-scripts/package.json
- tsconfig.json
- yarn.lock
- This PR adds the ability to generate ts definition files when using the `--typescript` option
- Test the build scripts with and without the `--typescript` option, and check if `types` is being outputted in the `dist` folder
- Test that the definition files are updated when running `yarn start`
- Test everything works with mgov child ds
[mgov 2.zip](https://github.com/CMSgov/design-system/files/4887014/mgov.2.zip)
> [WNMGDS-534] Generate ts definition files

- packages/design-system-docs/src/scripts/components/GitHubLinks.jsx
- packages/design-system-scripts/gulp/docs/assets.js
- packages/design-system-scripts/gulp/docs/docs.js
- packages/design-system-scripts/package.json
- yarn.lock
- Instead of linking to our Github release for the "Download code and design files" button, we generate a zip for the doc site to link to.
- Added new gulp task to generate the release via "npm pack", and then move that zip to the doc dist folder
- Run the scripts on the core and child ds
- Ensure the Download code and design files button is working
- Ensure the download zip has all the necessary files
> [WNMGDS-537] Update "Download code and design files" button

- packages/design-system-docs/src/pages/guidelines/accessibility.md
- packages/design-system-docs/src/pages/guidelines/i18n.md
- packages/design-system-docs/src/pages/startup/browser-support.md
- packages/design-system-docs/src/pages/startup/components.md
- packages/design-system-docs/src/pages/startup/examples.md
- packages/design-system-docs/src/pages/startup/fonts-and-images.md
- packages/design-system-docs/src/pages/startup/installation.md
- packages/design-system-docs/src/pages/startup/sass-and-css.md
- packages/design-system-docs/src/pages/startup/theming.md
- packages/design-system-docs/src/scripts/components/Header.jsx
- packages/design-system-scripts/cli.js
- packages/design-system-scripts/gulp/common/__tests__/replaceTemplateTags.test.js
- packages/design-system-scripts/gulp/common/replaceTemplateTags.js
- packages/design-system-scripts/gulp/docs/__tests__/processKssSection.test.js
- packages/design-system-scripts/gulp/docs/__tests__/processMarkdownPage.test.js
- packages/design-system-scripts/gulp/docs/__tests__/processMarkup.test.js
- packages/design-system-scripts/gulp/docs/extractReactData/parseReactFile.js
- packages/design-system-scripts/gulp/docs/extractReactData/reactDocgenHandler.js
- packages/design-system-scripts/gulp/docs/generatePages/convertMarkdownPages.js
- packages/design-system-scripts/gulp/docs/generatePages/generateDocPage.js
- packages/design-system-scripts/gulp/docs/generatePages/generatePages.js
- packages/design-system-scripts/gulp/docs/generatePages/processKssSection.js
- packages/design-system-scripts/gulp/docs/generatePages/processMarkdownPage.js
- packages/design-system-scripts/gulp/docs/generatePages/processMarkup.js
- packages/design-system-scripts/gulp/docs/webpack/createWebpackConfig.js
- Added `npmPackage` option
- Added support for `{{npm}}`, `{{github}}`, and `{{name}}` templates
- Run the doc site and ensure all the content using the new templates is correct
- Try changing various template values to see the doc site update
> [WNMGDS-536] Add more doc content templates

- packages/design-system/src/components/Alert/Alert.jsx
Update ARIA role prop to accept `status` type. This `status` type was requested for displaying scrollable notice on TableCaption Component.
> [NO-TICKET] Update ARIA role prop to include `status`

- packages/design-system-scripts/gulp/docs/generatePages/generatePages.js
CBJ isnt able to finish generating doc site because of the babel/register not working. This PR updates the regex to include CBJ's directory
CBJ error
Notice the directory is `s3/packages/design-system-docs` rather than `design-system/packages/`
- Ensure doc site generates in core and child ds
> Test babel register

- packages/design-system-docs/src/example.scss
- packages/design-system-docs/src/index.scss
- packages/design-system-docs/src/pages/startup/sass-and-css.md
- packages/design-system/src/styles/settings/variables/_build.scss
- Update the default font and image path to `../fonts` rather than `./fonts`
- Ensure the core builds
- Ensure both child design systems build
> [NO_TICKET] Update default font image path

- packages/design-system/src/components/Dialog/Dialog.jsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.jsx
Updated the HelpDrawer and Dialog component warnings to reference the propper component and not the `<button>`
> [WNMGDS-579] Fix console warnings for HelpDrawer and Dialog

- packages/design-system-docs/src/pages/components/MonthPicker/MonthPicker.example.jsx
- packages/design-system/src/components/index.js
- Export `getMonthNames` function from `MonthPicker` module, which one of our products relied on
1. Check out 4b38710 locally, which has some temporary debugging code in it
2. `yarn install && yarn start`
3. Go to the `MonthPicker` page of the docs site
4. Open up the developer console and see the debug output from that commit
> [WNMGTAXTOOLS-73] Export getMonthNames function from MonthPicker module

- packages/design-system-docs/src/pages/components/DateField/DateField.example.jsx
- packages/design-system/src/components/DateField/DateField.jsx
- packages/design-system/src/components/DateField/DateField.test.jsx
- packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- Added `disabled` prop to disable the entire `DateField` component.
- Added test for `disabled` `DateField`
- Updated React example name to be more explicit 
1. Run the doc site locally and navigate to the Date field page
1. Update the React `DateField` example by adding the `disabled` prop 
1. See that the day, month, and year fields are disabled
> [WNMGDS-527] Add disabled prop to DateField

- packages/design-system-scripts/gulp/docs/extractReactData/parseReactFile.js
- packages/design-system-scripts/gulp/docs/extractReactData/reactDocgenHandler.js
- Refactor `reactDocgenHandler` to export and use `processDocgenTemplates()`
- Use `processDocgenTemplates` in `parseReactFile` to ensure typescript prop documentation can use markdown
- Setup Mgov child ds to use the local branch for CMSDS scripts
- Add prop documentation to a `tsx` file that uses markdown
- Run the doc site and ensure the correct HTML is generated in the prop documentation table
> [WNMGDS-543] Allow markdown in typescript documentation

- packages/design-system/src/styles/components/_Choice.scss
Disabled checkboxes and radio buttons now have consistent border styling for default and inverse variations.
1. run the doc site locally 
1. Go to the choice page and see that the default and inverse disabled choice options have the same border treatment.
1. compare that to the live choice page https://design.cms.gov/components/choice/ where the default disabled choice has a much thinner border.
> [WNMGDS-616] Fix disabled choice style bug

- packages/design-system/src/types/ChoiceList/ChoiceList.d.ts
For the ChoiceList `choices` prop, omit the props that we override with values from ChoiceList. Without this fix, ChoiceList choice objects would all require a `name` and `type`. I'm omitting all of the props here that are overridden by https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/components/ChoiceList/ChoiceList.jsx#L34-L43 because they don't get passed down to the Choice component.
I'm putting this PR up so we have something to talk about, but maybe part of it should be some kind of internal tests to protect against these kinds of regressions.
- TypeScript: Fix ChoiceList props' type definition requiring that members of `choices` array have `name` and `type` defined. These come from the parent `ChoiceList` component.
> Omit props for choices that we override with values from ChoiceList

- packages/design-system-scripts/gulp/build.js
- packages/design-system/src/types/ChoiceList/ChoiceList.d.ts
- Build Child Design system with this branch, ensure only new folders (i.e. `types`, `locales`) are copied over to dist
> [NO_TICKET] Prevent copying setupJs and "styles" build folder

- packages/design-system/src/styles/components/_Choice.scss
- Changed background color for inverse choice items to be transparent instead of dark blue 
- Run the doc site locally
- Go to the choice page and change the inerse background color to another color
- See that the inverse choice items are set to transparent and not dark blue
> [WNMGDS-615] Set inverse choice bg to transparent

- packages/design-system-docs/src/pages/components/SkipNav/SkipNav.example.jsx
- packages/design-system-docs/src/pages/components/SkipNav/_SkipNav.docs.scss
- packages/design-system-docs/src/pages/components/SkipNav/skipnav.example.html
- Adds more detailed docs for skip links.
- Changes `tabindex` in example to `-1` so that the main container isn't in the flow for keyboard accessibility, but still focusable programmatically.
> [WNMGDS-565] - Update skip nav docs and examples

- examples/create-react-app/src/components/App.test.js
- lerna.json
- package.json
- packages/design-system-docs/src/pages/components/Badge/Badge.example.jsx
- packages/design-system-docs/src/pages/components/Button/Button.example.jsx
- packages/design-system-docs/src/scripts/components/ReactExample.jsx
- packages/design-system-scripts/cli.js
- packages/design-system-scripts/gulp/docs/generatePages/markdownRenderer.js
- packages/design-system-scripts/gulp/docs/generatePages/savePage.js
- packages/design-system-scripts/gulp/lint.js
- packages/design-system/src/types/ChoiceList/ChoiceList.d.ts
- This PR ensures that eslint is run and reported for all files in the provided directory. Previously only some errors would show.
- It also fixes the logging to accurately display how many JS files were linted
- It runs eslint and fixes many linter errors
- Run `yarn lint` on different directories
- Create linter errors to see if they are reported
- Use the `--fix` flag to see if automatically fixable linter errors are fixed
- Ensure the documentation around the CMSDS scripts are updated
> [WNMGDS-524] Fix eslint logging and run linter

- .travis.yml
- package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/design-system/src/components/Tooltip/Tooltip.jsx
- yarn.lock
- Downgrade `react-transition-group` to `^2.0.0` to avoid the requirement of React 16.6 (they use `React.createContext`)
- Add `core-js` as a dep to the scripts package
- Test the tooltips component in the HC gov child ds
> Fix Tooltips with React versions < 16.6

- packages/design-system-docs/src/pages/components/ChoiceList/checkbox-radio.example.html
- packages/design-system-docs/src/pages/components/DateField/datefield.example.html
- packages/design-system-docs/src/pages/components/Dropdown/dropdown.example.html
- packages/design-system-docs/src/pages/components/FormLabel/_FormLabel.docs.scss
- packages/design-system-docs/src/pages/components/FormLabel/form-label.example.html
- packages/design-system-docs/src/pages/components/TextField/textfield.example.html
- packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/design-system/src/components/FormLabel/FormLabel.jsx
- packages/design-system/src/components/FormLabel/__snapshots__/FormLabel.test.jsx.snap
- packages/design-system/src/styles/components/_FormLabel.scss
Add class `ds-c-field__error-message` and use in-place of `.ds-c-field__hint .ds-u-color--error` for handling the display of error message by the `FormLabel` component that currently has this error message handling.
- Add classes `ds-c-field__error-message` and ` ds-c-field__error-message--inverse`.
- Use these classes for display of field error message instead of the current usage of `ds-c-field__hint .ds-u-color--error`
- Run the design system site locally
- Check dev console log to make sure the new classes is applied for the following examples `Date field`, `Checkbox & Radio`  and `Form Label & Legend`
> [WNMGDS-568] Add styles for field error message class

- packages/design-system-docs/src/pages/components/Review/review.example.html
- packages/design-system/src/components/Review/Review.jsx
- packages/design-system/src/components/Review/__snapshots__/Review.test.jsx.snap
- packages/design-system/src/styles/components/_Review.scss
- packages/design-system/src/styles/components/index.scss
This fixes the issue of Review component classes cannot be overridden because the component applies utility styles which uses `!important`.
- Update Review component to apply it's component styling instead of using utility classes.
- `ds-c-review` and `ds-c-review__heading` classes 
- Run the design system site locally
- Update Review example to [override classes](https://github.com/CMSgov/design-system/issues/817) and check that the styles applied correctly
> [WNMGDS-632] Apply Review classes

- packages/design-system-docs/src/pages/components/DateField/datefield.example.html
- packages/design-system/src/components/DateField/DateField.jsx
- packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/design-system/src/styles/components/_DateField.scss
- packages/design-system/src/styles/components/_Review.scss
- The `Datefield` HTML example in the Mgov DS doc site was looking weird because of inconsistencies between React and HTML example markup
- This PR fixes those inconsistencies by removing an unnecessary utility class and updating the `id`.
- This PR also introduces a new classname `ds-c-datefield__label` to apply to m/d/y labels, reducing the amount of utilities used and making it easier to override those styles (as is the case in Mgov)
- Ensure no visual changes in the core CMSDS
- Run this branch in the Mgov DS and ensure the HTML and React examples for form elements are correct, especially DateField and ChoiceList
> [WNMGDS-664] Update DateField markup

- packages/design-system/src/components/TextField/TextField.jsx
- packages/design-system/src/components/TextField/TextField.test.jsx
- packages/design-system/src/components/TextField/__snapshots__/TextField.test.jsx.snap
This PR fixes https://github.com/CMSgov/design-system/issues/838
A default `ariaLabel` was added to currency masks originally to give screen reader users more contexts, but this prevents users from defining their own `ariaLabel` for currency fields.
Instead of requiring a hardcoded `ariaLabel`, we want the `ariaLabel` as a normal prop.
- Ensure `ariaLabel` isnt defaulted for currency mask
> [WNMGDS-659] Remove default currency ariaLabel

- packages/design-system/src/components/Tooltip/Tooltip.e2e.test.js
Currently, the `yarn test:e2e` ends with timeout error for Tooltip component.
Found that testing for any of these will timeout.
- expect(await getElementByClassName('ds-c-tooltip')).toBeTruthy();
- expect(await getElementByClassName('ds-c-tooltip__content')).toBeTruthy();
- expect(await getElementById(‘trigger_1)).toBeTruthy();
``` : Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.Error:```
- Update the Tooltip e2e test to look for another classname
> [NO_TICKET] Update Tooltip e2e test

- packages/design-system/src/types/Autocomplete/Autocomplete.d.ts
https://jira.cms.gov/browse/WNMGTAXTOOLS-95
After upgrading to the latest version of the design system and migrating to TypeScript, we started getting errors for passing props to `Autocomplete` that were defined for `Downshift` but not listed explicitly in the `Autocomplete` props' type definition. We had to ignore the line where we passed `defaultInputValue`, but it turns out that prop was incorrect as of Downshift v3 (changed to `initialInputValue`). I've tested that these typedef changes allow me to uncomment my `initialInputValue={text}` line without errors.
- Since downshift props can be passed down through `Autocomplete`, add it to TypeScript definition so we don't get errors when passing those props.
> [WNMGTAXTOOLS-95] Add Downshift props to Autocomplete props' type def

- packages/design-system/src/styles/components/_StepList.scss
StepList green checkmark is sometimes printed with an extra marking. 
Add background no-repeat to the green checkmark icon style to remove the extra marking.
> [NO_TICKET] Update Step List background image to no-repeat

- packages/design-system/src/components/HelpDrawer/HelpDrawerToggle.jsx
- packages/design-system/src/components/HelpDrawer/__snapshots__/HelpDrawerToggle.test.jsx.snap
- packages/design-system/src/types/HelpDrawer/HelpDrawerToggle.d.ts
There is a React warning happening for the HelpDrawerToggle:
```
Warning: React does not recognize the `helpDrawerOpen` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `helpdraweropen` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
in button (created by Button)
in Button (created by HelpDrawerToggle)
in HelpDrawerToggle (at HelpDrawerWrapper.tsx:69)
```
The `helpDrawerOpen` prop was being applied to the Button component which it shouldn't be, so I added it to line 17 to pull it out from the others variable before others is applied to the Button
> [No Ticket] - Fix HelpDrawerToggle React Warning

- packages/design-system-docs/src/pages/styles/color-palette/_color-palette.docs.scss
We don't really use color in the same way as USWDS does now in their V2.
I don't think it makes sense to link out to their site on this page.
This PR removes the USWDS link from the color palette page
> [NO-TICKET] Remove USWDS link from color doc page

- packages/design-system-docs/src/pages/components/UsaBanner/usabanner.example.html
- packages/design-system/src/components/UsaBanner/UsaBanner.jsx
- packages/design-system/src/components/UsaBanner/__snapshots__/UsaBanner.test.jsx.snap
- packages/design-system/src/images/close-alt.svg
- packages/design-system/src/styles/components/_UsaBanner.scss
- Add responsive feature to USA banner component on small viewport.
- Run the doc site locally with `yarn start`
- Then visit the USA Banner component page and ensure the USA banner displays correctly on resizing of the viewport
> [WNMGDS-718] Add responsive styling to USA banner component

- packages/design-system-scripts/cli.js
Update the domain path for design system docs site where the initial default `rootPath` is configured under `cmsds.config.js`. 
To support "build-a-branch" option for CBJ to build testing docs site for the branch name, a different `rootPath` can be  set via command line args as follows: 
`yarn build --rootPath="release-2.2.1"`
- Run `yarn build --rootPath="test-branch"` and note that `rootPath` is set to `test-branch`
> [WNMGDS-733] Add `rootPath` parameter to cli.js

- packages/design-system-scripts/package.json
- packages/design-system/package.json
- Move core-js dep into design-system package
- Test this PR in [windowshop](https://github.cms.gov/CMS-WDS/windowshop/compare/master...pwolfert/cmsds-2.2.1-error) and ensure this error does not occur:
> [WNMGDS-734] Fix core-js imports in Tooltip

- packages/design-system/src/components/Autocomplete/Autocomplete.jsx
- packages/design-system/src/components/Table/Table.jsx
Fix HCgov Header/Footer component page not displaying correctly on local testing of HCgov design system document site (note: odd that it does work on github pages though)
This issue was introduced in [PR Autocomplete component not rendering](https://github.com/CMSgov/design-system/pull/881)
- Run the doc site locally with `yarn start`
- Setup HCgov child design system in the package.json to reference this branch with `file:../design-system/package/design-system/`
- Run `git clean -fdx` and then `yarn install` to Install the local DS branch
- Test that the Header and Footer component pages are displaying correctly
> [WNMGDS-745] Fix HCgov Header/Footer displaying empty screen

- .eslintrc.js
- .travis.yml
- packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
- packages/design-system/src/components/DateField/DateField.jsx
- packages/design-system/src/components/DateField/DateInput.jsx
- packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/design-system/src/components/Dropdown/Dropdown.jsx
- packages/design-system/src/components/Dropdown/Select.jsx
- packages/design-system/src/components/Dropdown/Select.test.jsx
- packages/design-system/src/components/Dropdown/__snapshots__/Select.test.jsx.snap
- packages/design-system/src/components/FieldContainer/FieldContainer.test.tsx
- packages/design-system/src/components/FieldContainer/FieldContainer.tsx
- packages/design-system/src/components/FieldContainer/InlineError.tsx
- packages/design-system/src/components/FieldContainer/__snapshots__/FieldContainer.test.tsx.snap
- packages/design-system/src/components/FormLabel/FormLabel.jsx
- packages/design-system/src/components/FormLabel/FormLabel.test.jsx
- packages/design-system/src/components/TextField/TextField.jsx
- packages/design-system/src/components/TextField/TextInput.jsx
- packages/design-system/src/components/TextField/TextInput.test.jsx
- packages/design-system/src/components/TextField/__snapshots__/TextInput.test.jsx.snap
- tsconfig.json
- Handle `aria-invalid` in TextField and Dropdown when `errorMessage` prop is provided
- Handle `aria-invalid` in FieldContainer when `fieldset` component type is used and `errorMessage` prop is provided
- Refactor and move aria attribute handling to TextInput and Select
- Add tests and snapshots
- http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-686/add-aria-invalid
> [WNMGDS-686] Use aria-invalid attribute in form components

- packages/design-system/src/components/ChoiceList/ChoiceList.jsx
- packages/design-system/src/components/DateField/DateField.jsx
- packages/design-system/src/components/Dropdown/Dropdown.jsx
- packages/design-system/src/components/FieldContainer/FieldContainer.tsx
- packages/design-system/src/components/FieldContainer/InlineError.tsx
- packages/design-system/src/components/FormLabel/FormLabel.jsx
- packages/design-system/src/components/MonthPicker/MonthPicker.jsx
- packages/design-system/src/components/TextField/TextField.jsx
- packages/design-system/src/types/ChoiceList/ChoiceList.d.ts
- packages/design-system/src/types/DateField/DateField.d.ts
- packages/design-system/src/types/Dropdown/Dropdown.d.ts
- packages/design-system/src/types/FormLabel/FormLabel.d.ts
- packages/design-system/src/types/MonthPicker/MonthPicker.d.ts
- packages/design-system/src/types/TextField/TextField.d.ts
- Adds `errorMessageClassName` prop to all form components
- Ensure props are being passed around correctly
- Use the new prop in a Typescript app
> [WNMGDS-791] Add errorMessageClassname prop

- packages/design-system-docs/src/pages/components/Autocomplete/Autocomplete.example.jsx
- packages/design-system/src/components/Autocomplete/Autocomplete.jsx
- packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
- packages/design-system/src/styles/components/_Autocomplete.scss
Bottom placed errors breaks the Autocomplete's design, specifically with the autocomplete list and "clear search" button. 
Context: https://github.com/CMSgov/design-system/pull/914#issuecomment-767837341
Updated markup and/or styling to fix these errors
- hidden bottom error message if the autocomplete list items is being displayed (which is the same as dropdown component). For this example, top error placement is recommended as the bottom placed error message will be hidden by the autocomplete list items:
http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-766/Handle-Autocomplete-bottom-placed-error
> [WNMGDS-766] Handle bottom placed error in Autocomplete 

- packages/design-system-scripts/cli.js
Fix rootPath on child ds docs site not picking up the default value set on cmsds.config.js
- Run `yarn build` and verify that `design-system-docs/dist/index.html` contains the default path:
-  `<link rel="stylesheet" href="/index.css" />`
-  `<script src="/index.js"></script>`
- Run `yarn build --rootPath="test-branch"` and verify that `design-system-docs/dist/index.html` contains the correct path:
-  `<link rel="stylesheet" href="/test-branch/index.css" />`
-  `<script src="/test-branch/index.js"></script>`
- On Child ds, run `yarn build` and verify that `docs/dist/index.html` contains the correct default path: eg
-  `<link rel="stylesheet" href="/hcgov-design-system/index.css" />`
-  `<script src="/hcgov-design-systemh/index.js"></script>`
> [WNMGDS-801] Fix rootPath on docs site

- guides/RELEASE-PROCESS.md
Update release notes `guides/RELEASE-PROCESS.md` to reference CB Core and to enter `branch` instead of the `tag`.
> [NO_TICKET] Update release notes to reference CB Core

- packages/design-system-scripts/gulp/docs/extractReactData/parseReactFile.js
- packages/design-system-scripts/gulp/docs/webpack/createWebpackConfig.js
Prevents react-docgen error in HCgov Child DS
Run this branch on HCgov child ds and ensure there isnt any errors
> [NO_TICKET] Allow react-docgen-typescript to find tsconfig.json with path.resolve

- packages/design-system/src/components/ChoiceList/ChoiceList.jsx
- packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.jsx.snap
- packages/design-system/src/components/DateField/DateField.jsx
- packages/design-system/src/components/DateField/__snapshots__/DateField.test.jsx.snap
- packages/design-system/src/components/Dropdown/Dropdown.jsx
- packages/design-system/src/components/FieldContainer/FieldContainer.tsx
- packages/design-system/src/components/MonthPicker/MonthPicker.jsx
- packages/design-system/src/components/MonthPicker/__snapshots__/MonthPicker.test.jsx.snap
- packages/design-system/src/components/TextField/TextField.jsx
HCgov DS docs site displays blank screen for Header and Footer when we don't use the direct import of lodash.
See [this PR](https://github.com/CMSgov/design-system/pull/917) for similar fix.
- Run the doc site locally with `yarn start`
- Setup HCgov child design system in the package.json to reference this branch with `file:../design-system/package/design-system/`
- Run `git clean -fdx` and then `yarn install` to Install the local DS branch
- Test that the Header and Footer component pages are displaying correctly
> [NO-TICKET] Direct import of lodash

- packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
- packages/design-system/src/components/Button/Button.test.jsx
- packages/design-system/src/components/Dropdown/Select.jsx
- packages/design-system/src/components/Dropdown/__snapshots__/Select.test.jsx.snap
- packages/design-system/src/components/TextField/TextInput.jsx
- packages/design-system/src/components/TextField/__snapshots__/TextInput.test.jsx.snap
- Update TextField, Dropdown, and DateField components to avoid providing empty `aria-describedby` attributes.
- Ensure aria attributes are correct for both top and bottom placed errors
- `http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-10/feature
> [WNMGDS-817] Remove unnecessary aria-describedby

- packages/design-system-scripts/package.json
- yarn.lock
End to end tests are failing because chromedriver need to be updated to latest version.
Update chromedriver to v89.0.0
> [NO-TICKET] Update chromedriver to v89.0.0

- packages/design-system-docs/src/scripts/components/ReactPropDocs.jsx
This PR adds the compact table styling to the React property tables 
DEMO URL 
http://design-system-demo.s3-website-us-east-1.amazonaws.com/NO-TICKET-compact-table-for-props
> [NO-TICKET] Set prop tables on the doc site to be compact

- packages/design-system/package.json
- prerelease.sh
The zipped files generated by 'npm pack' for release does not include typescript source files. 
This PR adds typescript source files to the zipped files for publishing to npm.
- Run `npm pack ./packages/design-system/` command on terminal - this will generate a `.tgz` file
- Unzip the `.tgz` file and check that it contains all the files from `dist` folder and all the component files under `src/components` folder 
- Specifically check that it should include the typescript files for FormControl and InlineError
> [WNMGDS-823] Update build release files

- packages/design-system-docs/src/pages/components/Tooltip/Tooltip.example.jsx
- packages/design-system-docs/src/pages/components/Tooltip/_Tooltip.docs.scss
- packages/design-system/src/styles/base/_link.scss
- packages/design-system/src/styles/components/_Tooltip.scss
- packages/design-system/src/styles/components/_TooltipIcon.scss
[WNGMDS-850](https://jira.cms.gov/browse/WNMGDS-850)
There are two trigger link changes in this PR for trigger link styles.
(1) Based on Bernard's conversation [here](https://github.com/CMSgov/design-system/pull/971#discussion_r594705783) with @LouisFettet , the previous dashed underline made the trigger difficult to read.
**This is the example Louis showed of what a trigger looks like on hc.gov:**
**And this is what it looked like in the original Tooltip PR:**
This PR introduces a compromise between changing to `border-bottom` and the issue of the thick dashed underline being hard to read. Instead of using `dashed`, I discussed with Bernard using `dotted`, because it actually looks more like the dashed underline in Louis's example above. 
**Below is dotted:**
Also, I made use of the …
> [WNMGDS-850] Fix tooltip trigger link styles

- packages/design-system-docs/src/pages/components/Dialog/_Dialog.docs.scss
- packages/design-system/src/components/Dialog/Dialog.jsx
- packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
- packages/design-system/src/types/Dialog/Dialog.d.ts
Update `<Dialog>` to better document and expose options for customizing `<AriaModal>`, namely the focus behavior.
- Update `<AriaModal>` prop documentation to link to `react-aria-modal` documentation
- Add prop documentation for other common <AriaModal> props like `initialFocus`
- Deprecate `escapeExitDisabled` in favor of using `escapeExits` directly. `escapeExits` would be documented similarly to `initialFocus` and other AriaModal props
- Add UI and accessibility guidance to the Dialog on managing focus
- Ensure typescript defs are updated
Fixes: #901
- Go to demo test site: http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-719/update-dialog-props-focus-behavior
- Test that `Dialog` component and `Third party external link` pattern works
- Test using …
> [WNMGDS-719] Update Dialog to expose 'AriaModal' props

- packages/design-system-docs/src/pages/guidelines/component-maturity.md
Our component maturity documentation stated that draft versions should not be used https://design.cms.gov/guidelines/component-maturity/ 
This guideline seems to differ than how we want draft components to be thought of. 
This PR updates the guidance to reflect that Draft versions can be used but could be subject to change
> [NO-TICKET] Update documentation for draft versions of component maturity

- packages/design-system-docs/src/pages/components/Alert/_Alert.docs.scss
- packages/design-system/src/styles/components/_Alert.scss
Updating the icon used for the success alert to be more consistent with the the icons being used 
- Added alert variables to the documentation page for theming
- Changed the success alerts icon to used the checkmark that's filled
View the alert page and see that the success alert is using the filled check icon and matches the style of the others
**You'll need to run the site locally because icons don't show on the demo URLs**
> [WNMGDS-830] Update icon for success alert

- packages/design-system/src/components/Tooltip/Tooltip.jsx
- packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
- packages/design-system/src/styles/components/_Tooltip.scss
There was an issue noted by DK in [this pr](https://github.com/CMSgov/design-system/pull/979#issuecomment-808540772) where the screenreader was announcing the hidden content of interactive tooltips.
This is due to the fact that `aria-describedby` will announce the contents of items, even if they are hidden and have `aria-hidden` = true.
The non-interactive tooltips need `aria-describedby` because as you tab through them, the tooltip appears and we need the content of the tooltip to be read. However, for interactive tooltips, we do not want the content announced until the element is un-hidden, so we do not need `aria-describedby`
`aria-describedby` will now only be included on items that do not include the `dialog` prop (non-interactive tooltips)
- FIrst view the tooltip locally on master …
> [WNMGDS-876] Only include aria-describedby on non-interactive content Tooltips

- packages/design-system-docs/src/pages/components/Tooltip/Tooltip.example.jsx
When viewing the Tooltip component on localhost, a warning message of `<div> cannot appear as a descendant of <p>` is showing up on developer console. `<div> inside of <p>` is not valid HTML and should be avoided.
Changed tooltip examples to be wrapped by `<div>` instead of `<p>`
Test design system document site on local system (localhost) and view Tooltip component examples to ensure that there's no warning messages shown on the developer console.
> [WNMGDS-880] Tooltip examples displaying warning message

- packages/design-system-docs/src/pages/components/Dialog/_Dialog.docs.scss
Revert back guidance info to exclude the business guidance until further confirmation
Demo doc site: http://design-system-demo.s3-website-us-east-1.amazonaws.com/ni/revert-dialog-guidance
> [NO-TICKET] Revert back guidance info

- packages/design-system-scripts/gulp/build.js
Fix development so we don't have to constantly manually rebuild! :tada: 
When rebuilding there was an error being thrown that was introduced in #968. Reworked build.js so that error is not thrown.
- Run master first to see issue
- `yarn start` on master and load the Tooltip page on localhost
- Go to Tooltip.jsx and add in random text (ex Blah Blah Blah) on Line 172
- Notice that even though gulp attempts to rebuild, the page never refreshes with your text. You'll also see this error in the terminal
```
(node:97074) UnhandledPromiseRejectionWarning: TypeError: changedPath is not a function
```
- Revert your changes
- Check out this branch
- `yarn start` and load the Tooltip page on localhost
- Do the same with Tooltip.jsx. Notice after ~8 seconds, the page refreshes with correct text. The …
> [WNMGDS-851] Fix build error

- packages/design-system/src/components/Alert/Alert.jsx
- packages/design-system/src/components/Dialog/Dialog.jsx
- packages/design-system/src/types/Alert/Alert.d.ts
- packages/design-system/src/types/Dialog/Dialog.d.ts
Add GA event tracking to `<Alert>` and `<Dialog>` as [per Blast's requirements](https://confluence.cms.gov/display/HCDSG/Design+System+Component+GA+Event+Tracking%3A+Data+format): 
http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-833/ga-tracking-for-alert-and-modal/
Test locally:
- Test that `Alert` and `Modal Dialog` components work as per normal. Then proceed to test GA event tracking.
Alert:
- Go to `Alert` component.
- Inspect DevTools network tab and filter for `collect` to view the analytics data or view using Chrome's extension `Omnibug`: there should be GA events captured for the 3 React examples
Modal Dialog:
- Go to `Modal Dialog` component, the React example and click `Click to show modal` to open modal dialog.
- Inspect DevTools network tab and filter for …
> [WNMGDS-833] ga tracking for alert and modal

- packages/design-system-docs/src/pages/components/Alert/_Alert.docs.scss
- packages/design-system-docs/src/pages/components/Dialog/_Dialog.docs.scss
- packages/design-system-docs/src/pages/components/Dialog/_ThirdPartyLink.docs.scss
- packages/design-system-docs/src/pages/components/HelpDrawer/_HelpDrawer.docs.scss
- packages/design-system-scripts/gulp/docs/__tests__/__snapshots__/generateHtmlExample.test.js.snap
- packages/design-system-scripts/gulp/docs/generatePages/generateHtmlExample.js
- packages/design-system-scripts/gulp/docs/generatePages/generateReactExample.js
- packages/design-system/package.json
- packages/design-system/src/components/Alert/Alert.jsx
- packages/design-system/src/components/Alert/Alert.test.jsx
- packages/design-system/src/components/Dialog/Dialog.jsx
- packages/design-system/src/components/Dialog/Dialog.test.jsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.jsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.test.jsx
- packages/design-system/src/components/analytics/Analytics.ts
- packages/design-system/src/components/analytics/SendAnalytics.test.ts
- packages/design-system/src/components/analytics/SendAnalytics.ts
- packages/design-system/src/components/analytics/index.js
- packages/design-system/src/types/Alert/Alert.d.ts
- packages/design-system/src/types/Dialog/Dialog.d.ts
- packages/design-system/src/types/HelpDrawer/HelpDrawer.d.ts
- yarn.lock
To prepare for a release of the beta Help drawer component with GA event tracking as a POC, Blast suggested these key-value pairs changes.
```
Open help drawer event:
event_name: 'help_drawer_opened',
event_type: 'ui interaction',
ga_eventAction: 'opened help drawer',
ga_eventCategory: 'ui components',
ga_eventLabel: heading,
ga_eventType: 'cmsds',
ga_eventValue: '', 
heading: heading,
Close help drawer event:
event_name: 'help_drawer_closed',
event_type: 'ui interaction',
ga_eventAction: 'closed help drawer',
ga_eventCategory: 'ui components',
ga_eventLabel: heading,
ga_eventType: 'cmsds',
ga_eventValue: '', 
heading: heading
```
http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-888/update-beta-analytics-helpdrawer/components/help-drawer/
Test locally:
Test that Help …
> [WNMGDS-888] Update beta analytics help drawer

- packages/design-system/src/components/Tooltip/Tooltip.test.jsx
Tooltip unit test is displaying a console.error `Popper: Invalid reference or popper argument provided. They must be either a DOM element or virtual element.`. 
Mocked the popper module in the Tooltip test to avoid error
Run yarn test on master, see console errors pop up.
Run yarn test on this branch, no errors.
> [WNMGDS-896] Update tooltip test

- packages/design-system-docs/src/pages/components/Dialog/Dialog.example.jsx
- packages/design-system-docs/src/pages/components/Dialog/dialog-size.example.html
- packages/design-system-docs/src/pages/components/Dialog/dialog.example.html
- packages/design-system/src/components/Dialog/Dialog.e2e.test.js
Remove success/danger button variations from modal examples and replace with the primary button variation
Go to demo site: http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-893/remove-button-variations-from-modal-examples/components/dialog/
- check that the examples are all using the 'primary' button variation (which is blue) instead of the previous success (green) and danger (red) button variations
> [WNMGDS-893] Remove success/danger button variations from modal examples

- packages/design-system-docs/src/pages/components/Alert/_Alert.docs.scss
- packages/design-system-docs/src/pages/components/Dialog/_Dialog.docs.scss
- packages/design-system-docs/src/pages/components/Dialog/_ThirdPartyLink.docs.scss
- packages/design-system-docs/src/pages/components/HelpDrawer/_HelpDrawer.docs.scss
- packages/design-system/src/components/Alert/Alert.jsx
- packages/design-system/src/components/Alert/Alert.test.jsx
- packages/design-system/src/components/Dialog/Dialog.jsx
- packages/design-system/src/components/Dialog/Dialog.test.jsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.jsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.test.jsx
- packages/design-system/src/components/flags.ts
Put sending of analytics behind separate feature flags for each component that sends them while we get the issues worked out on the application side.
- Analytics-sending is now behind feature flags for each component that sends them. They all OFF by default for now.
> [NO-TICKET] Put analytics behind feature flags

- packages/design-system-scripts/package.json
- yarn.lock
End to end tests are failing because chromedriver need to be updated to latest version.
Update chromedriver to v91.0.0
> [NO-TICKET] Update ChromeDriver

- packages/design-system/src/components/Dialog/Dialog.jsx
Add `analytics` to the list of props destructuring as we don't want to pass this prop to `modelProps` which uses the spread operator to get all the unspecified props.
http://design-system-demo.s3-website-us-east-1.amazonaws.com/ni/remove-prop-from-modalprops
Test that Dialog continue to work as per normal.
> [NO-TICKET] Remove analytics prop from modelProps

- packages/design-system-docs/src/pages/utilities/background-color/background-color.example.html
- packages/design-system/src/styles/settings/variables/_color.scss
- packages/design-system/src/styles/utilities/_background-color.scss
Updated bg colors to mark old focus styles as deprecated while still supporting use 
Marked old focus styles as deprecated 
http://design-system-demo.s3-website-us-east-1.amazonaws.com/sw-focus-color-fix
Take a look at the bg color utility page to see that the old (gold) focus styles are present and marked as deprecated
> [NO-TICKET]Update focus bg colors to utility use

- packages/design-system/src/components/DateField/DateField.tsx
Re-refactored `<DateInput />` component to include `export` type to address any possible breaking API changes.
Referenced the [original TS conversion PR](https://github.com/CMSgov/design-system/commit/38d69fa924c8af6f1c86da30b6136971871b9270#diff-b3894434effaa75461ba8dcb9438ad92764a4b9bb71fa6a04ce652baa877a692) to update interface. 
- `DateFieldErrorPlacement` is now an exported type.
> Add export for DateFieldYearValue in <DateField />.

- packages/design-system/src/components/Dropdown/Dropdown.tsx
Re-refactored `<Dropdown />` component to include several `export` types/interfaces to address any possible breaking API changes.
Referenced the [original TS conversion PR](https://github.com/CMSgov/design-system/commit/c70d77a7903be42868c3725a5d3014a4cc44132f#diff-c132558c7ba0b4e130880148a65be06ed0cb42a950020183fb88bc11a899a351) to update interface.
`export`
- `DropdownDefaultValue`
- `DropdownOptions`
- `DropdownSize`
- `DropdownValue`
- `DropdownErrorPlacement`
Referenced new exports in main interface.
> Export several types and interfaces from <Dropdown />.

- packages/design-system/src/components/TextField/Mask.tsx
- packages/design-system/src/components/TextField/TextField.tsx
- packages/design-system/src/components/TextField/TextInput.tsx
Re-refactored `<Mask />`,  `<TextField />`, and `<TextInput />`,  components to include several export types to address any possible breaking API changes.
Referenced the [original TS conversion PR](https://github.com/CMSgov/design-system/commit/c70d77a7903be42868c3725a5d3014a4cc44132f#) to update interface.
`export`
- `maskValue` and `unmaskValue` functions (to be removed at next major version release)
- `TextFieldMask`
- `TextFieldSize`
- `TextFieldErrorPlacement`
- `TextInputMask`
- `TextInputRows`
- `TextInputSize`
- `TextInputErrorPlacement`
Referenced new exports in main interface.
> Review TS types/interfaces for TextField components.

- .github/workflows/build.yml
We recently adopted the Gitflow workflow, meaning all new development will branch off/into a newly created `development` branch. However, doing adding this new branch resulted in the build script failing. I've added `development` to a list of branches to fix this.
Followed [guidance from GitHub](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags) to do this fix.
Creating this PR should kick off a build check. Once it's merged, we'll see the other PRs builds run.
> Update build script to include development branch.

- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
Updated the Autocomplete component so that `aria-controls` attribute is present always.
Updated the Autocomplete component so that `aria-controls` attribute is always present.
* Pull up the demo site http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-995/autocomplete-accessibility-bugfix
* Navigate to the Autocomplete component
* Run AXE extension, confirm that `Required ARIA attributes must be provided` issue is resolved
> [WNMGDS-995] autocomplete aria attribute update

- packages/design-system/src/components/DateField/DateField.tsx
Duplicating fix from #1119 to go into `master` for a hotfix.
Review that PR for more details.
> Revert dateformatter in datefield interface to previous type.

- packages/design-system/src/components/DateField/DateField.tsx
Tyler Gould reported a breaking change in `DateField` component where the `dateFormatter` was no longer accepting a type of `any` - instead enforcing a strict `DateObject` type. Since this is a breaking change to the API, I've reverted this type back to its original definition.
You can see when [the changes were introduced in this commit](https://github.com/CMSgov/design-system/commit/38d69fa924c8af6f1c86da30b6136971871b9270#diff-a16e93d3d7e200cf3e3dce44ef2986d07b25c4fc8b9367e88ac2060ee3d25080L33-R32). I tried highlighting the specific line, but if the link doesn't correctly display, the change was made to file `DateField.tsx` (component) and line 32.
I also noticed as part of that refactor, the `defaultDateFormatter` is now being imported, but appears to be needed for this prop's default …
> [WNMGDS-1047] Revert `dateFormatter` to original type (DEV)

- packages/design-system/src/styles/base/_link.scss
ISSUE: Mobile view: Underlines in various texts seems to be broken 
DESCRIPTION: When PCII is open in mobile view, texts which are underlined, there seems to be line that is broken in pieces instead of continuous line.
https://jira.cms.gov/browse/WNMGPCII-1515 
changed value of text-underline-offset from `0` to `auto` where the browser chooses the appropriate offset for underlines.
https://developer.mozilla.org/en-US/docs/Web/CSS/text-underline-offset
take a look at the demo url on an iOS device to ensure that the links are not looking broken
http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1064-text-underline-fix
> WNMGDS-1064 - Fix text-underline bug 

- packages/design-system-scripts/package.json
- yarn.lock
Updated chrome driver version used in the e2e tests because the chromium version in our CI stack changed and e2e tests were failing.
> [NO-TICKET] Update chromedriver from version 91 to 93

- packages/design-system/src/styles/components/_Button.scss
Default button background color was being inherited for transparent button backgrounds. 
This PR makes the transparent button background transparent
> [NO-TICKET] Add transparent background to transparent button

- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- Revert change (#1133) to `getA11yStatusMessage` type so we aren't enforcing strict compliance to our `AutocompleteItems` interface. This was causing one hc.gov app to fail its build.
> [WNMGWINSHOP-934] Revert one prop type change for Autocomplete

- packages/design-system-scripts/helpers/e2e/assertNoAxeViolations.js
- packages/design-system-scripts/helpers/e2e/constants.js
- packages/design-system-scripts/jest/e2e.environment.js
- packages/design-system-scripts/jest/unit.config.js
- packages/design-system-scripts/package.json
- yarn.lock
Updating the npm package we use for axe accessibility testing
- Pull down branch
- run `yarn install`
- run `yarn test`
_Note: it is expected that the e2e tests will fail. Specifically, one of the spinner tests. This is good! This error was also caught by DK in [this Jira](https://jira.cms.gov/browse/WNMGDS-843) The fix for this test will come in a separate PR and that is a dependency for merging this PR_
> WNMGDS 814/e2e tool update

- packages/design-system/src/types/index.d.ts
Unfortunately in the `dist` copy of our core package the TS typedefs for the `analytics` folder were never exported, so we don't access to them in the child design systems. I don't think this warrants a hotfix release. I was planning on writing my new code for analytics in the header in TypeScript, but I'll just write it in plain JavaScript for now since it's only one helper function.
- TypeScript type definitions are now available for the `analytics` module
> [NO-TICKET] Expose type definitions for analytics modules

- packages/design-system-docs/src/pages/components/Table/table.example.html
This was brought up in Slack as something to fix about the plain HTML table example. The header is right aligned and it looks off. 
Removed the right align class from the table headers and cells. I think a better right aligned example would be needed to show when and why to align table content to the right.
Go to the demo site table page and see that the html table header for `Rate` is no longer right aligned. 
http://design-system-demo.s3-website-us-east-1.amazonaws.com/sw-remove-table-alignment
> [NO-TICKET] Update table example to fix right aligned header

- guides/RELEASE-PROCESS.md
The deploy script broke due to some recent changes in a shared script. That script doesn't support spaces in the job name or parent folder, so I renamed the job and its parent folder.
> [NO-TICKET] Update link to Jenkins job

- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/Autocomplete/keepInputDownshiftStateReducer.ts
All of the instances of Autocomplete that I know of on hc.gov require the behavior implemented in this PR. DM me for details and more context.
- Added `clearInputOnBlur` default prop to `Autocomplete` that can be set to `false` to keep input after blur, instead of the default behavior which is to clear input if no selections are made.
Modify one of the examples by setting `clearInputOnBlur` to false and observe the new behavior.
> [NO-TICKET] Add clearInputOnBlur prop to Autocomplete

- .github/workflows/build.yml
https://jira.cms.gov/browse/WNMGDS-1094
We're switching back to using `master` as our development and release branch. The `development` branch will be retired, so stop running CI tests for PRs against it.
> [WNMGDS-1094] Remove development branch from CI tests

- packages/design-system-scripts/gulp/build.js
- packages/design-system-scripts/gulp/common/logUtil.js
- packages/design-system-scripts/gulp/docs/docs.js
There are many steps in the build process, and they each have an OS-level popup notification associated with them. This is actually really obnoxious during development, so let's only use the notification for success messages. Even that has questionable utility.
- (Internal) Restrict the OS notifications for the build process to only show for success messages
Run `yarn start` or `yarn build`
> [NO-TICKET] Reduce OS notifications for build process

- packages/eslint-config-design-system/index.js
This particular rule isn't very helpful to us and ends up costing us time to try to fix. The lack of this rule will not result in choas in our codebase. Particularly the pattern to always include imports with multiple named imports before imports with single named imports seems arbitrary and doesn't help the eye find things when scanning an import list.
- Removed linter rule about ordering imports a certain way
Change the order of imports somewhere, [like putting this import last in the list](https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/components/ChoiceList/ChoiceList.tsx#L2). On master, `yarn lint` will throw an error. On this branch, it won't care.
> [NO-TICKET] Remove linter rule that hinders productivity

- publish.sh
This is a follow-up to https://github.com/CMSgov/design-system/pull/1156 after making improvements in https://github.com/CMSgov/hcgov-design-system/pull/100. It adds some additional logic in the `publish-release` script to determine whether there should be a non-default [npm dist-tag](https://docs.npmjs.com/cli/v7/commands/npm-dist-tag), specifically the `beta` tag. Adding this logic will mean that we don't accidentally mark our beta releases as `latest` in npm. If they are marked as `latest`, a team could accidentally download a beta release when they only want a stable release.
> [WNMGDS-1094] Add logic for determining npm dist-tags for beta releases

- publish.sh
- release.sh
- Now allows the `lerna version` command to do the tagging and committing. This results in tags for each of the packages that changed
- Creating the version bump branch now happens before the `lerna version` command. This doesn't result in any overall behavioral changes for the script; it's just what I had to do in order to cleanly get the automatically generated bump commit happen on a separate branch instead of master in a way that was easy to revert if someone exited out of the `lerna version` command or said "No" to the final question
- We now print out all the version tags and choose the first one in the example `yarn publish-release` command at the end of the script
1. Check out fe13e57ff56e7f3c8c98de0fbc643f9d4551eafe, which removes the teeth of the script. It won't push anything …
> [WNMGDS-1141] Update release scripts

- packages/ds-healthcare-gov/package.json
HC.gov DS has had some version bumps since merging. There are no code changes to the package, though, that aren't represented already.
> [NO-TICKET] Update ds-healthcare-gov package.json versions

- packages/ds-healthcare-gov/src/locale/es.json
https://jira.cms.gov/browse/WNMGTAXTOOLS-136
While working on https://jira.cms.gov/browse/WNMGTAXTOOLS-127 it was discovered that the Spanish translation for the skip-nav label did not match English. The current English translation is `Skip to main content` while the Spanish translation was `Omitir Navegación` which translates to `Skip Navigation`. As part of the work for TT-127 Meghan gave the translation `Ir al contenido principal` to be used for Spanish.
Update the Spanish translation for `skipNav` to `Ir al contenido principal`
http://localhost:3000/patterns/header/ is the component but it seems like the example is broken when toggling to use Spanish. The unit tests are also not set up to render translations
> [WNMGTAXTOOLS-136] Update skip-nav Spanish translation

- package.json
- publish.sh
https://jira.cms.gov/browse/WNMGDS-1142
For context, see https://github.com/CMSgov/design-system/pull/1212
- Updated the `gh-pages` command to also deploy medicare to GitHub Pages
- Updated the release-publish script to build and zip the ds-medicare-gov package
> [WNMGDS-1142] Update release-publish and gh-pages commands for medicare

- packages/ds-healthcare-gov/src/components/Footer/Logo.jsx
- packages/ds-healthcare-gov/src/components/Footer/LogosRow.jsx
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.jsx.snap
Context: https://github.com/CMSgov/design-system/pull/1212#issuecomment-964526632
This can either be merged into the existing PR for medicare.gov or rebased after that one is merged, depending on which one is approved first.
Fixes the healthcare.gov `Footer` component, which previously rendered what looked like garbage (the svg markup) rather than logos. The babel config specific to hc.gov was removed, so we needed to switch to using the svg loader plugin that the root babel config uses.
To compare, view the Footer component with `yarn start:healthcare` on both master and this branch.
> [WNMGDS-1142] Fix footer SVG rendering

- README.md
- package.json
- packages/design-system-scripts/cli.js
- packages/design-system-scripts/jest/a11y.global-setup.js
Related to work under https://jira.cms.gov/browse/WNMGDS-1097, I want there to be a separate command for just building the packages vs building the docs site. Our underlying `cmsds` command-line utility supports two separate commands, so I'm making our `package.json` script aliases reflect that.
Run the `build` and `build-docs` commands to make sure everything works.
> [WNMGDS-1097] Separate our build commands in package.json

- .github/dependabot.yml
I'm seeing this error for the dependabot yml file.
I think it could be two things
1. I ran the yml through a validator and there was some indentation issues that this PR addresses
2. Other thing I'm guessing could be a problem is that maybe dependabot doesn't like duplicate `package-ecosystem: 'npm'`?
> Fixing dependabot.yml indentation

- packages/ds-medicare-gov/package.json
Not sure why lerna didn't update this automatically. Maybe it was the lack of a caret? Either way, it needs to be updated. One symptom on master right now is that if you install dependencies, it updates yarn.lock with entries for the last version of core.
> [NO-TICKET] Sync ds-medicare-gov with latest core

- packages/design-system-docs/src/pages/index.md
- packages/ds-healthcare-gov/docs/src/pages/index.md
- packages/ds-medicare-gov/docs/src/pages/index.md
- Updating doc site homepages to point to Sketch cloud versions of the UI toolkits
- Changes links to the Sketch UI toolkits to point to Sketch cloud 
- check out demo URL for the core update - http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-828
- Run locally to see the changes for Healthcare and Medicare with `yarn start:Healthcare` and `yarn start:Medicare`
> [WNMGDS-828] Update homepages to point to Sketch cloud toolkits

- packages/design-system/src/components/TextField/TextField.stories.jsx
Added stories for the TextField component that represent
* Single line state
* Multiline state
* error state
* disabled state
* success state
* Masked field
Should the Masked input be its own section? Should there be more variations?
Run `yarn storybook` and verify that TextField stories look okay.
> text field storybook stories

- packages/design-system/src/components/UsaBanner/UsaBanner.stories.jsx
- packages/design-system/src/components/VerticalNav/VerticalNav.stories.jsx
[Jira](https://jira.cms.gov/browse/WNMGDS-1155)
Add stories for USA Banner and Vertical Nav components.
Pull down this branch and run `yarn storybook`. USA Banner and VerticalNav stories should match docs site equivalents ([USA Banner link](https://design.cms.gov/components/usa-banner/), [VerticalNav link](https://design.cms.gov/components/vertical-nav/))
> [WNMGDS-1155] Init stories for USA Banner and vert nav

- package.json
- yarn.lock
This is not strictly a revert of what was done in https://github.com/CMSgov/design-system/pull/1375, as I've made the version number `^5` instead of the previous `5`. This seems to work after testing with Storybook. Prior to this change, Storybook would not build.
Fixes Storybook failing to build after https://github.com/CMSgov/design-system/pull/1375
`yarn install && yarn storybook`
> [NO-TICKET] Revert major version upgrade of css-loader

- .gitignore
- package.json
Creating / updating `build-storybook` scripts to allow for serving on static site for devops pipeline
Running `yarn build-storybook`, `yarn build-storybook:medicare` & `yarn build-storybook:healthcare` will build storybook in a static-site friendly way. The outputs of these commands will go in the directories `storybook-static/core`, `storybook-static/medicare` & `storybook-static/healthcare`, respectively.
I also added the `storybook-static` directory to gitignore since those files do not need to be tracked in version control
> [WNMGDS-1156] updating scripts to build storybook

- examples/child-design-system/src/styles/settings/variables/_override.build.scss
- packages/design-system-docs/src/pages/styles/typography/_typography.docs.scss
- packages/design-system/src/styles/base/_link.scss
- packages/design-system/src/styles/components/_Alert.scss
- packages/design-system/src/styles/settings/variables/_build.scss
- packages/ds-medicare-gov/docs/src/pages/styles/typography/_typography.docs.scss
- packages/ds-medicare-gov/src/styles/settings/_variables.build.scss
Removing the `$ds-include-base-html-rulesets: true !default;` setting because it's never been set to false and is not needed. This was specifically used for styling an A tag only. 
From the doc site 
> The only base HTML element the design system applies styling to is the `<a>` element. You can also use `.ds-c-link` and `.ds-c-link--inverse` for styling links.
- Removed instances where the `ds-include-base-html-rulesets` was set to true
- Removed the instances where the `ds-include-base-html-rulesets` were wrapping an a tag
- Run the doc site locally `yarn start` and see if links appear differently than the live site. do the same for Medicare and Healthcare with `yarn start:medicare` and `yarn start:healthcare`
> [WNMGDS-983] Remove base html ruleset variable 

- packages/ds-healthcare-gov/package.json
- yarn.lock
reverting react-i18next package back to previous version (9.0.10) to allow react examples to build on hgov
Run `yarn install`. Run `yarn start:healthcare`. Confirm that react examples are viewable in hgov doc site
> [NO-TICKET] reverting react-i18next package back to previous version

- packages/design-system/src/types/index.d.ts
Removing duplicate TS exports. They were needed when the components were JS, but now that they are TS, the types are generated automatically.
> [WNMGDS-972] clean up TS exports

- packages/design-system-docs/src/pages/utilities/margin/margin.example.html
- packages/design-system-docs/src/pages/utilities/padding/padding.example.html
- packages/design-system/src/styles/settings/variables/_layout.scss
- packages/design-system/src/styles/utilities/_margin.scss
- packages/design-system/src/styles/utilities/_padding.scss
[Jira](https://jira.cms.gov/browse/WNMGDS-1207)
New margin/padding util classes supporting a half value.
How our Sass spacer variables are created, using a map instead of a list.
~You should be able to visit [margin docs](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1207/update-spacer-utils/utilities/margin/) and [padding docs](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1207/update-spacer-utils/utilities/padding/) to see a new half value in the documentation.~ This value should evaluate to 4px (half of our base of 8px).
Looks like build is currently disabled. You can test by building locally until this is resolved.
> [WNMGDS-1207] Update spacer utils

- packages/ds-healthcare-gov/src/components/Footer/LogosRow.jsx
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.jsx.snap
https://jira.cms.gov/browse/WNMGDS-1287
- Fix a11y error about Healthcare.gov Footer logo links having no text
`yarn build-docs && yarn test:a11y:healthcare`
> [WNMGDS-1287] Fix a11y error about logo links having no text

- release.sh
If you've got other local tags and run the release script, it'll try to push all those that aren't found on origin to origin, and it may fail. We really only need to be pushing the new tags.
Example:
```
To https://github.com/CMSgov/design-system.git
* [new tag]           @cmsgov/design-system-docs@2.12.0-beta.3 -> @cmsgov/design-system-docs@2.12.0-beta.3
* [new tag]           @cmsgov/design-system@2.12.0-beta.3 -> @cmsgov/design-system@2.12.0-beta.3
* [new tag]           @cmsgov/ds-healthcare-gov@6.4.0-beta.3 -> @cmsgov/ds-healthcare-gov@6.4.0-beta.3
* [new tag]           @cmsgov/ds-medicare-gov@3.4.0-beta.5 -> @cmsgov/ds-medicare-gov@3.4.0-beta.5
* [new tag]           @cmsgov/ds-medicare-gov@3.5.0-beta.1 -> @cmsgov/ds-medicare-gov@3.5.0-beta.1
* [new tag]           test-tag -> test-tag …
```
> [NO-TICKET] Update release script to only push the new tags to origin

- .eslintrc.js
- package.json
- packages/design-system/src/components/Alert/Alert.test.tsx
- packages/design-system/src/components/Button/Button.test.tsx
- packages/design-system/src/components/Button/Button.tsx
- packages/design-system/src/components/DateField/DateInput.test.tsx
- packages/design-system/src/components/DateField/__snapshots__/DateInput.test.tsx.snap
- packages/design-system/src/components/List/List.a11y.test.tsx
- packages/design-system/src/components/TextField/TextInput.test.tsx
- packages/design-system/src/components/TextField/TextInput.tsx
- packages/design-system/src/components/TextField/maskHelpers.ts
- packages/design-system/src/components/analytics/SendAnalytics.test.ts
- packages/design-system/src/components/analytics/SendAnalytics.ts
- packages/design-system/src/components/analytics/index.ts
- tsconfig.json
Overview of changes
- Added a `yarn type-check` command
- TypeScript now checks our src files and ignores the manually-defined definition files found in `packages/**/src/types/`
- ESLint rule disabled that disallows the `@ts-ignore` directive. In certain cases it's not worth the time cost to solve every compiler error and have perfect type-checking. To see my attempt at fixing this error, look at https://github.com/CMSgov/design-system/commit/b5f986571b90338e5ca80d0fb79beb8d7efd8f34
- Fix errors in unit tests about `window.utag`
- Fix errors in Button tests by cleaning up Button prop types
- Fix errors in DateInput tests and remove an obsolete test
- Fix errors in maskHelpers tests by making optional function parameters optional
- Fix errors in TextInput tests by cleaning up TextInput …
> [WNMGDS-1272] Configure project for type-checking and fix errors

- packages/ds-healthcare-gov/package.json
- packages/ds-healthcare-gov/src/__mocks__/react-i18next.js
- packages/ds-healthcare-gov/src/components/Footer/Footer.jsx
- packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.jsx
- packages/ds-healthcare-gov/src/components/Header/ActionMenu.jsx
- packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.jsx
- packages/ds-healthcare-gov/src/components/Header/Header.jsx
- packages/ds-healthcare-gov/src/components/Header/I18nHeader.js
- packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsDialog.jsx
- yarn.lock
Over the course of several TypeScript config fixes, I think all of the problems causing us to revert the upgrade in https://github.com/CMSgov/design-system/pull/1405 are now resolved. Commits that I think collectively fixed the issue:
- https://github.com/CMSgov/design-system/commit/85f8f866f869ea3476a217efde0e6323267912be
- https://github.com/CMSgov/design-system/commit/7bf9c52d5e3d434f58817d0680aa2bb9685b205d
- https://github.com/CMSgov/design-system/commit/5171b7ecfa09956e8dd09196245d8998c5658084
- Upgraded `react-i18next` from `9.0.10` to `11.14.3`, which fixes TypeScript errors that pop up when we start trying to convert modules to TypeScript that use `react-i18next`
Install dependencies and then try all the build targets, including build, build-docs, start, storybook, and both child …
> [NO-TICKET] Upgrade react-i18next again

- .github/PULL_REQUEST_TEMPLATE.md
- packages/design-system/src/styles/components/_Drawer.scss
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-1320)
Added a z-index to the Drawer component. Because our modals have a z-index of 1000, I felt 500 was a safe index for Drawers.
You can review the Drawer and HelpDrawer components here:
- [Core Storybook](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1320/bug-helpdrawer-elevation/core/storybook/?path=/story/components-drawer--drawer-default)
- [Hcgov docs](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1320/bug-helpdrawer-elevation/hcgov/components/drawer/)
I tested that this works locally by adding the same z-index solution to the url referenced in the ticket.
> [WNMGDS-1320] Drawer z-index bug

- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
- packages/design-system/src/styles/components/_Dialog.scss
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-1326)
Added new class to body of Dialog and applied word break styles to said class. Updated snapshot for testing.
I did **not** add hyphen styles since that may result in broken URLs. This just adds word break styles to keep content in its modal.
I didn't want to commit a weird and long word to our Dialog story just to showcase this fix. To test, you'll need to run this branch locally (`yarn storybook`) and change the Dialog story to include a supercalafragilistically long word (should be around line 27 (children)).
I took a screenshot of what I saw and your results should be similar:
> [WNMGDS-1326] Bugfix - Wordbreak for modals

- packages/design-system/src/styles/components/_StepList.scss
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-1333)
Changed the display type of our substep list items from `inline-block` to `inline`. 
**Note:** After testing locally and through the URL cited in that issue, this appears to be the right fix, but I am somewhat nervous about changing an elements display when it's nested within a component this deeply. What I'm getting at is that this component would be greatly improved by a refactor - there are a lot of nested `div`s and incorrect markup at play here that make it tough to maintain when style bugs pop up. And without vis regression in play, fixing these bugs gives me the heebie-jeebies.
View [this demo URL](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1333/bugfix-steplist-list-styles/core/storybook/?path=/story/pat …
> [WNMGDS-1333] Bugfix - Steplist sublist on mobile

- packages/design-system/src/styles/components/_Accordion.scss
[JIRA ticket](https://jira.cms.gov/browse/WNMGDS-1308).
This PR updates [the Accordion component](https://design.cms.gov/components/accordion/) to support Windows High Contrast Mode.
Media queries that update the Accordion's header button to better describe its size and interactable status.
https://user-images.githubusercontent.com/634191/150204289-f32208dd-687f-47c1-ad87-7d0073eb9ca6.mp4
Accordion header button is visible in its resting state, and hover/focus interactions are now added.
> [WNMGDS] Accordion HCM support

- packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.test.jsx
- packages/ds-healthcare-gov/src/components/Header/DeConsumerMessage.tsx
- packages/ds-healthcare-gov/src/components/Header/Header.tsx
- packages/ds-healthcare-gov/src/components/Header/__snapshots__/DeConsumerMessage.test.jsx.snap
- packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.jsx.snap
As of https://github.com/CMSgov/design-system/pull/1454, we don't use the `withTranslation` HOC anymore. Somehow this was forgotten.
- Fixed `DeConsumerMessage` (part of HC.gov `Header`) using the old `withTranslation` HOC from `react-i18next`
> [NO-TICKET] Remove a missed withTranslation instance

- packages/design-system/src/styles/components/_Spinner.scss
[Jira](https://jira.cms.gov/browse/WNMGDS-1312)
HCM doesn't understand "transparent" color values. I replaced the transparent borders on Spinner with the Window, or background, color so you can see the animation.## How to test
Before:
After:
Visit [this link](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1312/HCM-spinner/core/storybook/?path=/story/components-spinner--default-spinner) to see the Spinner in action. Test in VM of your choice.
> Fix spinner on HCM

- packages/design-system/src/components/Alert/Alert.test.tsx
- packages/design-system/src/components/Alert/Alert.tsx
- packages/design-system/src/components/Badge/Badge.tsx
- packages/design-system/src/styles/components/_Alert.scss
- packages/design-system/src/styles/components/_Badge.scss
This work is an enhancement to HCM work done for Alert and Badge (#1516, #1537) to include screen reader support. Refactor removes reliance on JS to toggle queries and instead switches a `<span>` labeling the component variation from not visible to visible.
Preview [Badge](http://design-system-demo.s3-website-us-east-1.amazonaws.com/NO-TICKET/HCM-alert-badge/core/storybook/?path=/story/components-badge--default) and [Alert](http://design-system-demo.s3-website-us-east-1.amazonaws.com/NO-TICKET/HCM-alert-badge/core/storybook/?path=/story/components-alert--default) links (building).
> [NO TICKET] New HCM approach to include SR support

- packages/design-system/src/styles/components/_Choice.scss
- packages/design-system/src/styles/components/_Tabs.scss
- packages/design-system/src/styles/components/_TextField.scss
[Jira](https://jira.cms.gov/browse/WNMGDS-1307)
Added HCM disable styles for 
- Choice
- TextField (impacting all form components using this class)
- Tabs
I noticed Tabs CSS had some unnecessary styles applied. When a tab is disabled, it becomes a `<span>` under the hood, but the styles were applying/overwriting interactive states it no longer had by virtue of no longer being an `<a>` tag (as interactive tabs are). We were also adding a pointer cursor, then removing with a `pointer-events` style when disabled - that again, seemed unnecessary as these come with being either an `<a>` or a `<span>` tag under the hood.
I also moved the disabled styles to the bottom of the cascade, as this seemed to resolve a lot of the overrides applied. 
Less code === good 😎
Visit these links (building) and …
> [WNMGDS-1302] Implement HCM disable state

- packages/design-system/src/components/Button/Button.tsx
Our integration tests with a consuming application called out that the `inputRef` prop on `<Button>` should probably support RefObjects
Opened the branch `design-system-integration-7.0.0-beta.2` in pet-shared-components repo, verified that error
```
Type 'RefObject<HTMLButtonElement>' provides no match for the signature '(...args: any[]): any'.
```
existed.
- Pull down this branch. In the hgov repo, change the `@cmsgov/design-system` dependency version to point at your local version using the `file:..` syntax
- Run `yarn build` to build core
- Run `yarn build healthcare` to build hgov
- Navigate to pet-shared and change the hgov dependency path to your local copy using the `file:` syntax
- Run `yarn install` in pet-shared
- Observe that the TS error for button went away
> [WNMGDS-1371] updating inputRef typing on Button component

- packages/design-system/src/components/StepList/Step.tsx
- packages/design-system/src/components/StepList/StepList.tsx
StepList props became required to appease TypeScript, but the TypeScript definitions that were generated required those props from components that use `StepList`. We want the props that have default values to be optional to our users.
- Fixed optional `StepList` props that have default values being required
1. `yarn type-check`
2. Can also `yarn build` and look at the type output
> [WNMGDS-1401] Make the StepList props with default values optional

- packages/design-system/src/styles/components/_Accordion.scss
- packages/design-system/src/styles/components/_Alert.scss
- packages/design-system/src/styles/components/_Choice.scss
- packages/design-system/src/styles/components/_Dialog.scss
- packages/design-system/src/styles/components/_Drawer.scss
- packages/design-system/src/styles/components/_FilterChip.scss
- packages/design-system/src/styles/components/_Pagination.scss
- packages/design-system/src/styles/components/_SvgIcon.scss
- packages/design-system/src/styles/components/_Tooltip.scss
- packages/design-system/src/styles/components/_TooltipIcon.scss
- packages/design-system/src/styles/components/_UsaBanner.scss
- packages/design-system/src/styles/components/_VerticalNav.scss
- packages/design-system/src/styles/settings/mixins/_icons.scss
[JIRA ticket](https://jira.cms.gov/browse/WNMGDS-1306).
This PR updates our SVG icon component, components that use the SVG icon component, as well as minor usability tweaks when Windows High Contrast Mode is active. It is also a replacement PR for https://github.com/CMSgov/design-system/pull/1571.
High Contrast Mode media queries that:
- Update the base treatment of all SVG icons, including their fill and stroke values.
- Tweak SVG utilized in components, where the base treatment is insufficient.
- Tweak components to better demarcate component boundaries and communicate their interactivity.
<details>
<summary><b>Accordion</b></summary>
<h3>Before</h3>
<h3>After</h3>
</details>
<details>
<summary><b>Alert</b></summary>
<h3>Before</h3>
<h3>After</h3>
</details>
<details> …
> [WNMGDS-1306] SVG HCM support

- packages/design-system/src/components/InlineError/InlineError.tsx
- packages/design-system/src/components/InlineError/__snapshots__/InlineError.test.tsx.snap
- packages/design-system/src/components/flags.ts
[JIRA ticket](https://jira.cms.gov/browse/WNMGDS-1304).
This PR updates input validation error messages to always show an inline error icon before the string describing the error. This allows error messages to be understood as errors regardless of viewing mode.
Additional context:
- [Explanatory slide deck](https://docs.google.com/presentation/d/1OQ61eiufU4JQHgslEZaOM3YMdGS0EXDvRIXWEtSgbBQ/edit?usp=sharing)
- [Confluence decision log](https://confluence.cms.gov/pages/viewpage.action?spaceKey=HCDSG&title=Weekly+Design+System+design+sync#WeeklyDesignSystemdesignsync-Feb8,2022)
All design systems now display an inline error icon:
- `displayErrorIcon` and its associated logic is removed
- `getInlineErrorIconDisplay()` has also been removed
Run `yarn storybook` and trigger the error state of …
> [WNMGDS-1304] Form fields and states HCM support

- packages/design-system/src/components/IdleTimeout/IdleTimeout.stories.jsx
- packages/design-system/src/components/IdleTimeout/IdleTimeout.test.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeout.tsx
Some updates to the IdleTimeout component
* an effect that updates the time-in-message as well as the timeout cookie if the `timeToWarning` or `timeToTimeout` prop changes
* unit tests to support changes
* IdleTimeout story has some additional text to provide context for how the component works & a short time until warning modal is shown
* The `timeToWarning` prop so now its value represents how many minutes (from current time) of idle activity will trigger the warning modal
*   it used to be relative to the timeout time
* IdleTimeout story so now the component gets updated args properly
`yarn storybook` and navigate to the idle timeout component
> [WNMGDS-1330] warning time refactor

- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeout.test.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeout.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.tsx
Adding a close button to the IdleTimeout dialog. The close button behaves the same way 'continue session' does
* Close button and associated refs to the IdleTimeout component
* The `hideCloseButton` prop in the dialog component that was previously added specifically to support IdleTimeout
`yarn storybook`. Navigate to Components > IdleTimeout confirm modal functions as expected
Components > IdleTimeout > IdleTimeoutDialog will show you the dialog markup with the close button
> [WNMGDS-1458] idle timeout close

- packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsDialog.test.jsx
- packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsDialog.tsx
- packages/ds-healthcare-gov/src/components/PrivacySettings/PrivacySettingsTable.tsx
- packages/ds-healthcare-gov/src/components/PrivacySettings/__snapshots__/PrivacySettingsTable.test.jsx.snap
- packages/ds-healthcare-gov/src/styles/components/_Footer.scss
- packages/ds-healthcare-gov/src/styles/components/_PrivacySettingsDialog.scss
- packages/ds-healthcare-gov/src/styles/components/_PrivacySettingsTable.scss
- packages/ds-healthcare-gov/src/styles/components/_index.scss
https://jira.cms.gov/browse/WNMGDS-1465
- Revert the weird, one-off dialog-close button to the default
- Turn the checkboxes to radio buttons
- Give the radio buttons column a minimum width so the text doesn't wrap
- Stop right-aligning the CTA button
In the doc site or storybook, view the healthcare Footer component and click the "Privacy Settings" link to bring up the privacy settings dialog
[Healthcare docs site](http://design-system-demo.s3-website-us-east-1.amazonaws.com/pwolfert/fix-privacy-settings-inconsistencies/hcgov/)
[Storybook Healthcare](http://design-system-demo.s3-website-us-east-1.amazonaws.com/pwolfert/fix-privacy-settings-inconsistencies/hcgov/storybook/)
> [WNMGDS-1465] Update privacy settings dialog

- packages/design-system/src/styles/components/_Pagination.scss
- https://jira.cms.gov/browse/WNMGDS-1403
- Updated margin for previous and next pagination navigation items to be consistent 
- Also centered up the image with the text more
- Run the demo storybook site with `yarn storybook`
- View pagination stories at Components > Pagination
- See that the spacing between the icon and text for the previous and next navigation is now consistent compared to what is currently live https://design.cms.gov/components/pagination/
> [WNMGDS-1403] Update spacing for prev/next nav in pagination 

- packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.tsx
Updating spacing between buttons in idle timeout dialog to be 16px instead of 8px
> [NO-TICKET] idle timeout dialog button spacing

- packages/design-system/src/components/StepList/Step.tsx
- packages/design-system/src/components/StepList/StepLink.tsx
- packages/design-system/src/components/StepList/index.ts
https://jira.cms.gov/browse/WNMGDS-1467
A product team was passing a custom `component` to `StepList` steps, but they were getting a TypeScript error that their provided component was incompatible with what we expected. The problem was that the `React.ComponentType` [that we use here in the `StepLinkProps` definition](https://github.com/CMSgov/design-system/blob/master/packages/design-system/src/components/StepList/StepLink.tsx#L13) does not specify props for that component type, and therefore it seems to apply some default definition for props. The `React.ComponentType` type is actually a generic and can take a parameter. We were correctly using the `React.ComponentType` in other places in our project but not here.
- Fix `StepLink` custom component type definition rejecting correct usage …
> [WNMGDS-1467] Fix StepLink custom component typedef rejecting correct usage

- packages/design-system/src/components/Links/Links.stories.jsx
- packages/design-system/src/styles/base/_link.scss
Having background of link element be transparent when link has active & focus states.
[Bug report in Jira](https://jira.cms.gov/browse/WNMGDS-1445)
- Navigate to the [demo storybook site](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1445/inverse-link-style-updates/core/storybook/?path=/story/typography-links--links)
- View link stories at Typography > Links
- For the inverse link example, click & hold your cursor on the link (this creates an active & focus state). Confirm that the background color is transparent and meets accessibility expectations
- Alternatively, using dev tools, you can select an element in the the `elements` tab. Click the 3 dots to the left, go to 'focus state' and toggle on active & focus to see the reported state
- Is this the expected …
> [WNMGDS-1445] updating link styles for active and focus state

- .github/dependabot.yml
We decided to limit the scope of dependabot's search because most of what it was flagging were dev dependencies that are less important than our actual package dependencies. Hopefully this cleans up a lot of them. If they don't, we may need to just disable it entirely until a time when we can keep up with Dependabot.
> [NO-TICKET] Restrict dependabot's scope

- packages/design-system-docs/src/pages/components/Dialog/ThirdPartyLink.example.jsx
- packages/design-system-docs/src/pages/components/Dialog/_ThirdPartyLink.docs.scss
- packages/design-system-docs/src/pages/components/Icon/IconComponent.example.jsx
- packages/design-system/src/components/Icons/ExternalLinkIcon.tsx
- packages/design-system/src/components/Icons/index.ts
- packages/design-system/src/styles/components/_Dialog.scss
Adding external link icon and updating the external link pattern to use the icon as well as add guidance 
- Added external link icon 
- Added guidance for external link pattern
- Updated styling for modal button spacing to use variables
- Run the doc site locally with `yarn start` and navigate to the icon component page and see the external link icon
- Next navigate to the external link pattern and see the icon used in the example
> [WNMGDS 1447] [WNMGDS-1483] External link adding and pattern update

- packages/design-system/src/components/Button/Button.tsx
- packages/design-system/src/components/Button/__snapshots__/Button.test.tsx.snap
- packages/design-system/src/components/Tooltip/Tooltip.tsx
- packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.jsx.snap
After discussing with accessibility experts, it is better to not include `role="button"` on link elements if we are not going to support additional functionality to make a link truly act like a button. So, removing it from our button & tooltip components
Also, updated snapshot tests. Once merged, this might affect other teams' snapshot tests.
> [WNMGDS-1319] removing role button from links

- packages/ds-medicare-gov/docs/src/pages/components/GlobalHeader/GlobalHeader.docs.scss
- packages/ds-medicare-gov/docs/src/pages/components/Navbar/Navbar.docs.scss
- packages/ds-medicare-gov/docs/src/pages/patterns/consistent-header.md
Add consistent header documentation deprecate navbar and global header
- Added pattern page for consistent header and took info from MAX team Google doc 
- Deprecated Navbar page (deprecation notice points to Consistent header page)
- Deprecated Global header (deprecation notice points to Consistent header page)
- run the Mgov doc site `yarn start:medicare`
- Navigate to the consistent header pattern page and see content and instructions for use
- Navigate to navbar page and se deprecation notice
- Navigate to global header page and se deprecation notice
- How can we get a live example of the global header set on on this page?
> [WNMGDS-1427] [WNMGDS-1426] Add consistent header documentation deprecate navbar and global header

- packages/design-system-docs/src/pages/styles/spacing/_spacing.docs.scss
- packages/design-system-docs/src/pages/styles/spacing/spacing.example.html
- packages/design-system-docs/src/styles/base/_index.scss
- packages/design-system-docs/src/styles/base/_spacing.scss
Adding spacing variables and values to the spacing page
- Added examples of our spacing values 
- Run `yarn start` to run the doc site and go to the spacing page which is under styles in the left navigation. 
- See that the spacing examples are on the page
> [WNMGDS-1413] Add spacing example to page

- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.jsx.snap
- packages/design-system/src/components/IdleTimeout/IdleTimeout.test.tsx
[Jira](https://jira.cms.gov/browse/WNMGDS-912)
Our modal's action buttons are wrapped in an `<aside>` that's a sibling to the modal's `<main>` content. Replace the `<aside>` tag with a `<div>` and move to inside of `<main>` container.
There should be no visual changes.
Run `yarn storybook` or visit [testing url](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-912/bugfix/remove-aside-from-modal/core/storybook/?path=/story/components-dialog--dialog) and confirm the modal matches the [modal in prod](https://design.cms.gov/components/dialog/).
This is the PROD modal:
This is the local:
> [WNMGDS-912] Remove aside tag from modal

- package.json
- packages/design-system-tokens/package.json
- packages/ds-medicare-gov/package.json
- yarn.lock
In https://github.com/CMSgov/design-system/pull/1658, dependabot tries to update `@types/node` in `ds-medicare-gov`, but that package doesn't actually need that dev dependency. Instead, let's update it in the package files where it's relevant and remove it from `ds-medicare-gov`.
> [NO-TICKET] Update @types/node as alternative to #1658

- packages/design-system/src/styles/components/_Tooltip.scss
[Jira](https://jira.cms.gov/browse/WNMGDS-1537)
When text is added after the Tooltip component, it's pushed to the next line when tooltip is opened (via hover or toggle).
This appears to have been caused by the block display of the Tooltip.
To test, add text after the [inline Tooltip](http://design-system-demo.s3-website-us-east-1.amazonaws.com/WNMGDS-1537/BUGFIX/tooltip-line-wrap/core/components/tooltip/) via browser dev tools. Hovering over inline Tooltip should not result in text moving to next line.
> Update tooltip display to inline-block.

- packages/design-system-docs/src/pages/components/DateField/_DateField.docs.scss
We were telling users to install the core and layout package, which is not a thing anymore.
outdated documentation
Run the doc site locally with `yarn start` and see that the outdated documentation is no longer on the page.
> [NO-TICKET] Remove outdated documentation

- packages/design-system/src/__mocks__/i18next.js
- packages/design-system/src/__mocks__/react-i18next.js
- packages/ds-healthcare-gov/src/components/Header/Header.test.jsx
- packages/ds-healthcare-gov/src/components/Header/Header.tsx
- packages/ds-healthcare-gov/src/components/Header/__snapshots__/Header.test.jsx.snap
- packages/ds-healthcare-gov/src/components/Header/__snapshots__/defaultMenuLinks.test.js.snap
- packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.test.js
- packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
https://jira.cms.gov/browse/WNMGDS-1551
As part of our 7.0 release, I had updated the `defaultMenuLinks` function to accept a required `t` (`i18next` _translate_) function, but I did not realize this function was being used externally. The way the translations are set up to support the old component-specific language props, it is impractical to expect teams to supply this function, which needs to use our internal `i18next` instance and be configured to use the right namespace.
Additionally, the list of parameters for that function was way too long, and the unit tests for it were actually full of mistakes where the wrong parameters were being sent. I switched this long list of parameters with an object with named properties, and I've updated the unit tests and snapshots to be correct.
- …
> [WNMGDS-1551] Remove translation parameter from defaultMenuLinks function

- packages/design-system/src/components/i18n.ts
This is a follow-up to https://github.com/CMSgov/design-system/pull/1668, where I introduced a doc-site-builder bug.
- Fixed `document is not defined` error during doc-site build. It was insufficient to check for `document?.` because even the reference to `document` is not allowed on node, where it is never defined. I also tried `window.document?.`, but that had the same problem on node.
Build the doc site with either `yarn start` or `yarn build-docs`
> [WNMGDS-1355] Fix "document is not defined" error during doc-site build

- packages/design-system-docs/src/pages/guidelines/i18n.md
- packages/design-system/src/components/MonthPicker/MonthPicker.stories.jsx
- packages/design-system/src/components/MonthPicker/MonthPicker.tsx
- packages/design-system/src/components/UsaBanner/UsaBanner.stories.jsx
- packages/design-system/src/components/UsaBanner/UsaBanner.tsx
- packages/ds-healthcare-gov/src/components/Footer/Footer.stories.jsx
- packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
- packages/ds-healthcare-gov/src/components/Header/Header.stories.jsx
- packages/ds-healthcare-gov/src/components/Header/Header.tsx
- packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
This is a documentation-update followup to https://github.com/CMSgov/design-system/pull/1668
- Rewrote the documentation page for _Internationalization_ to reflect our current stance and features
- Soft-deprecated old per-component language props in the doc site, Storybook, TypeScript, and in code warnings. These will need to be fully deprecated by removal in a future breaking-change release.
> [WNMGDS-1355] Update i18n documentation

- packages/docs/gatsby-config.ts
Read an optional `PATH_PREFIX` environment variable inside the Gatsby config file to allow for using a custom path in our demo sites.
Run `PATH_PREFIX='/hello-world' PREFIX_PATHS=true yarn build:gatsby` and check to make sure the resources in `docs/public/index.html` are prefixed with `/hello-world`
> [NO-TICKET] Gatsby path prefix

- packages/ds-healthcare-gov/src/types/index.d.ts
Fixes the following error that was caught in a downstream project during the beta test:
```
./node_modules/@cmsgov/ds-healthcare-gov/dist/esnext/i18n.js
Attempted import error: 'Language' is not exported from '@cmsgov/design-system'.
```
In #1668, I started exporting that type from the core, but I never cleaned out the old explicit export of that type from healthcare's `types/index.d.ts`.
Unfortunately this file isn't type-checked by our current CI tests. I don't know a good way of type-checking this file, since it relies on the child design system being compiled in order for all of its imports to work. I tried building and pointing `tsconfig` to the dist folder, but that didn't catch the bug. Once we have fully deprecated the old Button props, we can remove this file. The only reason we …
> [BETA-FIX] Remove bad export of type in ds-healthcare-gov

- .storybook/preview.js
- packages/design-system/src/components/i18n.ts
After implementing https://github.com/CMSgov/design-system/pull/1756, I decided to go back and try to set up an easy way to switch between languages in our Storybook.
Added a language-switching button in our Storybook toolbar
- `yarn storybook` - Go to the `UsaBanner` story
- `yarn build && yarn storybook:healthcare` - Check out the `UsaBanner` story, but also check out the healthcare.gov `Header`
My implementation does a React no-no in that it calls a function with side-effects inside a render function. Until https://github.com/CMSgov/design-system/commit/e2736bee7872f71a22be71ebdb8ab4935e251bf6, I was doing it "the right way", but the right way was more complicated, more verbose, and less performant (I surmise at least). I decided to simplify. But would ya'll have kept it as it was?
> [NO-TICKET] Storybook language switcher

- packages/design-system/src/components/Alert/Alert.test.tsx
- packages/design-system/src/components/Alert/Alert.tsx
- packages/design-system/src/styles/components/_Alert.scss
I also moved the id for the header up one level so it would capture our a11y label as well. I discovered that it didn't include the a11y label when I was writing new unit tests.
https://jira.cms.gov/browse/WNMGDS-1642
- Previously Alerts without headings had no `aria-labelledby` attribute. The `aria-labelledby` attribute now falls back to the a11y label so that we satisfy the requirement for all `role="region"` elements to have an aria label.
<details>
<summary>Look at the accessibility tree in devtools:</summary>
</details>
There's maybe an opportunity to simplify the HTML here.
```html
<div class="ds-c-alert__header ds-c-alert__heading">
<span
class="ds-c-alert__a11y-label ds-u-visibility--screen-reader"
id="alert_a11y_label_6"
>
Notice:
</span>
<h2 class="ds-c-alert__heading">This is a …
```
> [WNMGDS-1642] Make sure Alerts always have an `aria-labelledby`

- packages/docs/content/3_styles/1_base.mdx
- packages/docs/package.json
- packages/docs/src/components/ContentRenderer.tsx
- packages/docs/src/components/EmbeddedExample.tsx
- packages/docs/src/helpers/loremIpsumGenerator.ts
- packages/docs/src/styles/components/embeddedExample.scss
- packages/docs/src/styles/components/syntaxHighlighting.scss
- packages/docs/src/styles/index.scss
- yarn.lock
* Migrating the Styles/Base page content
* Updated the content for MDX
* Add an `EmbeddedExample` component that will render some elements as well as the HTML for them.
* I did update the arrow used for the 'Code Snippet' portion to use one of our DS arrows
`yarn start:gatsby`. Navigate to Styles > Base and click through page
Code snippets closed:
Code snippets open:
> [WNMGDS-1596] Styles > Base content migration

- packages/design-system-docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
Because we're releasing packages at the same time, there's no reason for child design systems to have the more fuzzy `^` version matcher. A certain child design system release is always built for a specific core design system release. If teams ever need to revert or use a specific version of their child design system, the exact version will ensure that their resolved core package dependency in their lockfiles will always stay in sync.
- Changed child-design-system and docs package files to use an exact version of the core design-system package
> [NO-TICKET] Use exact design-system version in child design systems

- examples/create-react-app-typescript/package.json
The `examples/create-react-app` example has this dependency, but `examples/create-react-app-typescript` doesn't. Fixes #1122
- Fixed missing dependency in the `create-react-app-typescript` example, which only shows up if you are running it outside the context of our monorepo workspace
1. Copy the `examples/create-react-app-typescript` directory somewhere else on your filesystem, and cd to it
2. Run `yarn install && yarn start`
> [NO-TICKET] Add missing node-sass dependency to TS example

- packages/ds-medicare-gov/docs/src/pages/components/NavigationMenu/NavigationMenu.docs.scss
This is no longer in use due to the Consistent header provided by the max team. We can mark this for deprecation on the site.
Nav menu
Run the medicare doc site locally with `yarn start:medicare` and see that the navigation menu page has a deprecation notice
> [WNMGDS-1664] Deprecate nav menu Mgov component

- packages/design-system-tokens/src/themes/medicare.ts
- packages/design-system-tokens/src/tokens/color.ts
Adds copper colors to color tokens and changes medicare focus token to `copper-500`
> adding copper swatches and assigning focus style

- packages/design-system/src/components/Table/Table.stories.jsx
- packages/design-system/src/components/Tabs/Tabs.stories.jsx
- packages/docs/content/5_components/accordion.mdx
- packages/docs/content/5_components/drawer.mdx
- packages/docs/content/5_components/spinner.mdx
- packages/docs/content/5_components/table.mdx
- packages/docs/content/5_components/tabs.mdx
- packages/docs/content/5_components/text-field.mdx
- packages/docs/content/5_components/tooltip.mdx
- packages/docs/content/5_components/uSA-banner.mdx
- packages/docs/content/5_components/vertical-navigation.mdx
- packages/docs/src/components/PropTable.tsx
- packages/docs/src/components/StorybookExample.tsx
- packages/docs/src/components/ViewSourceLink.tsx
- packages/docs/src/helpers/graphQLTypes.ts
* Component content migration for:
* Spinner
* Table
* Tabs
* TextField
* Tooltip
* USA Banner
* Vertical Nav
* Made reusable 'View Source' link to standardize github url
* Updated the `PropTable` component to hide props that have the `@hide-prop` signifier in their description -- same as current site
`yarn build-storybook:gatsby` to build storybook once
`yarn build:gatsby && yarn serve:gatsby` to see doc site locally with storybook
> [WNMGDS-1676] component content pt 4

- packages/design-system/src/components/Icons/StarIcon.tsx
- packages/design-system/src/components/Icons/SvgIcon.test.tsx
- packages/design-system/src/components/Icons/SvgIcon.tsx
- packages/design-system/src/components/Icons/__snapshots__/SvgIcon.test.tsx.snap
- packages/design-system/src/components/Icons/icons.stories.tsx
- packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/design-system/src/components/UsaBanner/__snapshots__/UsaBanner.test.jsx.snap
The reported bug (#1880) was that a `data-testid` attribute passed to any DS icons was not being applied to the svg element. 
In this PR, I:
* Added a story in storybook for icons for easier testing
* Updated `SvgIcon` to pass through additional props
* Updated `StarIcon` to not pass through an invalid attribute
* Added some tests for `SvgIcon` and updated other tests accordingly
run tests with `yarn test` and ensure new unit tests to address this are passing.
You can update the `icons.stories.tsx` file so that one of the icon components has additional props (like `data-other`, etc). Run storybook with `yarn storybook`, navigate to the icon stories. Open dev tools and ensure that your custom attribute shows up on the svg element
Updated story example:
Result in Storybook:
> [WNMGDS-1712] icon props bugfix

- packages/docs/content/1_getting-started/0_installation.mdx
- packages/docs/src/styles/components/syntaxHighlighting.scss
- Adds documentation for usage of CDN JS/CSS to the `installation` page.
- Added a style so long `<pre>` will add scrollbar for x overflow
- Tested including resources with jsfiddle, worked great.
`yarn install`
`yarn build && yarn build-storybook:gatsby`
`yarn build:gatsby && yarn start:gatsby`
visit `http://localhost:8000/getting-started/installation`
> [WNMGDS-1690] Add CDN Documentation

- packages/docs/content/not-in-sidebar/404.mdx
- packages/docs/src/components/DocSiteSidebar.tsx
- packages/docs/src/pages/404.tsx
- Added 404 page markup
- Added 404 page content
- Added new folder `not-in-sidebar` to `content` folder to allow for content items that do not currently live in the sidebar and updated sidebar to exclude that data in it's query
`yarn install && yarn build && yarn build:storybook-gatsby && yarn build:gatsby && yarn start:gatsby`
Hit any missing page and since you're in `developer` mode it will give you a button to click to preview the 404 page, in production it will just show this page normally but in development mode you have to click to it.. Notice 404 page content does not show up in sidebar, making it available to edit more easily.
> [WNMGDS-1670] Gatsby 404 Page

- packages/design-system-docs/src/pages/utilities/background-color/background-color.example.html
- Fixes a small bug that came in with the token branch, old doc site 'background-color' page was broken because of a formatting issue
- Looks like prettier doesn't do a very good job with EJS, it's ugly but it's not broken now, and we won't have to deal with it for long / likely again.
`yarn install && yarn build && yarn build:healthcare && yarn start:healthcare`
[http://localhost:3000/utilities/background-color/](http://localhost:3000/utilities/background-color/)
> [NO-TICKET] Legacy docs background color page bug

- packages/docs/gatsby-node.js
- packages/docs/src/components/Layout.tsx
- Managed to get `start:gatsby` working with a helpful fix found with the googles! Express serves the /static dir now when running start:gatsby which gets the iframes going.
- Added a default lang to `html` to get past that accessibility flagging. 
`yarn install && yarn build && yarn build-storybook:gatsby && yarn start:gatsby`
Check out the html tag and the iframes!
> [No-Ticket] start:gatsby iframes and default lang

- packages/design-system/package.json
https://jira.cms.gov/browse/WNMGDS-1770
Downgrades ev-emitter to v1.1.1 which was previously upgraded by dependabot but introduced ES6 which broke healthcare's v2.2 webpack build
> [WNMGDS-1770] ev-emitter downgrade for ES6 issue

- README.md
- package.json
- scripts/deploy-demo.sh
https://jira.cms.gov/browse/WNMGDS-1684
We need a new place to put our branch demos
- Added a `yarn deploy-demo` command that builds and deploys a demo for your branch to GitHub Pages
- Or we could call it `yarn demo`. Thoughts?
Take a look at https://cmsgov.github.io/design-system/branch/pwolfert/gh-pages-branch-demos/
You can also try the command out locally, which will override this directory.
> [WNMGDS-1684] Add command to deploy branch demo to GitHub Pages

- packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.test.js
- packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
- packages/ds-healthcare-gov/src/components/Header/localeLink.ts
https://jira.cms.gov/browse/WNMGDS-1771
- Fixed the healthcare `Header` component's language-switching link relying on the deprecated `initialLanguage` prop to render
1. On master, `yarn build && yarn storybook:healthcare` and view http://localhost:6006/?path=/story/components-header--logged-out-header&globals=language:es. If you switch the global language to Spanish, the component will throw an error
2. On this branch, repeat the above steps. Should not throw errors
> [WNMGDS-1771] Fix locale link relying on deprecated `initialLanguage` prop

- packages/design-system-tokens/src/themes/medicare.ts
- packages/ds-medicare-gov/src/styles/settings/variables/_medicare-theme.scss
Apparently `$color-focus-dark` for Medicare got overwritten or was not set correctly for the current implementation, this came in with the token branch merge. This fix set's the focus color to it's correct value.
`yarn install && yarn build && yarn build:medicare && yarn start:medicare`
Validate the focus color is the correct copper color `#c97532`
> [WNMGDS-1772] BUGFIX: medicare focus-dark was missing the correct color

- packages/design-system/src/styles/components/_Choice.scss
https://jira.cms.gov/browse/WNMGDS-1773
The `flex-basis: min-content` declaration is not supported by Safari yet, so we can't rely on it to build our layout
- Fixed choices with long, wrapping label content pushing the whole label to the next line beneath the checkbox or radio button
1. Open up one of the choice list stories and modify it to have some really long hint text (or any text inside the label)
2. View it in Safari. Notice that on master the whole label will wrap below the checkbox or radio button
> [WNMGDS-1773] Fix long choice hint text wrapping the whole label in Safari

- packages/docs/content/5_components/modal-dialog.mdx
- packages/docs/src/components/ContentRenderer.tsx
- packages/docs/src/components/InfoPage.tsx
- packages/docs/src/components/Layout.tsx
- packages/docs/src/components/TableOfContents.tsx
- packages/docs/src/components/TableOfContentsMobile.tsx
- packages/docs/src/helpers/casingUtils.ts
- packages/docs/src/pages/index.tsx
Pulling Table of Contents data from graphql & also adding a null check on TOC data. If no data exists, don't show the components.
`yarn start:gatsby`
> getting graphql data for table of contents

- packages/design-system/src/styles/components/_UsaBanner.scss
- packages/design-system/src/styles/settings/mixins/_layout.scss
- packages/design-system/src/styles/utilities/_grid.scss
This is an alternative to https://github.com/CMSgov/design-system/pull/1957. I've changed the parts of our Sass code that were incompatible with `node-sass` (the old one) while still avoiding division-syntax deprecation warnings in dart `sass` (the new one).
- Fixes incompatibility of our Sass code with downstream projects that are still using `node-sass`. Everywhere that performed division using the `math.div` function has been replaced with `calc()`, which [according to the Sass documentation](https://sass-lang.com/documentation/breaking-changes/slash-div) might actually be evaluated during compile time when all the information is available.
> [NO-TICKET] Make Sass syntax compatible with node-sass compiler

- packages/design-system/src/components/VerticalNav/VerticalNavItemLabel.tsx
Fix #1979
Visit [demo site](https://cmsgov.github.io/design-system/branch/WNMGDS-1795/add-ariaCurrent-to-VerticalNav/storybook/?path=/story/components-vertical-nav--default-vertical-nav), open dev tools and "Grandchild link" should have `aria-current="true"` set.
> [WNMGDS-1795] Add aria-current to active link in VerticalNav

- release.sh
We recently patched an old version of the design system, but when that patch for an older version of a child design system was installed in a project, the core version resolved to the latest because npm/yarn deemed the versions compatible because of the caret `^` in our child design systems' package files. This is something we manually fixed once, but Lerna re-added the carets.
- Update release script to use exact versions of our design system packages during lerna version bump
You can use the release script if you want and then run `yarn release -u` to undo
> [NO-TICKET] Update release script to bump exact

- packages/design-system/src/components/Tooltip/Tooltip.stories.jsx
- packages/design-system/src/components/Tooltip/Tooltip.tsx
- packages/design-system/src/styles/components/_TooltipIcon.scss
Pre-storybook, our tooltip trigger examples had states for focus, active and hover. It's because our previous examples were using the `<Tooltip>` component's prop `activeClassName`. Instead of updating our examples, we can use CSS pseudo-selectors to add this styling instead of a whole class. We still need to support the `activeClassName` for backwards compatibility.
In this PR, I:
- Added a story for inverse tooltips to check this change
- Added selectors so that the active styling of tooltip triggers shows up
- Updated the logic for the `activeClassName` css class. Previously, if that optional prop was not provided, the tooltip trigger would get `undefined` added to its list of classes. Now, that value is just ignored.
`yarn start-storybook` to test changes in Tooltip stories
Before: …
> [WNMGDS-1781] adding hover, active, focus styling to tooltip trigger

- packages/docs/src/components/Layout.tsx
- packages/docs/src/styles/pages/layout.scss
The problem: with the new footer, some pages with a short amount of contents were not taking up the full vertical screen.
Solution: updated the page styles a bit to ensure the footer stays at the bottom
`yarn start:gatsby`
> [NO-TICKET] making doc site pages full height

- packages/docs/content/foundation/typography.mdx
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-1812)
The design system provides a way for folks to create unstyled lists by using a CSS class. What's not documented is that [Safari will remove an unstyled list](https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html) from the accessibility tree without proper workarounds.
I've updated our documentation to call this issue out and updated the code example to reflect the Safari fix.
[Demo docs](https://cmsgov.github.io/design-system/branch/WNMGDS-1812/update-list-docs/foundation/typography?theme=core#list)
> [WNMGDS-1812] Add unstyled list guidance for Safari

- packages/design-system-docs/package.json
- packages/design-system-scripts/package.json
- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
For this major beta version (4.0.0 / 8.0.0 / 6.0.0), we had to skip `-beta.1` because the `@cmsgove/design-system` package already had the version `4.0.0-beta.1` that seems to have been published in 2020 and unpublished.
- @cmsgov/design-system-docs@4.0.0-beta.2
- @cmsgov/design-system-scripts@4.0.0-beta.2
- @cmsgov/design-system@4.0.0-beta.2
- @cmsgov/cms-design-system-docs@4.0.0-beta.2
- @cmsgov/ds-healthcare-gov@8.0.0-beta.2
- @cmsgov/ds-medicare-gov@6.0.0-beta.2
> Release 4.0.0-beta.2

- packages/docs/package.json
Occasionally `start:gatsby` will fail with issues in `.cache`. I've found this happens most when switching branches with different doc site data. This just adds a `gatsby clean` before the develop process to make sure `.cache` and `public` are rebuilt before developing on the site locally.  `gatsby build` does this automatically.
> [NO-TICKET] adding gatsby clean before develop to fix cache issues

- packages/design-system-tokens/src/themes/healthcare-components.ts
- packages/docs/content/components/inset.mdx
- packages/docs/src/styles/index.scss
- packages/docs/src/styles/theme-variables/_healthcare-components-scss-to-css.map.scss
- packages/docs/src/styles/theme-variables/_healthcare-components-theme.css
- packages/ds-healthcare-gov/src/styles/components/_Inset.scss
- packages/ds-healthcare-gov/src/styles/settings/_healthcare-components-theme.scss
Adding content from the hgov-specific component `Inset`. I had to create an additional component variable for the theme
`yarn start:gatsby` and navigate to Components > Inset
Hgov doc page:
Other brand doc page:
> [WNMGDS-1829] Hgov Inset component documentation

- packages/design-system-tokens/src/themes/core-components.ts
- packages/design-system-tokens/src/themes/healthcare-components.ts
- packages/design-system-tokens/src/themes/medicare-components.ts
- packages/design-system/src/styles/components/_SingleInputDateField.scss
- packages/design-system/src/styles/components/_TextField.scss
- packages/design-system/src/styles/settings/variables/_core-components-theme.scss
- packages/docs/src/styles/theme-variables/_core-components-scss-to-css.map.scss
- packages/docs/src/styles/theme-variables/_core-components-theme.css
- packages/docs/src/styles/theme-variables/_healthcare-components-scss-to-css.map.scss
- packages/docs/src/styles/theme-variables/_healthcare-components-theme.css
- packages/docs/src/styles/theme-variables/_medicare-components-scss-to-css.map.scss
- packages/docs/src/styles/theme-variables/_medicare-components-theme.css
- packages/ds-healthcare-gov/src/styles/settings/_healthcare-components-theme.scss
- packages/ds-medicare-gov/src/styles/settings/variables/_medicare-components-theme.scss
https://jira.cms.gov/browse/WNMGDS-1796
The error-state border width wasn't previously being defined as a design token theme variable. 
- Fixed a problem where the different border width of error-state text fields caused the calendar picker border to look funny in the `SingleInputDateField`
Using [the storybook instance from this branch](https://cmsgov.github.io/design-system/branch/pwolfert/fix-error-border-width/storybook/?path=/story/components-singleinputdatefield--with-error), look at the error story for the calendar picker and confirm that it has been fixed
> [WNMGDS-1796] Fix border width issue for pickers in error state

- packages/design-system-tokens/src/themes/core-components.ts
- packages/design-system-tokens/src/themes/healthcare-components.ts
- packages/design-system-tokens/src/themes/medicare-components.ts
- packages/design-system/src/styles/components/_SingleInputDateField.scss
- packages/design-system/src/styles/components/_TextField.scss
- packages/design-system/src/styles/settings/variables/_core-components-theme.scss
- packages/docs/src/styles/theme-variables/_core-components-scss-to-css.map.scss
- packages/docs/src/styles/theme-variables/_core-components-theme.css
- packages/docs/src/styles/theme-variables/_healthcare-components-scss-to-css.map.scss
- packages/docs/src/styles/theme-variables/_healthcare-components-theme.css
- packages/docs/src/styles/theme-variables/_medicare-components-scss-to-css.map.scss
- packages/docs/src/styles/theme-variables/_medicare-components-theme.css
- packages/ds-healthcare-gov/src/styles/settings/_healthcare-components-theme.scss
- packages/ds-medicare-gov/src/styles/components/_override.forms.scss
- packages/ds-medicare-gov/src/styles/settings/variables/_medicare-components-theme.scss
When working on https://github.com/CMSgov/design-system/pull/2033 and testing the medicare version of the picker component, I noticed that the border radius on the calendar button didn't match the border radius for the text input. Even though the picker styles used the `$text-input__border-radius` variable for its border radius so it would match text fields, the text fields in medicare weren't actually taking their value from `$text-input__border-radius`. An override rule was replacing the value defined in the token theme with a static value in Sass.
- Fixed Medicare `ds-c-field` styles not using the `$text-input__border-radius` variable defined in the token theme
- Fixed border radius on the right side of the calendar picker not matching the left side …
> [WNMGDS-1796] Fix bad border-radius on one side of picker on medicare

- packages/docs/content/components/header/healthcare-header.mdx
- packages/docs/src/styles/index.scss
- packages/ds-healthcare-gov/src/components/Footer/Logo.tsx
* Adding docs for the Healthcare header
* Updating some docs in the healthcare Logo component that was causing gatsby build errors
`yarn start:gatsby`
> [WNMGDS-1829] healthcare header docs

- .github/PULL_REQUEST_TEMPLATE.md
- Updated PR template to be more succint and added a few important tasks that should be checked off before a PR is merged.
Feedback: What do you all think of this? It would be changed to look like this:
---
- Overview of changes.
> [no-ticket] updating pr template to be more succint with tasks

- packages/design-system-scripts/gulp/build.js
- packages/ds-medicare-gov/src/components/MedicaregovLogo/MedicaregovLogo.tsx
`yarn build:medicare` is currently failing in master because of a missing export on a props interface for `MedicaregovLogo`
`yarn install && yarn build && yarn build:medicare`
> [no-ticket] [bugfix] Missing export on mgov logo caused build to fail 

- packages/docs/src/components/TableOfContents.tsx
In https://github.com/CMSgov/design-system/pull/2076 we renamed the `feedback` page to `contact`, but [I forgot to change the link that pointed to it]((https://github.com/CMSgov/design-system/commit/7aff2011e5a4e47d043ab8b252e13042ccef46f5#diff-2b42bc3c6f340eb687c4f3b560ae8a7bba5a306ecc42ad1d2b56ff6e4975678dL57))
1. `yarn start`
2. Click on the link in the side bar under `Have ideas?` that says `Contact the team`
3. It should take you to the contact page
> [NO-TICKET] Fix contact link pointing to old `feedback` route

- packages/docs/src/components/Layout.tsx
- Building the doc site statically failed because apparently the `slug` is not always defined. Fix that
> [WNMGDS-1864] Make the page id logic resilient to undefined slugs

- packages/design-system/scripts/cmsds-migrate/configs/html-button-migration.mjs
- packages/design-system/scripts/cmsds-migrate/configs/react-button-migration.mjs
- `transparent` is now converted to `ghost`
- removed a couple escape backslashes that linter marked as un-necessary
1. `yarn install && yarn cmsds-migrate` - run it using button && react configs, should update appropriately
> [no-ticket] [bugfix] Update cmsds-migrate to convert 'transparent' to 'ghost'

- packages/docs/content/foundation/color.mdx
- packages/docs/content/utilities/background-color.mdx
- packages/docs/src/components/ColorSwatchList.tsx
- packages/docs/src/components/ContentRenderer.tsx
https://jira.cms.gov/browse/WNMGDS-1897
- Make the color swatch component dependent on the current `theme` so it will re-render when the theme changes
- Switch from `useLayoutEffect` to `useEffect` because `useLayoutEffect` will always run before the DOM gets updated, which means it will never have a value other than what it gets from the default styles that are applied for the `core` theme before the frontend app hydrates
This is a quick fix and should make the theme dependency clearer in the code, but a better long-term solution would be to figure out a way to get static versions of each page for each theme as explained in https://jira.cms.gov/browse/WNMGDS-1899. I'm going to continue to look into that, but for now I want to get a fix up.
`yarn build:docs && yarn serve:docs` and …
> [WNMGDS-1897] Fix color swatch hex values not updating for non-core themes

- packages/design-system/src/styles/components/_Drawer.scss
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-1918)
Reimplement 500 z-index on Drawer component. Using the Sass var/token that I accidentally forgot to delete the last time I refactored (thanks Past Sarah!).
Run `yarn storybook` on this branch to see the z-index was applied
> [WNMGDS-1918] Add z-index fix to Drawer

- packages/design-system/src/styles/components/_Button.scss
https://jira.cms.gov/browse/WNMGDS-1911
Other rules for button interaction states were setting the color property, but this particular rule didn't. This meant that while the local CSS variable in charge of the text color had the correct value, that value wasn't being applied by a rule that had higher specificity than the rule that applies focus styles for plain anchor elements. When focusing on the link buttons with a keyboard only, the plain anchor rule was winning out, which resulted in a text color that didn't match.
Fixes #2110 
1. Start Storybook and view http://localhost:6006/?path=/story/components-button--all-anchor-buttons
> [WNMGDS-1911] Fix anchor styles overriding anchor-button styles when keyboard focusing

- packages/design-system/src/components/Alert/Alert.stories.jsx
- packages/design-system/src/styles/components/_Alert.scss
https://jira.cms.gov/browse/WNMGDS-1921
- Adds a Storybook story that shows buttons and anchor-buttons inside alerts
- Fixes anchor buttons having incorrect styles applied inside alerts
1. Start storybook
2. Navigate to http://localhost:6006/?path=/story/components-alert--alert-with-buttons
- ~Updated unit test snapshots (`yarn update-snapshots`) and loki reference images **if necessary** (`yarn loki && yarn loki:healthcare && yarn loki:medicare`)~ Purposefully leaving loki out of this for now until we have a fix for VRTs
> [WNMGDS-1921] Fix styles for anchor buttons inside alerts

- .storybook/preview-body.html
- .storybook/preview.js
- packages/design-system/src/components/Button/Button.stories.jsx
- packages/design-system/src/components/ChoiceList/ChoiceList.stories.jsx
- packages/design-system/src/components/DateField/MultiInputDateField.stories.jsx
- packages/design-system/src/components/Dropdown/Dropdown.stories.jsx
- packages/design-system/src/components/FormLabel/FormLabel.stories.jsx
- packages/design-system/src/components/MonthPicker/MonthPicker.stories.jsx
- packages/design-system/src/components/Spinner/Spinner.stories.jsx
- packages/design-system/src/components/Tooltip/Tooltip.stories.jsx
- packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.jsx
The previous way of adding a dark background to Storybook stories had a few issues:
1. The background color had to be determined at the time of starting storybook, based on a `STORYBOOK_DS` environment variable and did not adapt to design-system theme changes done within storybook
- This could be considered a doc-site bug
3. The background color was hard-coded rather than using the styles we already have
4. Logic was duplicated for every story that used it and was verbose
This change addresses those problems. You no longer need to use `storybook:medicare` or `storybook:healthcare` for a dark-background story to show the right color.
1. Run `yarn storybook`
3. Navigate to http://localhost:6006/?path=/story/components-button--variations-on-dark
4. Change the theme between core, healthcare, …
> [NO-TICKET] Adapt the background color of inverse stories to the selected theme in Storybook

- packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
- packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/design-system/src/components/Dropdown/Dropdown.test.tsx
- packages/design-system/src/components/Dropdown/Select.test.tsx
- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/design-system/src/components/Dropdown/__snapshots__/Select.test.tsx.snap
- Updated `Autocomplete` `Dropdown` and `Select` tests to RTL
- Still having a problem with `userEvent` in the Select tests @pwolfert @zarahzachz if you have time to take a look, will continue to investigate but not having a lot of luck, even tried upgrading jest, jest dom and the userEvent library.
1. `yarn install && yarn test:unit`
> [WNMGDS-1869] Autocomplete, Dropdown/Select RTL Conversion

- tsconfig.json
- Removes outdated `.tsconfig` settings which seem to no longer be needed
1. `yarn type-check` - used to fail because of these, but it seems they are no longer needed, thoughts @pwolfert ?
> [no-ticket] Removing tsconfig settings which are no longer needed

- package.json
- yarn.lock
- In an earlier conflict resolution I grabbed the wrong block, in yarn.lock, this fixes that mistake
- updates `yarn test` command which had a superfluous `core` parameter causing `yarn test` to fail after unit tests
1. `yarn install && yarn test`
> [no-ticket] fixing yarn test and incorrect lockfile I messed up

- packages/design-system/src/components/Alert/Alert.test.tsx
- packages/design-system/src/components/Alert/Alert.tsx
- packages/design-system/src/components/Alert/useAlertAnalytics.ts
Removes logic that made the event content always match what was being sent before. We've been given the go-ahead to update and simplify this analytics logic in the next breaking change. It will now always include the a11y-label prefix because that always exists in the DOM, and we're always pulling from the DOM now.
> [NO-TICKET] Clean out unneeded `Alert` analytics logic

- packages/docs/src/components/content/ColorSwatchList.tsx
- packages/docs/src/components/layout/Layout.tsx
https://jira.cms.gov/browse/WNMGDS-1942
Our theming CSS is controlled by a `data-theme` attribute that we apply to the body element through a library component called `Helmet`. Helmet allows us to render a `<Helmet>` component anywhere in our render tree and have changes applied to the `head` of our document or the `body` element. It's a handy tool, but the changes it makes are necessarily out of the normal React rendering lifecycle. When we apply a new theme by changing our top-level `theme` prop it trickles down and causes re-renders for components that rely on it. But because the actual DOM update for `data-theme` happens out of band, there's no guarantee that the styles for the theme will have been applied by the browser by the time our `ColorSwatchList` component expects to be …
> [WNMGDS-1942] Fix color swatch hex values not updating for non-core themes in Firefox

- packages/design-system/src/styles/components/_Accordion.scss
- Removing max height and y overflow settings for Accordion, per [a recent conversation around the current behavior](https://adhoc.slack.com/archives/C645GLLNN/p1664397928811549?thread_ts=1664386875.605169&cid=C645GLLNN).
- [LHDM-953](https://jira.cms.gov/browse/LHDM-953) is the ticket our team has used to track changes. If references to this ticket need to be swapped out for another on the Experience board let me know and I'll update everything here.
1. View updates on Storybook Accordion page
> [LHDM-953] Remove Accordion max height and y overflow

- packages/docs/content/components/alert.mdx
- packages/docs/src/components/content/MaturityChecklist/MaturityChecklist.tsx
Part of https://jira.cms.gov/browse/WNMGDS-1842
This is a follow-up to https://github.com/CMSgov/design-system/pull/2165 that adds the color item back in and updates some text, based off of discussions we had in the maturity model document.
`yarn start`
> [WNMGDS-1842] Add "Color" item back in and change some language

- scripts/deployDemo.ts
The storybook build command changed, so we need to update the `yarn deploy-docs` script.
> [NO-TICKET] Update the deploy-docs command with new sub-command names

- .storybook/preview.js
- Updated our storybook viewport sizes to [match doc site](https://design.cms.gov/foundation/layout-grid/responsive-design?theme=core) 
- Added Xsmall, small, medium, large and Xlarge
1. run `yarn storybook` see that the viewports are available and that light/dark backgrounds are not available in the storybook top toolbar
https://user-images.githubusercontent.com/1449852/195638406-a53d93d8-7097-48b7-87d8-366782971159.mov
> [NO-TICKET] Add viewport sizes to storybook to match doc site and remove light/dark background options from storybook

- packages/design-system/src/styles/components/_Choice.scss
- packages/ds-medicare-gov/src/styles/components/_override.choice.scss
This work folds in a local style from the Windowshop/Enroll app where small checkbox icons weren't displaying correctly. 
It turned out that app's CSS reseat included a `box-sizing: initial` for all elements, (`*, *::before, *::after { box-sizing: initial; }`) that was breaking the layout of our CSS. They fixed it by adding a local `box-sizing: content-box` to the checkbox styles. I migrated this style into our design system.
While testing this change, I discovered another bug:
Small checkboxes increase in size on focus. After playing around with the style causing this, I was able to determine we could safely remove the offending CSS. Tested in Chrome, Firefox, and Safari and removing this style had no impact on any checkboxes in our design system.
Run Storybook locally and navigate to: …
> [WNMGDS-1855] Add box-sizing rule. Remove focus sizing styles - unneeded.

- packages/docs/content/components/alert.mdx
- packages/docs/content/components/badge.mdx
- packages/docs/content/components/button.mdx
- packages/docs/content/components/checkbox.mdx
- packages/docs/content/components/form-label.mdx
- packages/docs/content/components/radio.mdx
- packages/docs/package.json
- packages/docs/src/components/content/ContentRenderer.tsx
- packages/docs/src/components/content/PropTable.tsx
- packages/docs/src/components/content/PropTableHtmlElementRow.tsx
- packages/docs/src/styles/components/propTable.scss
- packages/docs/src/styles/components/syntaxHighlighting.scss
- packages/docs/src/styles/index.scss
- yarn.lock
https://jira.cms.gov/browse/WNMGDS-2009
If the component we're documenting passes extra props through to an HTML element, we want to include documentation about that. Rather than listing out all the additional attributes for those HTML elements in our props table, I figured we could add some explanatory text with MDN documentation links to the bottom of our props table [like Primer does](https://primer.style/react/Button#props).
- Adds a `PropsTableHtmlElementRow` component
- Modifies `PropsTable` to accept `children`, which it renders at the bottom
`yarn start` and visit one of the updated pages
1. I figured putting that information in the table would be helpful to people who use screen readers, but is there a better way?
2. Ideas for a better way to explain this?
> [WNMGDS-2009] Document pass-through props

- README.md
- As reported in #2232 
- Fixes broken link in repo README.md
> [NO-TICKET] fixes link in README to yarn install

- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/styles/components/_Dialog.scss
https://jira.cms.gov/browse/WNMGDS-2094
- The fix is setting a `left: 0` and `right: 0` on the body to make it fill the whole width of the screen when `position: fixed`, which makes an assumption about how the application wants its body element to be laid out
- Because that assumption could be wrong in some applications, we wanted to make it easy to override the behavior in applications, so we the body styles with a new CSS class
1. Start storybook and navigate to http://localhost:6006/?path=/story/components-dialog--prevent-scroll-example
2. Find the `id="root"` element in the story iframe, and apply a `class="ds-l-container"` to mimic the layout of a standard application.
3. Click the button to open the dialog. In this branch, there should be no shift of the content. On the main branch, …
> [WNMGDS-2094] Fix centered containers shifting left when dialog opens

- packages/docs/content/blog/index.mdx
- Fixes a link to the maturity checklist documentation, which pointed to a branch that no longer exists
1. `yarn start`
2. Go to http://localhost:8000/blog
> [NO-TICKET] Fix a bad link in our 5.0 blog article

- packages/design-system/src/styles/settings/mixins/_layout.scss
https://jira.cms.gov/browse/WNMGDS-2122
Amid some delinting changes, we accidentally introduced [some Sass code](https://github.com/CMSgov/design-system/commit/f209b1611e94205e0bf83bcd2bf0930b1f373f83#diff-b18f80412afbfbae4bd03e27ba4b4df438eaa1a8874560b8d0d59855bfde619c) that [isn’t supported by LibSass](https://sass-lang.com/documentation/modules/math). Reverts use of `sass:math` only in the `release/5.0` branch.
> [WNMGDS-2122] Revert use of sass:math to restore support for LibSass in 5.0

- packages/design-system/src/components/DateField/SingleInputDateField.stories.jsx
- packages/design-system/src/components/MonthPicker/MonthPicker.stories.jsx
- packages/design-system/src/components/Review/Review.stories.jsx
- packages/design-system/src/components/Spinner/Spinner.stories.jsx
- packages/design-system/src/components/VerticalNav/VerticalNav.stories.jsx
- Was getting a bunch of warnings in storybook about `defaultProps` deprecation so figured I'd clean it up
- Removes `defaultProps` in any stories which use them, instead setting them manually with `args`
**Information on the deprecation here:**
[https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#no-longer-inferring-default-values-of-args
)
1. `yarn clean && yarn install && yarn storybook`
2. Shouldn't see any more warnings about this deprecation
> [NO-TICKET] getting rid of defaultProps in stories

- packages/design-system/src/components/i18n.test.ts
- packages/design-system/src/components/i18n.ts
https://jira.cms.gov/browse/WNMGDS-2135
Fixes bug where language is detected and stored with its full [Unicode BCP 47 locale identifier](https://www.unicode.org/reports/tr35/#Canonical_Unicode_Locale_Identifiers) instead of only the language tag, which our `i18n` module expects elsewhere.
I modified the `examples/cdn` example to test this. I changed the HTML `lang` attribute to `en-US` and to `es-US`. I added the healthcare.gov header and witnessed the bug using the code from `main` and then saw it fixed when switching to a bundle built from this branch.
> [WNMGDS-2135] Fix language detection bug

- packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.tsx
- packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.tsx
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
- packages/ds-healthcare-gov/src/components/Footer/index.ts
- Exporting the `PrivacySettingsLink` component so it can be consumed alone, outside of its usage in the footer.
- https://jira.cms.gov/browse/LHDM-1387
For testing, I'd mostly done so in the consuming application to ensure the changes would work for my use case. However, the `PrivacySettingsLink` component should be able to be added in any other storybook component instance and work on its own.
> [LHDM-1387] Expose Privacy Settings Modal for standalone usage

- package.json
- Combines some build commands so someone can get started with just `yarn build && yarn start`
- `yarn build` builds all DS packages
- Doc-building commands build storybook for docs first
- This will require a change in our CI script
> [NO-TICKET] Combine build commands

- packages/design-system/src/components/Button/Button.stories.jsx
- packages/design-system/src/styles/components/_Button.scss
https://jira.cms.gov/browse/WNMGDS-2153
- Fix `aria-disabled` button styles by qualifying the selector to only match `true` values, like `aria-disabled="true"`. Before those styles were being incorrectly applied to elements with `aria-disabled="false"`.
- Because an `aria-disabled` button can still be interacted with—unlike a `disabled` button—some interaction states like `:active:focus` were applying non-disabled styles to the button. To fix this, I increased the specificity of the disabled styles for those combinations
Fixes #2303
1. Check out [Temporarily change a story for testing](https://github.com/CMSgov/design-system/commit/35ff6b296510dfdb7783b0b6a4c09cd8906d6a5b)
2. Start storybook
3. Navigate to the "All buttons" story
4. Interact with the disabled buttons with the keyboard and …
> [WNMGDS-2153] Fix aria-disabled button styles

- packages/docs/src/components/layout/DocSiteNavigation.tsx
- packages/docs/src/styles/components/navigation.scss
WNMGDS-2150
1. Run demo docs site (or build locally if link isn't working)
2. Open the dev tools and search for "<h1" - you should only see one result
3. (Optional) Open VoiceOver and open Rotor - Headings - you should only see one heading for "1"
> [WNMGDS-2150] Refactor nav link to remove H1 tag, preserve styles

- packages/docs/content/foundation/spacing.mdx
Found a table that wasn't consistent with our other presentations of variable names
`yarn start` and visit http://localhost:8000/foundation/spacing/
> [NO-TICKET] Use code formatting for CSS variables on spacing page

- packages/docs/src/styles/index.scss
- packages/ds-healthcare-gov/src/styles/components/index.scss
- packages/ds-healthcare-gov/src/styles/index.scss
- packages/ds-medicare-gov/src/styles/components/index.scss
- packages/ds-medicare-gov/src/styles/index.scss
- Doc site wasn't adding the child systems styles where they needed to be.
- This was removed in the epic css branch and shouldn't have been
1. `yarn clean && yarn install && yarn start`
> [NO-TICKET] Adding child system scss back to doc site build

- gulpfile.js
- package.json
- packages/design-system-tokens/package.json
This will be cherry picked into the 6.0 release for another beta.
- Adds some logic to gulp build to leave the dist/scss folder alone so it doesn't clean it out during build.
- Removes extra `build:tokens` script from package.json
- Removing subdirectories as well in token dist folder in cases where subfolders may be there
1. `yarn build` - check for existence of `dist/scss` for each child system, should be there now.
> [NO-TICKET] Don't delete dist/scss folder during build

- packages/design-system/src/components/Pagination/Pagination.test.tsx
- packages/design-system/src/components/Pagination/Pagination.tsx
- packages/docs/content/components/pagination.mdx
WNMGDS-2133
Made `currentPage` a required prop, removed default value (this will undoubtedly cause issues for users - worth calling out in release notes), updated docs with change.
- View [demo site](https://cmsgov.github.io/design-system/branch/WNMGDS-2133/pagination-currentpage-bug) or build locally if demo unavailable
- Props table on docs site and Storybook should show `currentPage` as required
> [WNMGDS-2133] Make currentPage required, update docs

- packages/docs/content/getting-started/for-developers.mdx
- packages/docs/src/styles/components/syntaxHighlighting.scss
See the added note for details. This isn't really an option for some teams, but for teams that don't need it to be interpreted as Sass, it could help.
> [NO-TICKET] Add some notes about importing css to dev docs

- examples/create-react-app-typescript/README.md
Cleans up and updates the `examples/create-react-app-typescript` readme. The docs links were outdated. Moved the getting-started section to be consistent with our other examples and put the more important information first.
> [NO-TICKET] Clean up the `examples/create-react-app-typescript` readme

- packages/docs/content/foundation/theme-colors.mdx
- Focus color swatches had the wrong token name
> [NO-TICKET] Focus colors in theme color list had incorrect identifier

- .storybook/preview.js
- .storybook/static/cmsgov-theme.css
- packages/design-system-tokens/src/copy_themes.sh
- packages/docs/src/components/content/ThemeContent.tsx
- packages/docs/src/components/layout/ThemeSwitcher.tsx
- packages/docs/static/themes/cmsgov-theme.css
- themes.json
https://jira.cms.gov/browse/WNMGDS-2126
- Create a `themes.json` in the root with useful info about themes
- Use it in Storybook
- Use it in the doc site
- TO DO in a follow-up ticket: Use it in tests. I've got the code ready, but we may want to wait to take the initial visual regression reference images until the new CMS.gov theme has stabilized. Otherwise we'll be running those a lot.
> [WNMGDS-2126] Single source of truth for list of themes

- packages/docs/content/foundation/layout-grid/layout-grid.mdx
That story id didn't exist anymore, so this embedded story was broken
`yarn start` and visit http://localhost:8000/foundation/layout-grid/layout-grid/
> [NO-TICKET] Fix outdated story id on layout grid page

- packages/docs/content/layouts/overview.mdx
- Updated title to "Layouts overview" 😅
1. Run `yarn start` and visit the layout overview page and see the title reads `Layouts overview`
> [NO-TICKET ]Incorrect title on layouts overview page

- packages/design-system/src/components/flags.ts
- packages/ds-healthcare-gov/src/components/index.ts
I noticed that we don't pay attention to this flag anymore. All inline errors use the error icon. This unnecessarily complicates `ds-healthcare-gov` and adds a side-effect.
> [NO-TICKET] Remove unused flag for error icons

- packages/design-system/src/components/Pagination/Page.tsx
- packages/design-system/src/components/Pagination/Pagination.test.tsx
- packages/design-system/src/components/Pagination/Pagination.tsx
- packages/design-system/src/components/Pagination/__snapshots__/Page.test.tsx.snap
- packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/design-system/src/components/locale/en.json
- packages/design-system/src/components/locale/es.json
- packages/design-system/src/styles/components/_Pagination.scss
WNMGDS-2161
This work resolves a lot of a11y issues with Pagination:
- Page now reads `aria-current="page"`
- Added a heading for AT that announces the Pagination label + current page of total pages whenever a page changes
- Consolidated the disabled nav links (rendered as `span`) and button links to resolve issue of aria not being allowed on `span` tags
View [demo link](https://cmsgov.github.io/design-system/branch/WNMGDS-2161/compact-pagination/components/pagination/?theme=core) or run locally, navigate using Mac VO (for all 3 Pagination examples)
- [Default Pagination example](https://cmsgov.github.io/design-system/branch/WNMGDS-2161/compact-pagination/storybook/iframe.html?globals=theme:core&id=components-pagination--default&viewMode=story)
- [Hidden nav …
> [WNMGDS-2161] Compact pagination

- package.json
- Add `test:browser:smoke` command to quickly run a subset of tests only in Chrome
- Switch `test:browser:all` and `test:browser` (we thought this would require a Jenkins script update, but we actually don't 'use these commands directly on Jenkins)
> [NO-TICKET] Add local `test:browser:smoke` command

- .storybook/static/core-theme.css
- .storybook/static/healthcare-theme.css
- packages/design-system-tokens/src/themes/cmsgov-component.ts
- packages/design-system-tokens/src/themes/core-component.ts
- packages/design-system-tokens/src/themes/healthcare-component.ts
- packages/design-system/src/styles/core-theme.css
- packages/docs/static/themes/core-theme.css
- packages/docs/static/themes/healthcare-theme.css
- packages/ds-healthcare-gov/src/styles/healthcare-theme.css
https://jira.cms.gov/browse/WNMGDS-2235
Reverts earlier color change (https://github.com/CMSgov/design-system/pull/2384) after rethinking the role of the footer. I had originally changed this from `secondary` to `primary` when `secondary` colors moved into `info` because I thought a primary background would be more appropriate for the brand. However, this might have been an unnecessary color change for the component, especially considering that the footer may actually be used in an informational role, like an info alert. I'm not sure if that's true, but I'm proposing we don't actually change this value if we haven't figured out what our alternative background color palette looks like yet.
> [WNMGDS-2235] Revert to using `info` color in drawer footers

- packages/design-system/src/components/TextField/Mask.test.interaction.ts
- Updates mask interaction test to add slight delay during `elem.type` which ensures 3 characters are typed
- Occasionally only two characters were being typed before this.
1. `yarn clean && yarn install && yarn build && yarn test:browser:all`
> [NO-TICKET] Mask interaction test update

- package.json
- scripts/notes.ts
- themes.json
- yarn.lock
- Now skips over `.incomplete` themes
- Added cases for `internal` and `documentation`
- Updated prompt tooling, `node:readline` is a nightmare, `readline-sync` is perfect.
- Added list of milestones to choose from
- Fixed some internal logic
- Added edge case for when a ticket is labeled `[WNMGDS-2222][WNMGDS-3333]` which probably shouldn't be a thing but I ran into two of them.
- Added an `Impacts: Internal` label
- Fixed milestones not working when they had spaces in the name
1. `yarn clean && yarn install && yarn build && yarn release:notes`
> [WNMGDS-2253] Updates to release note generation script

- examples/create-react-app-typescript/src/components/Examples/UsaBannerExample.tsx
- Remove the use of the `locale` prop that is now deprecated
> [NO-TICKET] Remove use of deprecated prop in example

- packages/docs/content/components/button.mdx
WNMGDS-2231
Update Button docs to include verbiage defined in ticket. 
- I included this text within the Usage section because it felt most appropriate. 
- I also removed some previous guidance as it somewhat duplicated the new guidance.
- I removed guidance about styling the disabled buttons as I believe it was to ensure the disabled class was being applied to disabled button links. Because we're styling `aria-disabled` as a disabled button, we're using this attribute to enforce styling; this attribute is documented as required for a disabled button link in the Accessibility section. 
- I added more context around disabled link buttons and how to make them properly disabled.
To test, visit [preview link](https://cmsgov.github.io/design-system/branch/WNMGDS-2231/update-disabled-button-guid …
> [WNMGDS-2231] Update Button docs

- package.json
- scripts/build-cdn-indexes.ts
- Adds a script to build `index.html` files in the `dist` folders during build utilizing the latest version data from each child systems `package.json`
- Since this will only be updated live when we publish with jenkins, the versions will be up to date and correct/different.
- This is 1/3rd of this total ticket, the other 2/3rd's have been pushed live at [design.cms.gov/cdn](https://design.cms.gov/cdn) for browsing.
- @pwolfert I think the jenkins work needs another ticket, to keep it organized. I can create it. The only jenkins work that needs done is ensuring the `version/index.html` file is copied and the main `cdn/index.html` is updated with latest versions after a successful publish. Or maybe not another ticket, I'll be working on it, shouldn't bee too difficult, I've tested the main …
> [WNMGDS-2040] CDN Index build script

- packages/docs/src/components/layout/DocSiteNavigation.tsx
- packages/docs/src/styles/components/navigation.scss
- packages/docs/src/styles/components/themeSwitcher.scss
- packages/docs/src/styles/index.scss
- Updated side nav background to gray-lightest to fix a11y contrast issues for links
- Updated top of side nav to use brand primary color for accent and use white text color 
1. run the doc site with `yarn start` see that their ar no longer color contrast issues with the left navigtaion
> [WNMGDS-2262] Improve side nav a11y

- .storybook/static/cmsgov-theme.css
- .storybook/static/core-theme.css
- .storybook/static/healthcare-theme.css
- .storybook/static/medicare-theme.css
- packages/design-system-tokens/src/themes/cmsgov.ts
- packages/design-system-tokens/src/themes/core.ts
- packages/design-system-tokens/src/themes/healthcare.ts
- packages/design-system-tokens/src/themes/medicare.ts
- packages/design-system/src/styles/core-theme.css
- packages/design-system/src/styles/utilities/_background-color.scss
- packages/docs/content/foundation/theme-colors.mdx
- packages/docs/content/utilities/background-color.mdx
- packages/docs/static/themes/cmsgov-theme.css
- packages/docs/static/themes/core-theme.css
- packages/docs/static/themes/healthcare-theme.css
- packages/docs/static/themes/medicare-theme.css
- packages/ds-cms-gov/src/styles/cmsgov-theme.css
- packages/ds-healthcare-gov/src/styles/healthcare-theme.css
- packages/ds-medicare-gov/src/styles/medicare-theme.css
- Added tokens for --color-accent-primary for all themes
- Updated doc site page to add color swatches for  --color-accent-primary
- Added styles for using --color-accent-primary for background colors
- **Did not** add accent color for text-color utilities at this time b/c I don't think it would be needed 
1. Run doc site with `yarn start` and visit the theme file page to see accent color content on the page
2. Then visit the background color page to see the bg color examples
> [WNMGDS-2112] Add accent colors to themes

- .storybook/static/healthcare-theme.css
- packages/design-system-tokens/src/themes/healthcare-component.ts
- packages/docs/static/themes/healthcare-theme.css
- packages/ds-healthcare-gov/src/styles/healthcare-theme.css
Change to the value of `error-light` came from [this set of changes](https://github.com/CMSgov/design-system/commit/2b903f9fd77e912c3fd68db3284b782bb9d3547c#diff-b5013a09a4d1034f1180ffac1de478528d6fb5a92156d91ed6fc717e71fc13cfR32-L34), and it introduced a contrast issue. Other themes that have the same error color values use `error-lighter` here.
1. Start storybook
2. Open http://localhost:6006/iframe.html?args=&globals=theme:healthcare&id=components-multiinputdatefield--inverted-multi-input-date-field&viewMode=story
3. Use axe-core checker to check for color contrast issues
> [NO-TICKET] Fix contrast for inverse error color in healthcare

- packages/docs/src/components/layout/ThemeSwitcher.tsx
- packages/docs/src/components/layout/VersionSwitcher.tsx
- packages/docs/src/styles/components/navigation.scss
Follow-up to https://github.com/CMSgov/design-system/pull/2474
Take the form max width off of the switchers so they don't look weird in the mobile menu on wider screens
> [WNMGDS-2291] Remove max-width for doc site theme and version switchers

- packages/design-system/src/components/Pagination/Ellipses.tsx
- packages/design-system/src/components/Pagination/Page.tsx
- packages/design-system/src/components/Pagination/Pagination.test.tsx
- packages/design-system/src/components/Pagination/Pagination.tsx
- packages/design-system/src/components/Pagination/__snapshots__/Page.test.tsx.snap
- packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
- packages/design-system/src/styles/components/_Pagination.scss
WNMGDS-2050
Pagination's list of pages gives incorrect context to screen reader users. E.g., if a page set has 15 pages the readout will still say listitem X of 7 because there are 7 &lt;li> tags on the screen.
To fix this, the solution was to remove the list markup in favor of something more generic that won't confuse SR users.
To test, visit [demo url](https://cmsgov.github.io/design-system/branch/WNMGDS-2050/pagination-page-list-fix/components/pagination/?theme=core) and confirm no list markup exists. Test with a screen reader to confirm the readout is as expected (no confusion around number of items in a list vs actual number of pages).
> [WNMGDS-2050] Pagination page list fix

- scripts/notes.ts
- Previously sorting by `tag` was wrapping numbers higher than 9 back around to the 1's, not ideal, made latest release number for healthcare 9.0.0 instead of 11.0.0-beta.1
- Sorting by `committerdate` get's the latest tag which is more in line with what we're looking for
1. try the command that is now run: `git ls-remote --tags --sort committerdate origin | grep "design-system" | tail -1`
2. or `git ls-remote --tags --sort committerdate origin | grep "ds-healthcare-gov" | tail -1`
> [NO-TICKET] Sorting tags by committerdate in release:notes

- packages/design-system/package.json
- These dependencies should be in devDependencies so to not load up package size for users of the ds
1. `yarn clean && yarn install && yarn build && yarn cmsds-migrate`, everything should work the same
> [NO-TICKET] Moving ds-scripts dependencies into devDependencies

- packages/design-system/src/components/Autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/design-system/src/components/FormLabel/useFormLabel.tsx
- packages/design-system/src/components/TextField/TextField.test.tsx
https://jira.cms.gov/browse/WNMGDS-2282
Fixes the following error coming from the use of `labelId` on `TextField`:
```
console.error
Warning: React does not recognize the `labelId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `labelid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```
Run the unit tests. There should be no console errors related to `labelId`.
> [WNMGDS-2282] Fix `labelId` leaking through `TextField` into the DOM

- packages/design-system/src/components/Dropdown/useHighlightStatusMessageFn.ts
WNMGDS-2371
If you open the dropdown without hovering/selecting a new item, you receive `Uncaught TypeError: Cannot read properties of undefined (reading 'label')`
This was resolved by wrapping the highlightItem args in an if statement to see if they exist before assigning them to a const.
> [WNMGDS-2371] Wrap highlightitem args in if statement to prevent undefined

- packages/docs/content/getting-started/for-developers.mdx
- scripts/build-cdn-indexes.ts
I thought I had updated the dev docs for the preact/web-components update, but they were still out of date.
- Remove outdated content in dev docs
- I don't think it's feasible or helpful anymore to list out all the contents of our packages
- Same with the CDN package content, and I've moved some of the details to the generated CDN index pages
- Updated the generated CDN index pages to reflect the multiple options we now have for JavaScript components
- It also links to the examples and dev docs
- Added copyable code snippets
- Started using the web components in the index pages
1. `yarn start` and view the dev docs
2. `yarn build:cdn-index` and view the page generated at `packages/design-system/dist/index.html`
> [NO-TICKET] v7 updates for dev docs

- packages/docs/src/components/layout/ThemeSwitcher.tsx
Remove the top margin from the theme switcher so there's no awkward gap
Before
After
> [NO-TICKET] Refine look of doc site switchers

- packages/docs/content/foundation/css-normalization.mdx
- Because we've run into the the list flex-direction change a couple times in our own doc site, let's make a more eye-catching note about in the docs to warn our users
- Other refinements to the _CSS Normalization_ page
http://localhost:8000/foundation/css-normalization/
> [NO-TICKET] Make the list flex-direction change more eye-catching in the docs

- packages/design-system/src/components/Icons/HhsLogo.tsx
WNMGDS-2405
Setting `ariaHidden` to false on HHS logo component. Basically, our SVG icon component hides `<description>` and `<title>` SVG tags when set to `aria-hidden="true"`. Setting it to `false` makes these elements visible, therefore showing the title text on hover.
I figure it's a safe change to make on the core HHS logo since gov't logos should be accessible.
> [WNMGDS-2405] Remove `aria-hidden` from HHS logo

- .storybook/storybookStyles.scss
A follow-up to https://github.com/CMSgov/design-system/pull/2502, this fixes a problem where the inverse stories were really tall when viewed in the component docs pages in storybook, where they aren't in iframes.
This is what it looked like before:
Go to the button docs page in storybook and scroll down to the inverse story. Also try the inverse story itself and try it out on the doc site as well.
> [NO-TICKET] Fix inverse stories being too tall

- packages/design-system/src/styles/components/_SingleInputDateField.scss
WNMGDS-2416
The calendar dialog was missing a background color, causing the background elements to appear whenever the dialog was open (overlapping text elements). I added a background color using our `--color-background-dialog` token since this is a dialog.
To test, build storybook locally and modify the SingleInputDateField story file; add several `<TextField>` components to the Default story to see the fix.
Before:
https://github.com/CMSgov/design-system/assets/5159392/4b48ff2f-9d2a-4bf8-8d8d-29787c13d2d3
After:
https://github.com/CMSgov/design-system/assets/5159392/a37899d9-2c3d-48ed-9654-7f9ad292006e
> [WNMGDS-2416] Add background color to calendar dialog

- packages/design-system/src/components/Dropdown/Dropdown.test.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
WNMGDS-2417
- Restores the connection between `className` prop and root element
- Fixes a console warning when using `inputRef`
1. Start Storybook and navigate to the Dropdown stories
2. Try adding a `className` and see that it gets applied to the dropdown container element
> [WNMGDS-2417] Fix `Dropdown` `className` prop not being applied to its container element

- packages/design-system/src/components/Tabs/Tabs.stories.tsx
- packages/design-system/src/components/Tabs/Tabs.test.tsx
- packages/design-system/src/components/Tabs/Tabs.tsx
- tests/browser/story-screenshots.test.ts
WNMGDS-2418
- Adds a `selectedId` prop to `Tabs` for using it as a controlled component\
Note that I'm marking it for the 7.0.1 release even though it's technically feature. My reasoning is that it fills in missing functionality for using it as a controlled component. In that sense, it's a fix, and it's fully backwards compatible.
1. Try the new story
2. Look at the new unit test
> [WNMGDS-2418] Add `selectedId` prop to `Tabs` for controlled behavior

- packages/design-system/src/styles/components/_Accordion.scss
No ticket for this work.
If teams have extra extra extra long text in the Accordion headers, the text center-aligns. Text should always be left-aligned.
This behavior came about because of the button CSS reset. Button text is center aligned. Accordions use buttons. Therefore, Accordion text ends up center aligned unless that style is overwritten.
> [WNMGDS-2420] Left align wrapping text in Accordion; side effect of reset CSS

- package.json
- packages/ds-cms-gov/package.json
WNMGDS-2445
- Fixes oversight where the `yarn build:cmsgov` subcommand wasn't part of `yarn build`. This was causing the publish job on Jenkins to not build that package
- Removes the `private` property that keeps `@cmsgov/ds-cms-gov` from being published to npm
> [WNMGDS-2445] Make the `ds-cms-gov` package public and publishable

- packages/design-system/src/styles/components/_Autocomplete.scss
WNMGDS-2421
- Remove unused CSS class
- Add spacing to the autocomplete message options ("Loading...", "No results")
- Apply correct color token to autocomplete message options (as original Autocomplete had)
> [WNMGDS-2421] Style autocomplete message options

- packages/design-system/src/components/Accordion/AccordionItem.tsx
- packages/ds-healthcare-gov/src/components/Accordion/Accordion.stories.tsx
- packages/ds-healthcare-gov/src/styles/components/_Accordion.scss
WNMGDS-2455
- Refactor AccordionItem to rely on defaultProps for default props - this allows theme overrides to work
- Reimplement Accordion Story for hgov theme so we can display the correct icon overrides in our docs site
> [WNMGDS-2455] Reimplement hgov accordion story, fix default props for accordionitem

- packages/docs/content/migration-guides/v7-spacing-updates.mdx
- In order to help teams out who are trying to find places where their margins have disappeared, add a note to the spacing migration guide that lists zero-margin components.
[demo](https://cmsgov.github.io/design-system/branch/pwolfert/zero-margin-notes/migration-guides/v7-spacing-updates/?theme=core)
> [NO-TICKET] Add note in v7 spacing migration guide about zero-margin components

- packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.tsx
- packages/design-system/src/components/ChoiceList/__snapshots__/ChoiceList.test.tsx.snap
- packages/design-system/src/components/DateField/DateInput.tsx
- packages/design-system/src/components/DateField/__snapshots__/MultiInputDateField.test.tsx.snap
- packages/design-system/src/components/FormLabel/useFormLabel.tsx
- packages/design-system/src/components/MonthPicker/MonthPicker.test.tsx
- packages/design-system/src/components/MonthPicker/MonthPicker.tsx
- packages/design-system/src/components/MonthPicker/__snapshots__/MonthPicker.test.tsx.snap
We've gone back and forth on this a bit, but the latest advice we've gotten from an assistive tech user and accessibility expert is to place them on the fieldsets despite the issues with JAWS. Notes:
- Remove the  `aria-describedby` (for error and hint text) of each input. The `aria-describedby` on each input was way too verbose
- It won’t read out for all JAWS users but still will have a benefit for a lot of users. Just allow the aria-live on error messaging to do it’s job (when user submits) with the error. And the backup is that we’ll have the  `aria-describedby` on fieldset
This version of the change has been tested a couple times, but specifically the components we're testing are `ChoiceList`, `MonthPicker`, and `MultiInputDateField`.
[demo …
> [NO-TICKET] Move `aria-describedby` back to fieldsets

- packages/design-system/src/components/Tabs/TabPanel.tsx
- Adding `ReactNode` to `tab` prop on `TabPanel` component to allow providing markup as a tab title
- https://jira.cms.gov/browse/LHDM-1932 
1. `yarn storybook`
2. Provide jsx markup on the `tab` prop in [the Tabs stories](https://github.com/CMSgov/design-system/blob/679393310324b8f4fd46b843e350888efb8cfaef/packages/design-system/src/components/Tabs/Tabs.stories.tsx#L18)
> [LHDM-1932] Add ReactNode to tab type definition for TabPanel

- packages/ds-healthcare-gov/src/components/Header/Header.tsx
Put the USA banner in healthcare Header behind a feature flag to aid in the coordinated rollout
Toggle it on and off in Storybook
> [NO-TICKET] Put the USA banner in healthcare Header behind a feature flag

- packages/design-system/src/components/Dropdown/Dropdown.tsx
- Fix reference to `selectedItem` that assumes it's not nullable. See commit message for details
I actually have no idea how to reproduce this, [but it's failing on Jenkins](https://ci.backends.cms.gov/wds/job/design-system/job/publish-docs/116/console). I thought having an empty list of options would do the trick, but our code that finds the selected option correctly logs a warning to the console.
> [NO-TICKET] Fix possibility of null reference in Dropdown

- packages/design-system/src/components/Tabs/Tabs.test.tsx
- packages/design-system/src/components/Tabs/Tabs.tsx
Users already have the ability to supply a tab (anchor) id through `tabId`, but we can make the generated fallback more standardized, and we can add unit tests.
> [WNMGDS-2369] Standardize generated ids in Tabs

- packages/docs/content/components/autocomplete.mdx
Sarah noted that we still have the forced-colors item unchecked in Autocomplete's maturity checklist on the doc site, but we're actually good there now.
> [NO-TICKET] Check the "forced colors mode" item of Autocomplete's maturity checklist

- packages/design-system/src/components/Dropdown/Dropdown.tsx
Working on the release notes for the `Autocomplete` and `Dropdown` changes and realized I needed to make some prop changes.
> [NO-TICKET] Clean up prop definitions for the release

- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/react-aria/index.js
- Fixes using a possibly null callback function, which honestly TypeScript should have caught 😕 
- Inlines a few small functions from react-aria's dependencies. The version of the package that it was resolving to for one of our downstream projects wasn't actually compatible. Since we're including the react-aria source anyway, I figured we can just simplify by inlining and avoid the issue. None of this is a long-term fix.
> [NO-TICKET] Fix dropdown errors

- packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
Several of the event handlers for TextField no longer worked because the props from `useComboBox` were overriding them. While they shouldn't really be needed, this was an unexpected change for some teams, and it broke their code.
Add props to the `TextField` in one of the `Autocomplete` stories like `onKeyDown={action('onKeyDown')}` and then check the _Actions_ tab in Storybook for a log.
> [WNMGDS-2512] Fix event handlers for Autocomplete child TextField

- packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
WNMGDS-2514
The most common way our applications use Autocomplete involves fetching asynchronous data to show in the results. After the results come back, they are passed to the Autocomplete component in an array. However, in the new implementation of Autocomplete, the internal heuristics (in `react-stately`) for determining when to open the menu determine that it shouldn't be open. This overcomes that problem by manually detecting when new items come in and that the results list should be open.
1. Check out 8e13dca0d7a90d70db7f8c39219b058b07846041 to see the problem in the default Autocomplete story
2. Check out 3abfa13115a2071f9469767d6758c82bce41c227 to see it fixed
3. To see the new unit test work, comment out the new functionality in Autocomplete and watch it fail
> [WNMGDS-2514] Fix delayed receipt of items failing to open Autocomplete results list

- packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/react-aria/index.js
This is a follow-up to https://github.com/CMSgov/design-system/pull/2694.
The first iteration of a fix to that reported issue involved utilizing a flag for `useComboBoxState` called `allowsEmptyCollection`. Looking in the source code for `react-stately` to figure out what conditions will open the results menu, we saw that that `allowsEmptyCollection` flag would [let us pass through this logic gate](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-stately/combobox/src/useComboBoxState.ts#L116-L119). The triggering event for opening the dialog is typing stuff into the text field, but if the results aren't ready at the time the triggering event is handled (because they're being fetched asynchronously and we're waiting), `react-stately` will fail to open the …
> [WNMGDS-2518] Fix additional Autocomplete open/close issues

- packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/Autocomplete/utils.tsx
- Don't clobber user-set props on textfield by undefined properties in Autocomplete
- Note that while it's possible to pass the text field's props to the `useComboBox` function, there's no guarantee that it will honor those props or pass them on or use them the way we intend.
Add a `placeholder` prop to the `TextField` in one of the Autocomplete stories and make sure it doesn't get stripped.
> [WNMGDS-2517] Fix Autocomplete stripping props from TextField unintentionally

- packages/design-system/src/components/Dropdown/Dropdown.test.interaction.ts
- packages/design-system/src/components/Dropdown/Dropdown.test.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
After much discussion, we've decided to follow Adobe Spectrum's lead in keeping the `role="combobox"` off of the dropdown buttons. The problem we were having was isolated to desktop users of VoiceOver, and it was that the selected value inside a dropdown button was read out differently than the options in the list when containing something that it deemed was a spelling error.
What we believe was happening was that when the role is `combobox`, VoiceOver thinks that it’s a text field (because that's the common combobox pattern), and it wants to warn the user that they typed something in wrong. That resulted in "Nisqually Indian Tribe (formerly the Nisqually Indian Tribe of the Nisqually Reservation" being read out as “Mispelled Nisqually Indian Tribe (formerly the Mispelled Nisqually Indian …
> [WNMGDS-2517] Remove "combobox" role from dropdown buttons

- scripts/release.ts
Follow-up to https://github.com/CMSgov/design-system/pull/2688 where somehow it included an undefined, unused import and still ran fine. It does not seem to run fine anymore.
> [NO-TICKET] Fix an undefined, unused import in the release script

- scripts/release.ts
Undoes [this mistake](https://github.com/CMSgov/design-system/pull/2688/files#diff-21f9896491d70e481e031a1c66e9ffed07592f08455bdcd4a3cecc9c63814768R57) that was leftover from a version of that change where I had to pass the tags to one of the functions. The release script crashed on our release branch after cherry-picking new commits onto it because it couldn't find the publish commit. When I committed the change, I think I had been testing on a test branch that already had a publish commit on it, which gave us a false positive.
1. Create a release
2. Undo the release
> [NO-TICKET] Fix release script trying to use the tags before we make them

- packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
- Fix the `errorMessage` control in the inverse ChoiceList story so that it can be set. Previously it was an object type
> [NO-TICKET] Allow the setting of an error message on the inverse ChoiceList story

- examples/cdn-html-css/index.html
- examples/cdn-preact/README.md
- examples/cdn-preact/copy.sh
- examples/cdn-preact/index.html
- examples/cdn-react/index.html
- examples/cdn-web-components/README.md
- examples/cdn-web-components/copy.sh
- examples/cdn-web-components/index.html
Update all the CDN examples to use the latest version of the assets
Open up all the `index.html` files (see readmes)
> [NO-TICKET] Update CDN examples to use latest DS version

- packages/design-system/src/components/DateField/SingleInputDateField.test.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.tsx
WNMGDS-2529
Sometimes there are multiple date pickers on the same page. Screen reader users need to be able to distinguish between the different calendar buttons.
- Give the calendar button more context for screen readers by describing by the label and hint
[Branch demo](https://cmsgov.github.io/design-system/branch/pwolfert/give-calendar-button-sr-context/storybook)
1. Open the [with picker](https://cmsgov.github.io/design-system/branch/pwolfert/give-calendar-button-sr-context/storybook/?path=/story/components-singleinputdatefield--with-picker) story in Storybook
2. Using a screen reader, focus on the calendar button. It should read out the label and hint after a short pause to give some extra context
> [WNMGDS-2529] Give the calendar button more context for screen readers

- README.md
- package.json
- scripts/notes.ts
- scripts/patch.ts
- scripts/utils.ts
- Moves the milestone-picking function from the notes script into a shared utility module
- Creates a new `yarn release:patch` script that will guide you through applying commits from a milestone onto your current branch (the release branch)
1. Check out the `test-release` branch, which I branched off of `release/8.0` and then merged the commits from this feature branch.
2. Run `yarn release:patch`. Note that there is only one open milestone right now, so it automatically chooses that. Also note that you don't have to actually go through with fixing all the merge conflicts; just run `git cherry-pick --abort` after you've seen that it kicks off the command successfully.
> [NO-TICKET] Add a "patch" script for automatically cherry-picking commits

- packages/design-system/src/components/Dropdown/Dropdown.test.interaction.ts
- packages/design-system/src/components/TextField/Mask.test.interaction.ts
- packages/design-system/src/components/Tooltip/Tooltip.test.interaction.ts
WNMGDS-2535
- Fixes interaction test failures when running against a Preact-built storybook, including
- `Dropdown` interaction tests
- `Tooltip` interaction tests
- `Mask` interaction tests (intermittent failures)
1. `PREACT=true yarn build:storybook`
2. `yarn test:browser:interaction`
> [WNMGDS-2535] Fix interaction tests run with Preact

- .storybook/webpack.config.js
- package.json
WNMGDS-2535
Follows up https://github.com/CMSgov/design-system/pull/2768
- Change how we evaluate the `PREACT` environment variable in Storybook so that we assume we're using Preact unless that environment variable is explicitly set to something falsey. That means `yarn storybook` will use Preact by default, and the statically built versions will too as well.
- Replaced `yarn storybook:preact` with `yarn storybook:react` that runs it in React mode instead of Preact
1. `yarn storybook` and make sure the web component stories work
2. `yarn storybook:react` and see that they don't
3. `yarn build:storybook` and serve the `storybook-static` directory from a web server like `http-server ./storybook-static` and make sure the web component stories work
> [WNMGDS-2535] Make storybook use Preact by default

- packages/docs/content/components/checkbox.mdx
The [Checkbox](https://design.cms.gov/components/checkbox/) page on the doc site was showing radio buttons for one of its examples. This fixes it so that the example is of checkboxes.
1. `yarn start`
2. Go to http://localhost:8000/components/checkbox/
3. Take a look at the "checkbox children"
> [WNMGDS-2542] Fix radio example showing on checkbox doc page

- packages/docs/content/components/autocomplete.mdx
- packages/docs/content/components/checkbox.mdx
- packages/docs/content/components/drawer.mdx
- packages/docs/content/components/dropdown.mdx
- packages/docs/content/components/icon.mdx
- packages/docs/content/components/spinner.mdx
- packages/docs/content/components/usa-banner.mdx
- packages/docs/content/foundation/layout-grid/layout-grid.mdx
- packages/docs/content/foundation/spacing.mdx
- packages/docs/content/layouts/Healthcare/one-col-page-layout.mdx
- packages/docs/content/layouts/documentation-page.mdx
- Added missing Sketch UI kit references for Core, HealthCare, and Medicare
1. Running doc site locally, may check sketch references point to their proper cloud counterpart
- [?] Selected appropriate `Type: non-breaking`
- [?] Selected appropriate `Impacts: documentation site`
> [WNMGDS-2552] Add reference links to design artboards in Sketch cloud

- packages/design-system/src/components/Dropdown/Dropdown.test.interaction.ts
- packages/design-system/src/components/Dropdown/DropdownMenuOption.tsx
- packages/design-system/src/components/Dropdown/DropdownMenuSection.tsx
- tests/unit/setupTests.js
WNMGDS-2556
If you’ve selected an option you had to scroll to reach and then use a pointer device to click the dropdown button, the menu that opens won’t be scrolled to the selected item. It's a bug in Adobe Spectrum that has already been reported (see link in code comment). This works around that issue by manually scrolling it into view.
1. Before you build anything, try out the new test to make sure it fails when the fix is not in place:
1. Check out c8bc0d4b44c990f56227cf7fadeda27c5842a479
2. Run `yarn playwright test --config tests/browser/interaction.config.ts --headed --debug --ignore-snapshots packages/design-system/src/components/Dropdown/Dropdown.test.interaction.ts` to see it in the browser and step through it if you want
2. Build storybook with the fix to make sure the test …
> [WNMGDS-2556] Fix the Dropdown not scrolling to the selected item when using pointer

- packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
WNMGDS-2557
- Restores the ability for an `Autocomplete`'s `TextField` to be disabled, which was lost in the conversion to `react-aria`
- Making the `TextField` disabled also disables the _clear search_ button so that we can't modify what's in the search field and so it does not appear in the accessibility tree as a random button without a search field
Modify the Autocomplete story render function by adding a `disabled` attribute to the `TextField`
> [WNMGDS-2557] Restore ability to disable autocompletes

- .storybook/docs/DocumentationTemplate.mdx
- .storybook/docs/HtmlElementArgs.tsx
- .storybook/docs/WebComponentDocTemplate.mdx
- package.json
- packages/design-system/src/components/Badge/Badge.stories.tsx
- packages/design-system/src/components/Button/Button.stories.tsx
- packages/design-system/src/components/ChoiceList/Choice.stories.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.stories.tsx
- packages/design-system/src/components/Dialog/Dialog.stories.tsx
- packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
- packages/design-system/src/components/Icons/icons.stories.tsx
- packages/design-system/src/components/Label/Label.stories.tsx
- packages/design-system/src/components/Table/Table.stories.tsx
- packages/design-system/src/components/TextField/TextField.stories.tsx
- packages/design-system/src/components/Tooltip/Tooltip.stories.tsx
- packages/design-system/src/components/web-components/ds-badge.stories.tsx
- packages/design-system/src/components/web-components/ds-button.stories.tsx
- packages/design-system/src/components/web-components/ds-dropdown.stories.tsx
- yarn.lock
This is a follow-up to https://github.com/CMSgov/design-system/pull/2798. Adds the actual documentation in Storybook for each of the components that have pass-through props.
Check out the component documentation in storybook
> [WNMGDS-1922] Document pass-through props in Storybook dev docs

- packages/design-system/src/styles/_base.scss
- packages/design-system/src/styles/_set-for-deprecation.scss
- packages/design-system/src/styles/typography-headings.stories.tsx
- packages/design-system/src/styles/utilities/_font-size.scss
WNMGDS-2146
- Deprecate semantic font-size class names (`ds-h1`, `ds-display`, etc.)
- Made the call to also deprecate `ds-u-font-size--small` as it's redundant and doesn't match naming convention
- Added styles to make it more obvious the lawngreen color is intention, included label as well
I deviated from the initial deprecation strategy; no longer copying over classes to be deprecated into deprecation SCSS file for two reasons:
1. Changing the location of the CSS could impact how it's rendered in the cascade, introducing more bugs somehow
2. It created a lot of unnecessary work in duplicating `@mixin` logic and other SCSS stuff
Instead, I each each class with a deprecation comment.
To test this work
1. Pull the commit ~9e5bc7c74dc2d092737f6de28ae1fa9c4ba12639~ …
> [WNMGDS-2146] Deprecate font size classes

- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.tsx
- packages/design-system/src/components/DateField/MultiInputDateField.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/FormLabel/useFormLabel.tsx
- packages/design-system/src/components/InlineError/index.ts
- packages/design-system/src/components/InlineError/useInlineError.tsx
- packages/design-system/src/components/Label/Label.stories.tsx
- packages/design-system/src/components/MonthPicker/MonthPicker.tsx
- packages/design-system/src/components/TextField/Mask.test.tsx
- packages/design-system/src/components/TextField/TextField.tsx
- packages/design-system/src/components/TextField/TextInput.test.tsx
- packages/design-system/src/components/TextField/TextInput.tsx
- packages/design-system/src/components/TextField/__snapshots__/TextField.test.tsx.snap
- packages/design-system/src/components/TextField/__snapshots__/TextInput.test.tsx.snap
- packages/design-system/src/components/flags.ts
- packages/design-system/src/components/utilities/describeField.ts
- packages/ds-healthcare-gov/src/components/index.ts
- packages/ds-healthcare-gov/src/components/web-components/index.ts
WNMGDS-2523 is about lessening the negative effects of the useFormLabel abstraction. I'm working on a feature branch that breaks `useFormLabel` up into some smaller, more focused hooks that can be mixed and matched. This is one of several pull requests to go into this feature branch.
- Creates a new `useInlineError` hook that returns...
- `topError` and `bottomError`, only one of which will have a rendered element in it based on the error positioning
- `errorId` for referencing by other elements
- `invalid` boolean for applying to whatever element needs an `aria-invalid` property
These components should be manually tested a bit, but automated tests should also cover this work.
> [WNMGDS-2523] Break some `useFormLabel` functionality into a `useInlineError` hook

- packages/design-system/src/components/ChoiceList/Choice.stories.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.tsx
- packages/design-system/src/components/DateField/MultiInputDateField.stories.tsx
- packages/design-system/src/components/DateField/MultiInputDateField.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.stories.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.tsx
- packages/design-system/src/components/Dropdown/Dropdown.stories.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/FormLabel/useFormLabel.tsx
- packages/design-system/src/components/Hint/useHint.tsx
- packages/design-system/src/components/Label/Label.test.tsx
- packages/design-system/src/components/Label/__snapshots__/Label.test.tsx.snap
- packages/design-system/src/components/MonthPicker/MonthPicker.stories.tsx
- packages/design-system/src/components/MonthPicker/MonthPicker.tsx
- packages/design-system/src/components/TextField/TextField.stories.tsx
- packages/design-system/src/components/TextField/TextField.tsx
WNMGDS-2523 is about lessening the negative effects of the useFormLabel abstraction. I'm working on a feature branch that breaks `useFormLabel` up into some smaller, more focused hooks that can be mixed and matched. This is one of several pull requests to go into this feature branch.
- Adds a `useHint` hook that will conditionally render a hint and return a `hintId` if the component props contain hint data.
These components should be manually tested a bit, but automated tests should also cover this work.
> [WNMGDS-2523] Break some `useFormLabel` functionality into a `useHint` hook

- packages/design-system/src/components/PrivacySettingsDialog/__snapshots__/PrivacySettingsTable.test.jsx.snap
- packages/design-system/src/components/Table/Table.tsx
- packages/design-system/src/components/Table/__snapshots__/Table.test.tsx.snap
- tests/browser/stories.test.ts
WNMGDS-2570
We asked our a11y experts, and they could not figure out why this explicit `role="table"` would have been added. My only hunch was that Safari was doing something weird like what it does with lists because people "overuse lists". However, our a11y experts tested it with and without the role in VoiceOver, JAWS, and NVDA and did not find any differences. I checked it in VoiceOver + Safari as well. We've decided to remove it, because causes Axe to throw errors regarding the "scrollable table" alert.
1. Go [to this story](https://design.cms.gov/storybook/iframe.html?args=&id=components-table--scrollable-table&viewMode=story)
2. Resize the screen until it’s small enough for a blue alert to show up at the top
3. Run Axe core and look at the error:
```
To solve this problem, you need …
```
> [WNMGDS-2570] Remove redundant table role to fix axe-core error

- packages/design-system/src/styles/components/_Alert.scss
In cases where a decendent element inside the alert body wants to be very wide, the body element won't properly restrict the width, as can be seen in the screenshot below, which is from https://github.com/CMSgov/design-system/commit/e36bd9cd91f7046ae61a68d03637ec3aa6dfecd5:
The fix in this branch, discovered by @zarahzachz, sets the minimum width of the `ds-c-alert__body` element to a value other than the `auto` value [that flex-box children receive by default](https://drafts.csswg.org/css-flexbox/#content-based-minimum-size).
1. Check out 916257df7
2. `yarn start`
3. Navigate to [the headings page](http://localhost:8000/foundation/typography/headings/?theme=core) and see that the code example in the alert is bounded correctly.
> [NO-TICKET] Fix alert body content flowing out of bounds

- packages/ds-medicare-gov/src/components/index.ts
In e9db1de, we removed the medicare override for the Dialog React component, but I failed to remove the import. It seems to have been a perfect storm that let it slip through to `main`:
1. On our local development machines, we still had copies of that module in `dist`
2. Storybook doesn't import the index files where this import was, so it can build with no errors in CI
3. We only build core in CI so that the child design systems can properly import the modules, though all other testing is done on the child design systems' src code
4. For some unknown reason, our linter didn't pick up on the missing import.
1. Clean out your dist folders
2. Run `yarn build`
Note that this is not in itself a breaking change, but I want it to be grouped with the original PR in the generated notes
> [WNMGDS-2578] Remove import for file we deleted in #2828

- packages/docs/content/components/button.mdx
WNMGDS-2582
I created a subsequent ticket to address inconsistencies in the component guidance. I wonder if it makes sense to move some of the guidance to be closer to the example related to it? E.g., we have guidance around icon buttons, which icons are allowed, how to handle them accessibly, etc. and I think it's far more likely users will have a better understanding of how to use that specific example if its instructions are with it, otherwise they'll have to read all the button guidance and may miss the stuff related to icons.
> [WNMGDS-2582] Add a11y docs to button

- packages/design-system/src/components/Hint/Hint.tsx
- packages/design-system/src/components/InlineError/InlineError.tsx
- packages/design-system/src/components/Label/Label.tsx
- packages/docs/content/components/hint.mdx
- packages/docs/content/components/inline-error.mdx
- packages/docs/content/components/label.mdx
- packages/docs/content/patterns/Forms/validation.mdx
- Created new doc pages for `hint` and `inline-error`
- Added doc comments for these components that will show up in Storybook
- Pulled error-message guidance from the _Form validation_ page and directed readers to go to the new _Inline error_ page
- Refined documentation across all four affected pages. (Look specifically in 78df509c610748bf6d6a5231131dec51ac3f2ee3 for details on what changed)
- Made sure users know not to put interactive elements in the label text
1. `yarn start`
> [WNMGDS-2524] Create/update docs for label, hint, and inline error

- packages/design-system/src/components/DateField/SingleInputDateField.stories.tsx
Fix the year to match the arbitrary fixed date for VRTs. As can be seen in the code comments, there's a problem here that once fixed will make this a lot better.
> [NO-TICKET] Fix failing calendar-picker test

- packages/design-system/src/components/TextField/TextField.stories.tsx
WNMGDS-2628
Avoid Storybook rendering issues by making the controlled story a bit more intelligent. The symptom I'm fixing is the flashes of an unstyled component [that Sarah discovered here](https://github.com/CMSgov/design-system/pull/2863#pullrequestreview-1802611064). Updating the actual args on every keystroke is hard for Storybook to keep up with, so we want to treat this story like other components of ours which can either be controlled or uncontrolled. The TextField itself is always controlled by our story, but whether this story is controlled by args depends on whether the user has supplied a new value of the `value` arg to this story. 
Type really fast in the controlled label-mask stories.
> [WNMGDS-2628] Fix flash of unstyled TextField story

- packages/design-system/src/styles/components/_SingleInputDateField.scss
WNMGDS-2627
We have a problem where the calendar overlay can sometimes appear behind other form elements, like dropdown. I've applied a z-index of 1 to the calendar overlay as a short-term fix.
Did some poking around and found the dropdown has a relative position applied. This is because our dropdown is a custom made element and the menu that appears when toggled open needs its own absolute positioning 😵 I wonder if we can evaluate our current UI elements to see if more modern CSS solutions can be employed to mitigate the stacking context issues? We seem to be using relative positioning a lot in our library and I imagine if we limit the usage of positioning, we can avoid these wack-a-mole scenarios. It also makes the system more resilient imo.
> [WNMGDS-2627] Add z-index to calendar

- packages/design-system/src/components/Dialog/Dialog.stories.tsx
- packages/design-system/src/components/NativeDialog/NativeDialog.tsx
It looks like between the [cancel event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/cancel_event) and the [close event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/close_event), the close event won. The `close` event has broad browser support, whereas the cancel event seems to have been abandoned. Switching the event name fixes the bug where if you press ESC after opening the dialog in [this story](https://design.cms.gov/v/8.0.5/storybook/?path=/story/components-dialog--prevent-scroll-example), you won't be able to open it again because the element remained in the DOM and the story thinks it's still open.
1. Start storybook locally
2. Open [this story](http://localhost:6006/?path=/story/components-dialog--prevent-scroll-example)
3. Click the button …
> [WNMGDS-2629] Fix bug in NativeDialog where ESC doesn't call exit handler

- packages/design-system/src/styles/components/_Dropdown.scss
WNMGDS-2614
Focus styles were added to override the select element in Firefox. Because the dropdown's been refactored to NOT be a select element, these styles are no longer applicable. In fact, they cause a fun little bug that turns the SVG inside white when focus-visible happens. What a journey! [This is the context in which it was originally added](https://github.com/CMSgov/design-system/pull/510/files#diff-be195afbb32878f98661d965a1e5565af48defe54f8a89bd585eab496d1bff7a).
> [WNMGDS-2614] Remove Firefox focus styles added in #510

- examples/create-react-app-typescript/package.json
- examples/create-react-app-typescript/src/components/App.tsx
- examples/create-react-app-typescript/src/components/Examples/MultiInputDateFieldExample.tsx
- examples/create-react-app-typescript/src/components/Examples/SingleInputDateFieldExample.tsx
In order to test a specific issue we were seeing in storybook, I updated this example project to use the latest. I also found that it did not include the newer date field and used a deprecated heading class. Adding the new date field also exposed an issue with the dropdown button bleeding through the calendar picker menu, which we'll want to address in a separate PR.
> [NO-TICKET] Update the `create-react-app-typescript` example project

- packages/design-system/src/styles/utilities/_text-color.scss
WNMGDS-2633
Add the missing `ds-u-color--gray-dark` util that we said existed [in our docs](https://design.cms.gov/utilities/text/text-color/).
The screenshots below show that the `gray-dark` color wasn't actually being applied to the `ds-u-color--gray-dark` text in the table because that utility class didn't actually exist in our CSS. It worked in the circle swatch because that was pulling directly from the token variable.
> [WNMGDS-2633] Add the missing `ds-u-color--gray-dark` util that we said existed

- packages/design-system-tokens/src/themes/cmsgov.ts
WNMGDS-2634
Designers on CMS.gov worked with the design system team and UX Leads to pick a color from the design system palette that would work better for visited links than the original one. Visited links are now `orchid-800`.
Using dev tools, you can toggle on the `:visited` state to the Typography > Links story in Storybook
> [WNMGDS-2634] Update the visited link color for the cmsgov theme

- packages/docs/content/components/idle-timeout.mdx
We must have missed this, but `IdleTimeout` doesn't have Spanish translations even though it has default English content. Unchecking that checkbox in its maturity checklist
> [NO-TICKET] Uncheck that IdleTimeout has Spanish translations

- packages/design-system/src/components/Drawer/DrawerManager.stories.tsx
- packages/design-system/src/components/Drawer/DrawerManager.test.tsx
- packages/design-system/src/components/Drawer/DrawerManager.tsx
- packages/design-system/src/components/Drawer/index.ts
- packages/docs/content/components/drawer.mdx
WNMGDS-2638
[Based on this recent RFC](https://github.com/CMSgov/design-system/discussions/2897)
Previously we held back on releasing our `DrawerManager` / `useDrawerManager` feature ([see this old RFC](https://github.com/CMSgov/design-system/discussions/1951)) because of [this focus-management bug](https://github.com/CMSgov/design-system/pull/2890). Now that the bug is fixed, we can roll this new feature out, and app teams will be able to offload some of their logic to the design system.
- Started exporting `DrawerManager` and `useDrawerManager` from our design system packages
- Updated all the documentation and made it visible
- Changed the names of the return-value properties to be general about their usage context (not just for click-handling) but more specific about being for a …
> [WNMGDS-2638] Publish the drawer manager feature

- packages/design-system/src/components/Dialog/Dialog.stories.tsx
- packages/design-system/src/components/Dialog/useDialog.test.tsx
- packages/design-system/src/components/Dialog/useDialog.ts
- tests/browser/stories.test.ts
[See RFC for the why](https://github.com/CMSgov/design-system/discussions/2897).
- Adds a new `useDialog` hook that provides an imperative interface for opening a modal dialog and waiting asynchronously for the final result of the user's interaction with the modal
There's a Storybook story and unit tests.
> [WNMGDS-2639] Add new `useDialog` hook

- packages/design-system/src/components/IdleTimeout/IdleTimeout.stories.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeout.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.tsx
- tests/browser/snapshots/storybook-docs/Docs-Components-IdleTimeout-Docs-prop-table-matches-snapshot-1.txt
Expand some `string` prop types in IdleTimeout to `ReactNode`. They don't really need to be restricted to strings.
> [NO-TICKET] Expand some `string` prop types in IdleTimeout to `ReactNode`

- packages/design-system/src/components/Drawer/Drawer.stories.tsx
- packages/design-system/src/components/PrivacySettingsDialog/PrivacySettingsDialog.stories.tsx
- packages/ds-medicare-gov/src/components/HelpDrawer/HelpDrawer.stories.tsx
- tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-PrivacySettingsDialog-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
We were mixing and matching the packages that our doc blocks were coming from. The arg tables created by using the other package were showing controls, which we don't want (see screenshot below).
Start Storybook and look at the affected doc pages.
> [NO-TICKET] Use only a single version of Storybook "doc blocks"

- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/InlineError/useInlineError.tsx
- packages/design-system/src/components/TextField/TextField.stories.tsx
- packages/design-system/src/components/config.ts
- packages/docs/content/components/config.mdx
We were getting errors downstream that strings like "bottom" weren't being accepted. We had a fix for it in 924dbfb82441c721232df3cbcfdf7d5b6037fc5e, but really I don't think we need to make this an enum, at least not right now. We don't use enums for any other prop types that are unions of different string literals, like the `variation` or `size` props.
See 0d135b2f4f201f6761963f1986c11eafa53f8e74 for the line that will cause the type to be checked.
> [NO-TICKET] Fix error placement types

- packages/docs/src/components/layout/TableOfContents.tsx
**This work just updates the component page's table of contents.** I've included screenshots comparing local and PROD for both desktop and mobile views.
Changes:
- Update the vertical spacing for the "Have ideas?" list items
- Remove left padding on the "On this page" list items
- Remove lower level headings from "On this page" list (only shows `<h2>` headings)
The only difference I see between this work and what's shown in [the mock](https://www.sketch.com/s/a90bdc60-5526-4f3d-88d0-98ac8eefea94) is the position of the ToC. The mock shows the ToC as being higher up in the page (aligned with the intro paragraph below the page's `<h1>` title/heading) whereas the current placement aligns the ToC with the beginning of the page's body content. The only reason I haven't moved it is it would …
> Update ToC to exclude lower level headings

- packages/docs/content/components/alert.mdx
- packages/docs/src/components/content/ContentRenderer.tsx
- packages/docs/src/components/content/DesignResourceLink.tsx
- packages/docs/src/components/content/SeeStorybookForGuidance.tsx
- packages/docs/src/components/page-templates/InfoPage.tsx
~This one annoyed me - couldn't get access to `frontmatter` and instead of continuing to bang my head into my keyboard, I hardcoded the Sketch links until I can come up with a better solution.~
Figured it out and I kinda hate it, but it works. 
I needed to pass an extra optional prop to the ContentRenderer because our InfoPage components only pass the `body` data through the ContentRenderer and frontmatter isn't accessible via this query. For a component within the InfoPage to access `frontmatter`, it also needed to be passed down to the ContentRenderer, but ContentRenderer's `data` prop wouldn't allow multiple values without reworking a bunch of TS (ugh). Simple solution was to create an optional `frontmatter` prop on ContentRenderer that allows this info to pass through.
> [NO TICKET] Create design resource link

- packages/design-system/src/components/ChoiceList/Choice.tsx
Fixes the visual regression in #2893 where `Choice` error messages saw a slight vertical shift when viewed in the healthcare theme. The HealthCare.gov Design System sets all field errors to bottom-placement by default. When I started using the `useInlineError` hook in the `Choice` component, it began applying a bottom-placement CSS class that was causing the shift. We separated these hooks out of the one giant `useFormLabel` hook for this very reason—so that we could mix and match which features we want to use in each component. I simply stopped using that hook, because we don't need its placement logic. We can just use the `InlineError` component directly for this simpler case.
- I ran the full suite of visual regression tests
- You can use Storybook to make sure there's no vertical …
> [NO-TICKET] Fix the visual regression in #2893

- packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
- packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.tsx
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
WNMGDS-2511
- Replace `h4` with `p` tag in hgov footer
- Why? The current markup uses `h4` and it sometimes causes issues with the heading structure when `h2` or `h3` aren't used. This tag doesn't need to be a heading at all and only exists as a label for the list of language resources, so it's been replaced with a `p`
- This needs to be an `aria-labelledby` to take advantage of browser translation features
- ~Add `aria-label="global"` to hgov footer~
- ~This wasn't part of the original ticket, but hgov's footer should _probably_ have an `aria-label` to indicate it's the global footer for the site. I mirrored the same label used on hgov's header~
- Footer doesn't need a label because it's the only element of its kind on a page ([source](https://adhoc.slack.com/archives/C049H6KSE6Q/p1707495 …
> [WNMGDS-2511] Update hgov footer html

- packages/docs/src/components/layout/SideNav/SideNav.tsx
- packages/docs/src/styles/components/navigation.scss
WNMGDS-2350
I thought we needed to refactor our vertical nav CSS due to how complex the docs site CSS overrides were, but I was wrong and the solution turned out to be much simpler 🎉 
- Removed clever CSS in favor of redefining vertical nav token in docs site
- Removed unnecessary util classes from docs header
- Fixed `:hover:focus` state of hamburger icon
> [WNMGDS-2350] Fix background color of docs vertical nav on hover

- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
- packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/PrivacySettingsLink.test.tsx.snap
WNMGDS-2681
Fixed an id in Dialog that was static and caused duplicates now that we can actually render multiple dialog elements to the DOM at once without showing them after the recent API change to `Dialog`.
> [WNMGDS-2681] Fix instance of static id in Dialogs

- packages/design-system/src/components/Accordion/AccordionItem.test.tsx
- packages/design-system/src/components/Accordion/AccordionItem.tsx
- packages/design-system/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/design-system/src/components/Accordion/__snapshots__/AccordionItem.test.tsx.snap
- packages/design-system/src/components/locale/en.json
- packages/design-system/src/components/locale/es.json
Icons used in AccordionItem are decorative and the button uses `aria-expand` to announce if the button's open or not, so removing the SVG title and associated i18n text.
> [NO-TICKET] Make accordion SVG hidden to AT users

- packages/design-system/package.json
WNMGDS-2656
Make `case-it` a direct dependency. This dependency is actually a true dependency of our web components. If we don't move it, web component builds fail for downstream projects.
> [WNMGDS-2656] Make `case-it` a direct dependency

- packages/design-system/src/components/PrivacySettingsDialog/privacySettings.ts
Don't actually throw errors when privacy settings cookie doesn't exist. Because our privacy settings dialogs can exist in non-production environments where Tealium may or may not be loaded, throwing an error can be unnecessarily disruptive. Developers should be able to pick up on logged console errors as well.
While we normally like to fail fast so issues can be discovered, there's evidence that suggests a possible race condition for Tealium loading and this component rendering among existing applications. Because this code has also recently been updated to never _set_ the cookie unless the user takes explicit action, returning default settings here does not run the risk of accidentally setting cookie values unnecessarily when Tealium hasn't finished loading.
1. In an incognito window, …
> [WNMGDS- 2685] Privacy settings to no longer throw error when no cookie exists

- packages/docs/src/components/content/ColorExampleList.tsx
- packages/docs/src/helpers/clientOnly.ts
- yarn.lock
A while back, we identified an architectural problem that resulted in [bugs like this](https://github.com/CMSgov/design-system/pull/2752). The problem is that design-system theming introduces dynamic information into our statically-built site. We have one copy of each page, but each page can be viewed from the context of one of four design-system themes. Different themes show different content in some pages—different guidance, different descriptions, different examples, etc. Since we only build one HTML file for each page, we build as if we're viewing it in the _core_ theme, but the HTML spat out for the _core_ theme doesn't necessarily match 1-1 with the HTML for every other theme. When the client-side JavaScript loads, React renders the page with the actual current theme and then tries …
> [WNMGDS-2675] Show accurate colors in theme-colors page

- packages/design-system/src/components/Accordion/AccordionItem.test.tsx
- packages/design-system/src/components/Accordion/AccordionItem.tsx
- packages/design-system/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- packages/design-system/src/components/Accordion/__snapshots__/AccordionItem.test.tsx.snap
WNMGDS-2686
Remove `aria-labelledby` from AccordionItem. This attr is on a `div`, which has the default role of generic and generics cannot accept aria labels as part of the spec. This label is also just not needed. More details in [this Slack thread](https://cmsgov.slack.com/archives/CHH0381RD/p1708710668265149).
> [WNMGDS-2686] remove aria-labelledby from accordion; not needed

- packages/design-system/src/components/Pagination/Pagination.tsx
- packages/design-system/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap
WNMGDS-2696
Remove live region attributes from Pagination; the component isn't dynamic (would trigger a page reload given it uses links to navigate to different urls) and is a `nav` element (users would understand interacting with it would result in a page change).
I think we added these attrs because Storybook's example _is_ dynamic.
[Link to the Slack discussion here](https://cmsgov.slack.com/archives/CHH0381RD/p1709914079761229).
> [WNMGDS-2696] remove live region attrs from Pagination

- package.json
- packages/design-system-tokens/package.json
- packages/ds-healthcare-gov/package.json
- yarn.lock
- Used `npx depcheck` to identify candidates for removal in repo
- Did a cross search within repo to see if packages were being used internally
- Discovered the following packages were unused and not referenced anywhere, but appear to be dependencies of Storybook (some Stories broke without these packages) so I didn't remove them:
- "@babel/helper-string-parser": "^7.19.4"
- "@babel/plugin-proposal-decorators": "^7.21.0"
- "@babel/plugin-proposal-export-default-from": "^7.18.10"
- "@babel/register": "^7.8.4"
Ran the following commands without error and spot checked docs and Storybook to see everything worked A-OK
1. `yarn clean && yarn install`
2. `yarn build && yarn build:storybook && yarn build:storybook:docs && yarn build:docs && yarn build:examples`
3. `yarn test`
4. `yarn …
> [WNMGDS-2704] Remove unused packages

- packages/design-system/scripts/cmsds-migrate/configs/deprecated-semantic-typography-classes.mjs
A long, long time ago, we replaced typography classes tied to semantic heading levels with class names that were independent of heading levels. Later on, we added [a migration guide](https://design.cms.gov/migration-guides/agnostic-typography-classes/) to help folks make the change in their code. We still found they were in use, so in #2801 we finally officially deprecated them now that we have a method of warning people of deprecated CSS. In #2982, we removed the deprecated classes, but I'm not convinced we won't leave some stragglers behind. Therefore, I've added a migration script people can run to update their classes once and for all.
1. Add one of the old classes somewhere in the core package
2. Run `yarn cmsds-migrate` from the core package root and select the option about …
> [NO-TICKET] Add a migration script for the old to new typography classes

- examples/astro/package.json
- examples/preact-app/package.json
- examples/preact-react-app/package.json
- examples/react-app/package.json
- Make the new example package private so it doesn't mess up the release
- Make all the example version numbers match core to make things simpler
> [NO-TICKET] Make new example package private

- scripts/release.ts
This recent lerna config change was incorrect, so revert it. If we ignore all private packages during the bump, we're actually failing to bump the version of the design system packages in the dependencies for those private packages, which means that the doc site won't get the new version of the design system, and neither will the examples. I guess the tradeoff is that we have to choose an option for those private packages while we're going through the bump workflow.
> [NO-TICKET] Fix release script not bumping versions in private packages

- scripts/release.ts
https://github.com/CMSgov/design-system/pull/2987 fixed one problem but created another 😅. Including the private packages in the bump also included them in Lerna's publish commit message, like so:
```
Publish
- astro-example@10.0.0-beta.1
- preact-app-example@10.0.0-beta.1
- preact-react-app-example@10.0.0-beta.1
- react-app-example@10.0.0-beta.1
- @cmsgov/design-system@10.0.0-beta.1
- @cmsgov/cms-design-system-docs@10.0.0-beta.1
- @cmsgov/ds-cms-gov@10.0.0-beta.1
- @cmsgov/ds-healthcare-gov@14.0.0-beta.1
- @cmsgov/ds-medicare-gov@12.0.0-beta.1
```
Our release script parsed this message to get the git tags to create, but it didn't take into account package names that don't start with `@cmsgov`.
Along with fixing the regex pattern so it doesn't break the release script, I made it only …
> [NO-TICKET] Fix release tagging with private packages

- packages/docs/src/components/layout/Layout.tsx
- packages/docs/src/components/page-templates/BlogPage.tsx
Fix headings on blog posts not getting any heading styles
1. Run the doc site locally and look at one of the blog posts
> [NO-TICKET] Fix headings on blog posts not getting any heading styles

- scripts/browser-tests.ts
- scripts/utils.ts
Don't pass the browser tests when they fail!
1. Mess up the Alert styles
2. `yarn test:browser --grep "Alert"
3. Did it fail?
> [NO-TICKET] Don't pass the browser tests when they fail!

- packages/design-system/src/components/web-components/ds-alert/ds-alert.stories.tsx
- packages/design-system/src/components/web-components/ds-badge/ds-badge.stories.tsx
- packages/design-system/src/components/web-components/ds-button/ds-button.stories.tsx
- packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
- packages/design-system/src/components/web-components/ds-usa-banner/ds-usa-banner.stories.tsx
- packages/design-system/src/components/web-components/storybook.tsx
In order for updates made to web components by React to correctly re-render the component, we've had to force React to re-render the component whenever the args change by adding a `key` prop. This is unnecessary boilerplate code for each story, and we want to also expand the functionality to take into account changes to global Storybook variables like our theme variable, so I've codified it into a Storybook _decorator_ that can be reused in each web-component Story.
What doesn't seem to work is changing language. I haven't figured out why.
Play with the web component stories and change props and themes.
> [NO-TICKET] Fix changing themes in web component stories

- packages/design-system/src/styles/components/_Dialog.scss
- packages/design-system/src/styles/components/_Drawer.scss
Protect a dialog's width and font size from inheriting from ancestors. Fix drawers too, which had the same problem.
1. Open up a story with a dialog
2. Manually set the font size of the story div (dialog's ancestor) to have a really large or really small font size
3. Without this fix, the dialog will grow really wide or really narrow and the internal font sizes will be affected. With this fix, those two things should remain unaffected.
> [WNMGDS-2745] Fix dialogs inheriting font size from ancestors

- packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
- packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.test.tsx
- packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.tsx
- tests/browser/snapshots/storybook-docs/Docs-Web-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
Add missing `inversed` attribute to `ds-dropdown`
> [NO-TICKET] Add missing `inversed` attribute to `ds-dropdown`

- packages/design-system/src/components/web-components/preactement/define.ts
- packages/design-system/src/components/web-components/preactement/shared/element.ts
- packages/design-system/src/components/web-components/preactement/shared/model.ts
Refactors local preactement code for clarity, readability, and conciseness. My intention was to make no functional changes except that it now throws an error if you give it an invalid custom element name. The next step will be to make actual changes to hopefully fix the odd behavior when nesting custom elements.
- Renames several functions to be clearer about what they do
- Consolidates and separates some functions
- Adds documentation comments to all functions in the `define` module
- Removes code duplication in the function that defines the custom element class and constructor
1. Run the unit tests
2. Look for regressions in the Storybook stories
3. Look for regressions in the Astro example
It's helpful to use the [split diff view](https://github.com/CMSgov/design-system/pull/3048/files? …
> [WNMGDS-2759] Refactor local preactement code

- .storybook/preview.tsx
- packages/design-system/src/components/config.ts
- packages/ds-healthcare-gov/src/components/Footer/Footer.test.tsx
- packages/ds-healthcare-gov/src/components/Footer/Footer.tsx
- packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.test.tsx
- packages/ds-healthcare-gov/src/components/Footer/InlineLinkLists.tsx
- packages/ds-healthcare-gov/src/components/Footer/Logo.tsx
- packages/ds-healthcare-gov/src/components/Footer/LogosRow.test.tsx
- packages/ds-healthcare-gov/src/components/Footer/LogosRow.tsx
- packages/ds-healthcare-gov/src/components/Footer/PrivacySettingsLink.tsx
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/Footer.test.tsx.snap
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/InlineLinkLists.test.tsx.snap
- packages/ds-healthcare-gov/src/components/Footer/__snapshots__/LogosRow.test.tsx.snap
- packages/ds-healthcare-gov/src/components/Footer/analytics.ts
- Adds analytics to all footer links when the new `footerSendsAnalytics` config property is true (`true` by default for healthcare)
Storybook testing is somewhat tricky because you have to be able to prevent default navigation. There are unit tests, though.
> [WNMGDS-2715] Add analytics to healthcare footer links

- webpack.config.js
This is a follow-up to https://github.com/CMSgov/design-system/pull/3070 to make it backwards compatible so we can include it in a feature release.
> [WNMGDS-2744] Make the web components bundle split backwards compatible

- .storybook/preview.tsx
- packages/docs/src/components/layout/Layout.tsx
In order to test analytics with the analytics team before new analytics features get released, we were thinking we'd enable analytics for specific components on the doc site, which already sends analytics. However, this would require that we make specific test pages for features we're trying to test. If we add it to Storybook, we have all our components already available to test. Therefore I'm adding a new config option to be able to choose live analytics for validating the actual events sent to our analytics provider. This can be run either locally or on a deployed copy.
Select the new analytics config option and try out one of the analytics-enabled components.
Also try turning it off and on again and switching between the different options.
> [NO-TICKET] Add live-analytics option to Storybook

- .storybook/docs/WebComponentDocTemplate.mdx
- .storybook/docs/WebComponentEventsTable.tsx
- .storybook/docs/WebComponentSlotsTable.tsx
- packages/design-system/src/components/web-components/ds-choice/ds-choice.stories.tsx
- Adds a new `WebComponentSlotsTable` to Storybook
- Uses it in the `ds-choice` docs to explain slots generally and list the two slots
Look at the storybook docs for `ds-choice`.
> [NO-TICKET] Add documentation for web component slots

- packages/design-system/src/components/web-components/preactement/define.test.tsx
- packages/design-system/src/components/web-components/preactement/define.ts
- Fix regression from aa6ef9e where I lost the default `event.detail.target`
- Test for it
1. Run the tests
2. Look at the actions in Storybook. To get the true details, you might have to console log the `event.details.target` in a story's event handler.
> [NO-TICKET] Fix web component custom events missing the default `event.detail.target`

- packages/design-system/src/components/DateField/CustomDayPicker.tsx
- packages/design-system/src/components/DateField/CustomDayPickerDayContent.tsx
Restores screen-reader context lost in [react-day-picker pull request #1537](https://github.com/gpbl/react-day-picker/pull/1537/files). That change was originally made [to fix an issue with Google Translate](https://github.com/gpbl/react-day-picker/issues/1490); however, the component is still pretty broken with Google Translate running even with that fix; therefore, we don't gain anything by accepting it, and we lose screen-reader context when we do.
In the `main` branch, you'll find that each day button just has the number as its inner HTML content. With this fix, there are two spans inside, and screen readers get more information.
> [WNMGDS-2775] Restore additional screen-reader context for calendar-picker days

- packages/design-system/src/components/DateField/MultiInputDateField.test.tsx
- packages/design-system/src/components/DateField/MultiInputDateField.tsx
Fixes the `MultiInputDateField` overwriting a subset of user-supplied props with defaults.
> [WNMGDS-2790] Fix the `MultiInputDateField` overwriting some props with defaults

- packages/design-system/src/styles/components/_UsaBanner.scss
WNMGDS-2784
UsaBanner had a style using `justify-content: end` and another team was receiving a support warning for it. [This style is widely supported](https://caniuse.com/?search=justify-content%3A%20end), but I think the team supports an older browser or something. Regardless, [because the element this style's applied to has a `display: flex`](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#flex-end) also applied, changing this to `flex-end` seemed appropriate.
> [WNMGDS-2784] Change end to flex-end to quiet another teams console warn

- packages/design-system/src/components/index.ts
We forgot to actually export the new `Hint` component starting in v9!
> [NO-TICKET] Add missing `Hint`-component export

- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/design-system/src/styles/components/_Dropdown.scss
WNMGDS-2779
Replacing visible `<label>` on Dropdown with a `<div>` (I know the ticket said to use a `<span>`, but `<div>` is already a block level element and I didn't want to add the extra style to make `<span>` do that).
Aside from some markup changes, there should be no visual/functional change in this component.
> [WNMGDS-2779] Replace dropdown label with div

- packages/design-system-tokens/src/css/translate.ts
- packages/design-system-tokens/src/figma/translateFigmaToTokens.ts
- packages/design-system-tokens/src/figma/translateTokensToFigma.ts
- packages/design-system-tokens/src/lib/tokens.ts
- packages/design-system-tokens/src/tokens/System.Value.json
This is one of several PRs for [WNMGDS-2785](https://jira.cms.gov/browse/WNMGDS-2785). Rebase after https://github.com/CMSgov/design-system/pull/3100 is merged.
- Add support for syncing font (STRING) variables down from Figma
- Add support for syncing `fontFamily` tokens up to Figma
- Add support for rendering `fontFamily` tokens to CSS
`yarn build:tokens` and take a look at the font variables inside `dist/css-vars/core-theme.css`
> [WNMGDS-2785] Add full support for font-family tokens

- .prettierignore
- packages/design-system-tokens/src/tokens/System.Value.json
- packages/design-system-tokens/src/tokens/Theme.cmsgov.json
- packages/design-system-tokens/src/tokens/Theme.core.json
- packages/design-system-tokens/src/tokens/Theme.healthcare.json
- packages/design-system-tokens/src/tokens/Theme.medicare.json
This is one of several PRs for [WNMGDS-2785](https://jira.cms.gov/browse/WNMGDS-2785). Rebase after https://github.com/CMSgov/design-system/pull/3101 is merged.
- Removes the Prettier ignore for the tokens folder and formats the token files. It was originally added to not mess up the formatting of our TypeScript tokens that we no longer have.
> [NO-TICKET] Stop ignoring token files for Prettier cleanup

- packages/design-system/src/components/Drawer/Drawer.tsx
It was introduced in [here](https://github.com/CMSgov/design-system/commit/7fee5f741b90b5599875d141a443b379fad763d1#diff-9ef68d956bbe4985a98993aa40ecbbc2f643eb437d5cbdd94cd5529587a51ac6R102) and hasn't been released yet 😅 
1. On `main`, and look at [the drawer toggle story](https://design.cms.gov/v/main/storybook/?path=/story/components-drawer--drawer-toggle-with-drawer), you'll see that once you open the drawer you can no longer interact with the toggle
2. In this branch, you should be able to interact with things on the page (even though there's no logic in the story for the toggle doing anything when you click on it if it's already open)
> [NO-TICKET] Fix bug causing drawers to always trap focus

- packages/design-system/src/styles/components/_Accordion.scss
- packages/ds-healthcare-gov/src/styles/components/_Accordion.scss
Updated Accordion with Figma changes.
- Removed the healthcare-only `--accordion-icon__size` variable
- Split `--accordion__border-radius` into the following variables to support Figma:
- `--accordion__border-bottom-left-radius`
- `--accordion__border-bottom-right-radius`
- `--accordion__border-top-left-radius`
- `--accordion__border-top-right-radius`
> [WNMGDS-2785] Updated Accordion with Figma changes

- packages/design-system-tokens/src/tokens/Theme.cmsgov.json
Fix border radii for cmsgov badges so they match production. I'm pretty sure they were given this border radius so they wouldn't get confused with the pill-shaped buttons. Hailey agrees.
> [WNMGDS-2785] Fix border radii for cmsgov badges

- packages/docs/src/helpers/themeTokens.ts
Don't print any of the boolean values on the doc site. Those boolean tokens are mostly internal and are not robust enough to set to different values. They shouldn't be shown in the docs as configuration options. This fixes build because I made the CSS value function to throw an error if we try to get the value of a boolean token.
> [NO-TICKET] Fix broken doc-site build

- packages/ds-medicare-gov/src/styles/components/_HelpDrawer.scss
We no longer have direct access to this Montserrat font variable at the theme level, so use a token that we do have and is semantically relevant.
> [WNMGDS-2785] Fix reference to system-only token that doesn't exist in theme

- packages/design-system/src/styles/components/_Drawer.scss
- packages/design-system/src/styles/components/_Dropdown.scss
- packages/docs/src/styles/components/filterDialog.scss
- packages/docs/static/themes/cmsgov-theme.css
- packages/docs/static/themes/core-theme.css
- packages/docs/static/themes/healthcare-theme.css
- packages/docs/static/themes/medicare-theme.css
Remove references to the underused and now removed z-index variables.
1. There are still a lot of VRT failures on this feature branch, but you can manually look through the failures in `playwright-report/index.html` like I did to verify that none of them are z-index related.
2. Can also double-check that I did indeed remove all of them.
3. Can also manually test the affected components in Storybook
> [WNMGDS-2785] Remove refs to z-index variables

- packages/design-system/src/components/Dialog/Dialog.test.tsx
- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Drawer/Drawer.test.tsx
- packages/design-system/src/components/Drawer/Drawer.tsx
- packages/design-system/src/components/IdleTimeout/IdleTimeoutDialog.test.tsx
- packages/design-system/src/components/NativeDialog/NativeDialog.test.tsx
- packages/design-system/src/components/NativeDialog/NativeDialog.tsx
- packages/design-system/src/components/NativeDialog/useNativeDialogAnalytics.test.tsx
- packages/docs/src/components/layout/FilterDialog/FilterDialog.tsx
- tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
In [the Release 9.0 blog post](https://design.cms.gov/blog/release-9.0/?theme=core#improving-drawers-and-dialogs "Follow link"), we announced that we were changing the way applications open and close dialogs and help drawers. [Here is a code migration guide](https://github.com/CMSgov/design-system/pull/2890 "Follow link"). We added a console warning for the old behavior in development mode, but after seeing that teams are still using the old API and running into issues, we decided it's time to increase the visibility of this change.
https://jira.cms.gov/browse/WNMGDS-2780
Implement stricter warnings when the `isOpen` prop isn't used (the new dialog API).
- Require it in TypeScript
- Up the dev warnings to throwing dev errors
- Display a console error message in prod (previously silent in …
> [WNMGDS-2780] Implement stricter warnings when the `isOpen` prop isn't used

- packages/design-system-tokens/src/tokens/Theme.cmsgov.json
- packages/design-system-tokens/src/tokens/Theme.core.json
- packages/design-system-tokens/src/tokens/Theme.healthcare.json
- packages/design-system-tokens/src/tokens/Theme.medicare.json
- packages/design-system/src/styles/components/_FilterChip.scss
- packages/docs/static/themes/cmsgov-theme.css
- packages/docs/static/themes/core-theme.css
- packages/docs/static/themes/healthcare-theme.css
- packages/docs/static/themes/medicare-theme.css
This didn't actually have the right values in Figma, but we don't need it anyway. It's the same value for each theme, so just hard-code it into the CSS. It wasn't being used in Figma.
VRTs for filter chip should all succeed
> [WNMGDS-2785] Fix filter chips by removing variable with bad value

- packages/design-system/src/components/Dropdown/Dropdown.tsx
No ticket.
`useLabelProps` spread the attr `inversed` onto the newly created label-div element (`<div>` styled as a `<label>` to skirt some Axe/Wave issues). Because the `div` doesn't have the concept of an `inversed` attr, and I'm using `classNames` to get the same effect, remove that prop from `labelProps`.
> [NO-TICKET] Remove inversed prop from label-div

- packages/design-system/src/components/Alert/Alert.tsx
- packages/design-system/src/components/Alert/__snapshots__/Alert.test.tsx.snap
- packages/design-system/src/components/web-components/ds-alert/__snapshots__/ds-alert.test.tsx.snap
WNMGDS-2800
The current Alert assigned `headingId` to the body element, which contained text for the heading, alert type and body text (aka, wall-o-text).
This update assigns `headingId` to the element containing just the heading text and alert type, making it easier for AT users to scan a given page. If no heading or icon are provided, the accessible label will default to announcing the alert type.
You can test these changes by comparing PROD and local builds, either by using VO or by opening your browser's accessibility tools to see what the label is.
Local readout:
PROD:
> [WNMGDS-2800] Refactor alert so headingId is on heading node, not alert body

- packages/docs/src/styles/pages/layout.scss
Fix regression in max-width of USA banner on doc site. For some reason a value of `initial` seems to trigger the `var()` fallback mechanism instead of just removing the max width. I guess that's how custom properties work?
Make sure the doc site's USA banner content spans the full width like the production one.
> [NO-TICKET] Fix regression in max-width of USA banner on doc site

- packages/design-system-tokens/src/tokens/Theme.cmsgov.json
- packages/design-system-tokens/src/tokens/Theme.core.json
- packages/design-system-tokens/src/tokens/Theme.healthcare.json
- packages/design-system-tokens/src/tokens/Theme.medicare.json
Removed the unused `--autocomplete*` and `--dropdown*` variables, which we didn't actually use in the CSS.
> [WNMGDS-2797] Remove the unused `--autocomplete*` and `--dropdown*` variables

- packages/design-system/src/components/Dialog/index.ts
- packages/docs/src/components/content/MaturityChecklist/MaturityChecklist.tsx
We forgot to export the new `useDialog` hook in v9, and nobody has caught it until now when I noticed I couldn't import it into the doc site.
1. Check out [01dfe21](https://github.com/CMSgov/design-system/pull/3130/commits/01dfe2158f1907c8e5b84056a5db60dae942f756)
2. Build the doc site and look at the maturity checklist on a component page. There will be a new button in there for opening a dialog, which uses the new hook
> [NO-TICKET] Export the `useDialog` hook

- packages/design-system/src/styles/components/_Dialog.scss
Fix Firefox scrolling pages to the top when a dialog opens in race condition.
On one of the apps, opening a dialog in Firefox would scroll the page to the top. We weren't able to reproduce this in our Storybook, but we could see the behavior that caused it by disabling our code that applied the body classes and properties that freeze it. The polyfill styles by themselves were causing the page to scroll to the top in Firefox. In the race condition, the page would scroll to the top before our JavaScript could poll the document to find its scroll position, so the scroll position was always zero.
We don't need these polyfill styles anymore. We have to keep the skeleton of a JavaScript polyfill around to support testing frameworks, but those don't need any CSS. The dialog element has Baseline …
> [WNMGDS-2808] Fix Firefox scrolling pages to the top when a dialog opens

- packages/design-system/src/components/Dropdown/DropdownMenuOption.tsx
WNMGDS-2809
Fixes dropdown flash caused by selection on mouseup after content shifts under cursor
To reproduce the original error:
1. Go to the Storybook docs page for Dropdown where each story is in a short iframe. That iframe restricts the height of the window to be shorter than the dropdown menu.
2. Open the first dropdown and select the last item.
3. Now if you hold down your click on the dropdown button to open the dropdown menu and then let go after the menu has opened and the page shifted under you so that what's under the cursor isn't the dropdown button anymore but one of the options, it will select that option and close the menu.
This is what I believe to be the "flash" that people are seeing. It's shifting the content out from under your cursor and then making a selection when …
> [WNMGDS-2809] Fix "dropdown flash"

- packages/design-system/src/components/ChoiceList/Choice.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.tsx
- packages/design-system/src/components/ChoiceList/__snapshots__/Choice.test.tsx.snap
- packages/design-system/src/components/MonthPicker/MonthPicker.tsx
- packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice.test.tsx.snap
- packages/design-system/src/components/web-components/preactement/parse.test.ts
- packages/docs/content/patterns/Forms/error-validation.mdx
- tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
WNMGDS-2818
Prevent errors from being nested in ChoiceList.
- Individual Choice can have an `errorMessage`
- Choices nested within ChoiceList cannot have an `errorMessage`
- If an error exists in ChoiceList, it should only be revealed by the ChoiceList's `errorMessage`, not on its children
Also added TS checks to make sure `error*` props weren't being used and a `console.warn` to gently scold if they weren't TS users and insisted on doing the bad pattern.
> [WNMGDS-2818] Prevent nested errors in choicelist

- packages/design-system/src/components/ChoiceList/Choice.tsx
- packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice.test.tsx.snap
WNMGDS-2821
Fixes all generated ids for `Choice` error messages being `undefined_error`.
1. http://localhost:6006/?path=/story/components-choice--default
2. http://localhost:6006/?path=/docs/web-components-ds-choice--docs
> [WNMGDS-2821] Fix generating error ids for individual Choices

- .storybook/cmsTheme.ts
- .storybook/preview.tsx
WNMGDS-2645
In PROD, discovered the Nunito font was being downloaded for Storybook UI. Discovered the cmsTheme file we created (I believe when Storybook was first added to this project) wasn't hooked up to style the canvas area of Storybook's UI (the area where the interactive examples were). When adding the cmsTheme to Storybook's canvas area, Nunito was removed, but other styles were introduced. Turns out we had things configured that weren't actually displaying.
Discussed this with Patrick and decided that because we weren't seeing the pre-set configuration to begin with, it's best to remove those options and just configure the things we care about (brand color, names, fonts). So I simplified this config. The only change should be the font-face used on the canvas documentation.
> [WNMGDS-2645] Remove unused storybook styles, add support for font fallbacks

- packages/docs/content/patterns/Forms/error-validation.mdx
WNMGDS-2828
Replace "Error message should never" guidance with "Avoid the following in error messages;" include "don't" language.
> [WNMGDS-2828] Update avoid error message guidance.

- packages/docs/content/components/third-party-external-link.mdx
WNMGDS-2826
Update ThirdPartyExternalLink docs to include PDF guidance.
[Demo url (building)](https://cmsgov.github.io/design-system/branch/WNMGDS-2826/update-third-party-external-link-guidance)
> [WNMGDS-2826] Update third party external link docs to include pdf guidance

- .storybook/main.ts
- package.json
- packages/design-system/src/components/Drawer/Drawer.stories.tsx
- tests/browser/snapshots/storybook-docs/Docs-Components-Button-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-ChoiceList-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-MonthPicker-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-MultiInputDateField-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-SingleInputDateField-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Table-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-TextField-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Tooltip-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Medicare-HelpDrawer-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-components-Alert-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-components-Badge-Docs-prop-table-matches-snapshot-1.txt
- tsconfig.json
- yarn.lock
- Uses the new react-docgen-typescript feature [referenced here](https://github.com/CMSgov/design-system/pull/3003#issuecomment-2239465345)
- Is a follow-up to https://github.com/CMSgov/design-system/pull/3080
1. `yarn clean && yarn install && yarn build`
2. `yarn test:browser:storybook-docs` and make sure it doesn't try to change the order of union-type members from what the snapshots show now (string-stort (somewhat alphabetical) order)
> [NO-TICKET] Use new docgen union sorting

- packages/docs/src/components/content/ContentRenderer.tsx
This is a follow-up to https://github.com/CMSgov/design-system/pull/3176, where I attempted to fix a bug and caused its equal and opposite bug. See added code comments for details.
I re-deployed [this demo](https://cmsgov.github.io/design-system/branch/pwolfert/release-11-blog-post/blog/release-11.0?theme=core) with the fix. Loading that page from the link should successfully show the image, and also navigating away through the "See other releases" link and then back using the "Release 11.0" link should show the image too. Without this fix, it would have failed to load the image in that second scenario, which was the opposite of what it was before the first fix.
> [NO-TICKET] Fix the bug caused by the first fix to Gatsby image paths

- packages/design-system/src/components/DateField/SingleInputDateField.stories.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.tsx
- packages/design-system/src/components/web-components/ds-date-field/ds-date-field.stories.tsx
- packages/design-system/src/components/web-components/ds-date-field/ds-date-field.tsx
Add uncontrolled component support to `SingleInputDateField` so it works with web components. Web components are uncontrolled by definition, and I discovered that our `SingleInputDateField` (P)react component didn't actually support an uncontrolled component behavior. Even though the underlying `TextField` component supports the uncontrolled behavior,  we need access to that internal value in the `SingleInputDateField`, so I re-implemented the uncontrolled-component internal state tracking at the `SingleInputDateField` level. We have several other components that follow a very similar pattern of optionally tracking internal state based on whether the `value` is provided.
Try out the new `Uncontrolled` story on the `SingleInputDateField` and specifically use the calendar picker to select a …
> [NO-TICKET] Add uncontrolled-component support to `SingleInputDateField`

- examples/astro/package.json
- examples/preact-app/package.json
- examples/preact-react-app/package.json
- examples/react-app/package.json
- packages/docs/package.json
- packages/ds-cms-gov/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
A quick fix to resolve how `@cmsgov/design-system` is imported as dependency in packages
> [NO-TICKET] Manually updates "@cmsgov/design-system" version in package dependencies

- packages/docs/content/components/drawer.mdx
- packages/docs/content/components/modal-dialog.mdx
- packages/docs/src/components/content/StorybookExample.tsx
[Ticket](https://jira.cms.gov/browse/WNMGDS-2878)
- Updated component stories referenced in drawer and modal-dialog doc site pages
- Added new argument to the StorybookExample file to handle control arguments
1. Pull down changes locally
2. Build the docsite
3. Run locally and confirm that the stories are displaying properly for the Drawer and Modal Dialog pages
> [WNMGDS-2878] Render Doc Site stories for Modal Dialog and Drawer

- packages/design-system/src/components/HelpDrawer/HelpDrawer.test.tsx
- packages/design-system/src/components/HelpDrawer/HelpDrawer.tsx
Fix `onAnalyticsEvent` prop bleeding into `dialog` DOM elements through `HelpDrawer`. Pulls that custom handler out of the `other` props that get passed through to the `Drawer` and then the `NativeDialog` element.
Without this fix, the unit test I added will print errors to the console like this:
```
console.error
Warning: Unknown event handler property `onAnalyticsEvent`. It will be ignored.
at dialog
at NativeDialog (/Users/patrickwolfert/Projects/design-system/packages/design-system/src/components/NativeDialog/NativeDialog.tsx:38:3)
at Drawer (/Users/patrickwolfert/Projects/design-system/packages/design-system/src/components/Drawer/Drawer.tsx:73:5)
at HelpDrawer (/Users/patrickwolfert/Projects/design-system/packages/design-system/src/components/HelpDrawer/HelpDrawer.tsx:13:11)
```
> [WNMGDS-2890] Fix `onAnalyticsEvent` attribute rendering to DOM through `HelpDrawer`

- packages/ds-healthcare-gov/src/components/Header/Header.tsx
- packages/ds-healthcare-gov/src/components/Header/defaultMenuLinks.ts
Be more informative about what `defaultMenuLinks` returns in the types. Previously the return type was `{}`, which is useless to teams trying to use that functions themselves.
Build the healthcare package and take a look at the typedef files. There should be a return type other than `{}` for that function.
> [NO-TICKET] Define a better return type for `defaultMenuLinks`

- packages/docs/content/blog/release-11.0.mdx
- Removes reference to removing the privacy settings dialog
> [NO-TICKET] Revises release v11 blog post

- scripts/bump-child-deps-utils.ts
- We were accidentally adding the core design system as a dependency to it's on package.json file when updating the child dependencies, this change fixes that.
1. In the `release.ts` script, comment out lines [102-137](https://github.com/CMSgov/design-system/blob/jryan/no-ticket-exclude-core-design-system-from-dependency-update/scripts/release.ts#L102-L137) and comment out lines [222-224](https://github.com/CMSgov/design-system/blob/jryan/no-ticket-exclude-core-design-system-from-dependency-update/scripts/release.ts#L222-L224)
2. Run the release script: `yarn release`
3. Confirm the version number has been updated for the /packages/design-system/package.json, and that the dependencies have NOT changes for that same file.
4. All other child DS and example package.json files should be …
> [NO-TICKET] Exclude core design system from dependency update

- packages/design-system/src/components/Autocomplete/Autocomplete.stories.tsx
- packages/design-system/src/components/DateField/MultiInputDateField.stories.tsx
- packages/design-system/src/components/Dialog/Dialog.stories.tsx
- packages/design-system/src/components/Drawer/Drawer.stories.tsx
- packages/design-system/src/components/FilterChip/FilterChip.stories.tsx
- packages/design-system/src/components/Pagination/Pagination.stories.tsx
- packages/design-system/src/components/Review/Review.stories.tsx
- packages/design-system/src/components/SkipNav/SkipNav.stories.tsx
- tests/browser/snapshots/storybook-docs/Docs-Components-Autocomplete-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Dialog-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Drawer-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-FilterChip-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-MultiInputDateField-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Pagination-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Review-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-SkipNav-Docs-prop-table-matches-snapshot-1.txt
- [Jira ticket number](https://jira.cms.gov/browse/WNMGDS-2713)
- Added a number of default values to our Storybook stories
1. Confirm that the default values for each component are displaying in the props tables in Storybook. The default values should match those listed in the `en.json` translation file. 
| Component | Default values |
|--------|--------|
| Autocomplete | ariaClearLabel; clearInputText; loadingMessage; noResultsMessage |
| DateInput | dayLabel; monthLabel; yearLabel |
| Dialog | ariaCloseLabel |
| Drawer | ariaLabel; closeButtonText; headingLevel |
| FilterChip |ariaClearLabel |
| Pagination | ariaLabel; endAriaLabel; endLabelText; startAriaLabel; startLabelText |
| Review | editText |
| SkipNav | children |
> [WNMGDS-2713] Add default value overrides to Storybook

- packages/design-system-tokens/src/css/translate.test.ts
- packages/design-system-tokens/src/css/translate.ts
Makes our Figma changes backwards compatible with respect to the sass var files. I had failed to adequately document the changes in https://github.com/CMSgov/design-system/pull/3100, which resulted in a failure to report the breaking change of a file-name change in our release notes. Luckily our integration tests caught it in one of the beta releases.
Note that instead of reproducing the same old contents of those files, they're just duplicates of the new file, and that's enough. It won't break anything if a product imports both of these files, because they just re-declare the same variables. It also has no effect on the final CSS bundle sizes because Sass variables are ephemeral.
Clear all your `dist` folders and rebuild. You should see the same old file names that we used to output. …
> [WNMGDS-2935] Make Sass token file changes backwards compatible

- packages/design-system-tokens/src/css/translate.test.ts
- packages/design-system-tokens/src/css/translate.ts
Unlike CSS Custom Properties, Sass variables can't be used before they're defined. Our new script for generating Sass variable (theme) files from tokens allowed for instances where a variable was assigned to another variable before it was declared, which will cause Sass compiler errors when someone tries to use those files. I've added a post-processing function that reorders the declarations when it finds variables being used before they're defined.
There's a new unit test, but the best place to test would be in the downstream app where this problem was found.
> [WNMGDS-2950] Reorder Sass token files to avoid Sass compiler errors

- .storybook/docs/WebComponentArgsTable.tsx
- .storybook/docs/WebComponentAttrs.tsx
- .storybook/docs/WebComponentEventsTable.tsx
- packages/design-system/src/components/web-components/ds-accordion/ds-accordion-item.stories.tsx
- packages/design-system/src/components/web-components/ds-choice/ds-choice.stories.tsx
- packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
- packages/design-system/src/components/web-components/ds-pagination/ds-pagination.stories.tsx
- packages/design-system/src/components/web-components/shared-attributes/storybook.tsx
A known limitation with our documentation tables within Storybook for web component attributes and events is that the descriptions don't render Markdown. And the TypeScript types for Storybook keep us from being able to pass JSX instead. I think there's even some kind of error in Storybook if you do pass in JSX to the argTypes to work around the issue (because the Storybook arg controls use the same descriptions).
- Add markdown rendering capabilities to the attributes and event tables
- Updates the event table descriptions, which _were_ able to have JSX workarounds before, unlike the `argTypes` rendered by the attributes table
Open up Storybook and look at the `Description` column for both the attributes and events tables and the `Event object` column for the events tables.
> [WNMGDS-3025] Add markdown rendering to web component Storybook docs

- packages/docs/content/components/accordion.mdx
- This pull request is part of a series aimed at adding missing "Web Component" sections to component pages on the documentation site. By including these sections, we ensure developers have quick access to code examples and guidance for the web component version of each component.
Jira story: [WNMGDS-3027](https://jira.cms.gov/browse/WNMGDS-3027)
Test the storybook link in the Web Component section: [here](https://cmsgov.github.io/design-system/branch/tamara/WNMGDS-3027/add-wc-section-to-accordion-doc-page/components/accordion/?theme=core#code)
> [WNMGDS-3037] Adds web component section to Accordion doc site page

- packages/docs/content/components/button.mdx
- Remove the bullet in mgov theme referring to 'exceptions', which has a broken link. (Melissa-approved)
- https://jira.cms.gov/browse/WNMGDS-2940
When running locally, take a look at the guidance section on the Button page and make sure the following content isn't visible on mgov theme: 
"Other exceptions require advance and separate approval than mock-ups by product teams. See [Exception process](https://design.cms.gov/guidelines/exceptions/?theme=medicare)" in Foundations."
> [WNMGDS-2930] Update mgov guidance on button.mdx

- packages/design-system/src/components/NativeDialog/NativeDialog.tsx
- Problem: when backdropClickExits is enabled, we see the onExit or ds-exit event called twice when exiting the Modal either via the close button or a form submit button
- This is only an issue in Chrome and Firefox and any other browsers that set clientX & clientY to zero on key press (likely Edge though I haven't tested). Safari is smart and doesn't have this issue. Maybe I'll start using Safari for more than just testing, but also probably not.
- The simplest fix that we landed on is to add a simple check for the number of clicks on the event. This information is stored in the event.detail read only property. 
- If it's 0, that means there was no click of a mouse, so a key must've been pressed (or so my logic goes) & return out of the function
- Else, check if we're in the bounding …
> [NO-TICKET] Prevent double firing of exit event in Modal Dialog

- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Tooltip/Tooltip.tsx
- packages/design-system/src/components/web-components/ds-modal-dialog/ds-modal-dialog.tsx
- packages/design-system/src/components/web-components/ds-tooltip/ds-tooltip.tsx
- packages/design-system/src/components/web-components/utils.test.ts
- In [3331](https://github.com/CMSgov/design-system/pull/3331) I added a cute little function that serves as a type predicate for some of our attributes on our web components
- Here we use it more broadly, introducing the needed constants and types in the ModalDialog and Tooltip components
- I also added a spec. Which isn't the best spec since it doesn't do the type predicate stuff that we use this function for, but maybe it's sufficient to ensure the basic functionality of the thing. 
1. Confirm tests pass locally
2. Fire up Storybook or one of the example apps and confirm that ModalDialog and Tooltip web components operate as expected.
> [NO-TICKET] Use isPossibleValue util function in more places and add spec

- packages/design-system/src/components/ThirdPartyExternalLink/__snapshots__/ThirdPartyExternalLink.test.tsx.snap
- packages/design-system/src/components/analytics/getAnalyticsContentFromRefs.ts
We need to change our React component analytics-content-extracting code to be able to follow `slot` elements across the Shadow DOM barrier. Otherwise, the analytics events will have nothing for things like alert heading when the heading content is defined with a slot.
Run the unit tests and make sure no snapshots change.
> [WNMGDS-3057] Update analytics-content-extraction method to support slots

- tests/browser/__snapshots__/custom-reporter.test.ts.snap
- tests/browser/custom-reporter.test.ts
- tests/browser/custom-reporter.ts
This PR introduces the following improvements to the custom reporter:
- Adds a `--list` flag to display test hierarchy paths without executing tests.
- Implements logic to track and display the current test index in the logged output (e.g., `[1/160]`).
- Formats browser names with square brackets (`[]`) in the output for improved readability.
[Jira Ticket](https://jira.cms.gov/browse/WNMGDS-3147)
1. Run tests using the `--list` flag and a `grep` pattern to filter specific test cases. 
**Example:**`% yarn test:browser --grep="ds-autocomplete" --list `
2. Disable the custom reporter in `playwright.config.ts`, run the tests and compare the logged output with the custom reporter’s output.
3. Run tests without the `--list` flag both with and without the custom reporter enabled. Check that all …
> [WNMGDS-3147] Enable `--list` for playwright custom playwright reporter

- packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/Button/Button.test.tsx
- packages/design-system/src/components/Button/Button.tsx
- packages/design-system/src/components/ChoiceList/Choice.test.tsx
- packages/design-system/src/components/ChoiceList/Choice.tsx
- packages/design-system/src/components/Dropdown/Dropdown.test.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/TextField/TextField.test.tsx
- packages/design-system/src/components/TextField/TextField.tsx
- packages/design-system/src/components/TextField/TextInput.test.tsx
- packages/design-system/src/components/TextField/TextInput.tsx
- tests/browser/snapshots/storybook-docs/Docs-Components-Autocomplete-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Choice-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-Dropdown-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-SingleInputDateField-Docs-prop-table-matches-snapshot-1.txt
- tests/browser/snapshots/storybook-docs/Docs-Components-TextField-Docs-prop-table-matches-snapshot-1.txt
The types I added previously introduced in #3356 didn't cover mutable refs, which are what you get when you use `useRef`. I guess the immutable `Ref` types are what you get when you use `createRef`. I thought I had read the type definitions thoroughly before, but I missed that the `MutableRefObject` was missing. And I didn't understand the difference in the returned ref type between those two functions until now.
Also, if you look at the types we were using before [my last change](https://github.com/CMSgov/design-system/pull/3356/files), they used a lot of `any` types. I'm nervous that if we start introducing really specific types like `React.Ref<HTMLInputElement | HTMLTextAreaElement>`, we're going to start to get a lot of complaints from down stream.
- Change all of the standardized …
> [WNMGDS-2928] Follow up to improve the standardized `inputRef` types

- .storybook/docs/HtmlElementArgs.tsx
- .storybook/docs/WebComponentAttrs.tsx
- package.json
- packages/docs/package.json
- packages/docs/src/components/content/StorybookDocLinks.tsx
- packages/docs/src/helpers/humanizeList.tsx
- yarn.lock
Remove the `humanize-react` library and put a modified version of its source code into our project. It's a nice little library, but it was made with a single commit 5 years ago and never updated since. It still requires React 16 as a peer dependency. This causes errors when we try to use other package managers.
1. Try the doc site
2. Try Storybook
> [WNMGDS-3175] Remove outdated `humanize-react` library

- packages/design-system/src/components/utilities/cleanFieldProps.ts
Fixes an error found by the TextField "applies custom hintClassName to the hint element" unit test where React is complaining that the `hintClassName` is being applied directly to a DOM element.
Run `yarn test:unit packages/design-system/src/components/TextField/TextField.test.tsx` and make sure no errors are printed to the console.
> [NO-TICKET] Fix `hintClassName` being applied to DOM elements

- packages/docs/content/foundation/typography/overview.mdx
- Adds general and per theme guidance to the docs site
- [Jira Ticket](https://jira.cms.gov/browse/WNMGDS-3171)
1. Pull down the changes locally and go to http://localhost:8000/foundation/typography/overview/
2. Switch themes and verify that the content contains relevant information
Alternatively, go to https://cmsgov.github.io/design-system/branch/kcn/WNMGDS-3171/typography-overview/foundation/typography/overview/ and then switch themes and verify that the content contains relevant information
> [WNMGDS-3171] Adds Typography overview guidance to docs site

- packages/docs/src/components/content/MaturityChecklist/MaturityChecklist.tsx
- Updates a stray Sketch reference on our `MaturityChecklist` component to Figma.
Run locally:
- Run `npm run start`
- Inspect the token section in the maturity checklist for various component pages. 
Or, inspect maturity checklists for various components on [deployed branch](https://cmsgov.github.io/design-system/branch/tamara/WNMGDS-3173/remove-sketch-references-from-maturity-checklist/?theme=core) to verify that references to Sketch have been replaced with Figma.
Below is a screenshot for quick review.
> [WNMGDS-3173] Removes a stray Sketch reference on the `MaturityChecklist` component.

- packages/docs/content/components/month-picker.mdx
Added "Accessibility" and "Accessibility testing" sections to the [month-picker page](https://design.cms.gov/components/month-picker/?theme=core) on the docsite.
Navigate to month-picker page and confirm that "Accessibility" and "Accessibility testing" sections are added for each theme.
Refer to the Jira ticket for pdf of copy.
> [WNMGDS-3245] Added accessibility and accessibility testing sections to month-picker

- packages/docs/content/components/tooltip.mdx
- Added "Accessibility" and "Accessibility testing" sections to the [tooltip page](https://design.cms.gov/components/tooltip/?theme=core) on the docsite.
1. Navigate to tooltip page and confirm that "Accessibility" and "Accessibility testing" sections are added for each theme.
2. Refer to the Jira ticket for pdf of copy.
> [WNMGDS-3247] Added accessibility and accessibility testing sections to tooltip page

- packages/design-system/src/components/DateField/DateInput.test.tsx
- packages/design-system/src/components/DateField/DateInput.tsx
- packages/design-system/src/components/DateField/MultiInputDateField.tsx
- [Ticket](https://jira.cms.gov/browse/WNMGDS-3215)
- Changes presentation of multi-input date field based on page language
- Shows MM/DD/YYYY for English pages and DD/MM/YYYY for non-English language pages
1. Locally, run in Storybook
2. Change the language via the circular, globe/basketball shaped icon in the top bar over the component
3. Confirm that the format of the inputs changes based on the language selected and that it follows this format:
English: MM/DD/YYYY
Espanol: DD/MM/YYYY
> [WNMGDS-3215] Allow for date entry format to switch between MM/DD and DD/MM per page language

- packages/design-system/src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/design-system/src/components/react-aria/index.js
- packages/design-system/src/components/web-components/ds-dropdown/__snapshots__/ds-dropdown.test.tsx.snap
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-3186)
When initially loading the `Dropdown` component in Storybook ([link](https://design.cms.gov/storybook/iframe.html?globals=theme:core&args=&id=components-dropdown--default&viewMode=story)), the `tabIndex` for the hidden `input` field was set to -1, which is great — no accessibility issues at that point. However, after interacting with the page (either via keyboard or mouse events) the `react-aria` library would set the `tabIndex` to 0, which does register as an [accessibility issue](https://dequeuniversity.com/rules/axe/4.10/aria-hidden-focus?application=AxeChrome).
This PR pulls in the specific changed lines found in this PR (https://github.com/adobe/react-spectrum/pull/7200/) to the local copy of `react-aria` that affects the …
> [WNMGDS-3186] Pulls in an accessibility fix for `react-aria`'s `<HiddenSelect />`

- packages/docs/src/helpers/analytics.ts
- packages/docs/src/helpers/navDataFormatUtils.ts
- [Ticket](https://jira.cms.gov/browse/WNMGDS-3249)
- This adds a new analytics event for when drop downs in the side nav are opened. 
- This event will additional insight into the navigational behaviors of our users
The navigation type field has a number of options. Three seem possibly relevant:
- main nav
- secondary nav
- left_rail
I am leaning towards main nav since this even though our navigation element is on the left rail, it's our only and main page navigation interface. Happy to talk more about this if folks have differing opinions though!
1. Pull down locally
2. `npm run start`
3. Add `window.utag.link = console.log` to you browser console environment. 
4. Confirm that the object shape matches that of the [tech spec](https://confluence.cms.gov/pages/viewpage.action?pageId=1185025 …
> [WNMGDS-3249] NavigationOpened analytics event

- packages/design-system/src/components/Dropdown/Dropdown.test.tsx
- packages/docs/content/components/dropdown.mdx
- [Ticket](https://jira.cms.gov/browse/WNMGDS-3227)
- Remove lines that are no longer reflective of our dropdown type ahead functionality
- Added in a few specs that hopefully get us closer to testing our type ahead functionality
1. Read the documentation and confirm that the line "If the same character is typed in succession, visual focus cycles among the options starting with that character." is removed from the sublists under the "Keyboard Testing" section.
> [WNMGDS-3227] Remove incorrect documentation for Dropdown

- packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.spec.tsx
- packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
- Updated the `SimpleFooter `component to dynamically set the `baseUrl` based on the `language` prop, ensuring Medicare URLs use `es.medicare.gov` when `language="es"` and `www.medicare.gov` otherwise.
- [Jira Ticket](https://jira.cms.gov/browse/WNMGDS-3138)
`npm run test:unit -t SimpleFooter`
> [WNMGDS-3138] Make Medicare URLs language-aware in `SimpleFooter`

- packages/docs/src/pages/search.tsx
- The search value was grabbing the title of the search result link, not it's position in the list. We now grab the position in the list.
5. When that file is opened, search "Command + F" for track:
7. Search for something that will return results, like "help drawer"
8. Click some of the search results links
10. Confirm that search results position is indeed the number of the …
> [WNMGDS-3278] Add in search results position to search event

- packages/docs/src/components/content/SearchForm.tsx
- When someone searches for nothing, make sure we submit a default value of "no value" to our analytics handler
5. When that file is opened, search "Command + F" for track:
7. Search for nothing. Just click the search button, do not enter any string content
10. Confirm that search term is "no value"
> [WNMGDS-3277] Added in default analytics value for empty string searches

- packages/docs/src/helpers/analytics.ts
- Links were pointing to the base url, but instead need to point to the href
5. When that file is opened, search "Command + F" for track:
7. Click a link in the main navigation of the page, the left hand navigation
10. Confirm that the url listed in the data object indeed points to the destination url of the link
> [WNMGDS-3279] Link URL should point to link destination

- packages/docs/src/components/content/ContentRenderer.tsx
- packages/docs/src/components/layout/PageHeader.tsx
- Make sure the Figma link present on all pages uses an'external-link' event rather than an 'internal-link' event
5. When that file is opened, search "Command + F" for `track:`
7. Click on the Figma link
10. Confirm that the "event_name" field sis "external_linl"
> [WNMGDS-3280] Make figma use the external link event

- packages/design-system/src/components/web-components/ds-dropdown/ds-dropdown.stories.tsx
Fixes a typo in the `ds-dropdown` Storybook documentation. The event object for `ds-change` was incorrectly documented as `event.details.target.value` instead of `event.detail.target.value`. 
Review the updated Storybook documentation for `ds-dropdown` and verify that the event object reference is correct.
**Note:** Wasn't sure which milestone to select, so went with 12.1.1 (doc site changes).
> [WNMGDS-3284] Fixes typo in `ds-dropdown` storybook docs

- package-lock.json
- scripts/release.ts
Prior to migrating to `npm` (https://github.com/CMSgov/design-system/pull/3397), the `yarn.lock` [file](https://github.com/CMSgov/design-system/blob/0ba0518c6fac28f4ff8434e66921369188a6f0b6/yarn.lock) did not include the latest DS version used in each of this repository's examples and packages.
With the migration to npm, the `package-lock.json` [file](https://raw.githubusercontent.com/CMSgov/design-system/refs/heads/main/package-lock.json) does include that information. This PR specifically looks to include that change as part of the release script to ensure that running `npm install` after a version bump (https://github.com/CMSgov/design-system/pull/3473) does not change the `package-lock.json`
1. On `main`, run `npm install` and verify that changes to the `package-lock.json` exist
2. On …
> [NO-TICKET] Include changes made to `package-lock.json` in the release script

- packages/design-system/src/components/ThirdPartyExternalLink/ThirdPartyExternalLink.tsx
- tests/browser/snapshots/storybook-docs/Docs-Components-ThirdPartyExternalLink-Docs-prop-table-matches-snapshot-1.txt
[Ticket](https://jira.cms.gov/browse/WNMGDS-2880)
1. Open storybook
2. Confirm that ariaDescribedby exists as a control in the ThirdPartyExternal link story
3. Confrim that setting it to a value adds the attribute `aria-describedby` to the underlying anchor link
> [WNMGDS-2880] Add support for aria-describedby to ThirdPartyExernalLink

- packages/docs/src/components/layout/PageHeader.tsx
- Storybook links are internal links, this request makes sure they are treated as such by our analytics 
5. When that file is opened, search "Command + F" for track:
7. Click on a component, and then click on the Storybook link at the top of the page
10. Confirm that the object contains a field that says "event_name":"internal_link_clicked"
> [NO-TICKET] Add analytics handler to storybook links

- .github/ISSUE_TEMPLATE/bug_report.yml
The idea here is to bolster our bug reporting format to use a [Github form schema](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). This might also allow us to hook into our slack bug reporting workflow.
1. I'm not exactly sure? Try to  create a ticket and see if you can use a form?
> [NO-TICKET] New form for bug reports

- packages/design-system/src/components/Autocomplete/Autocomplete.test.tsx
- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/Autocomplete/utils.tsx
- packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.test.tsx
Previously, when selecting a grouped item in the Autocomplete component, the `onChange` callback wasn't triggered. This was because the component only searched top-level items when resolving the selected ID and did not account for items nested within groups.
- This pull request updates the selection logic to correctly handle both standalone and grouped items.
- Adds unit tests to verify that:
- `onChange` is triggered when selecting a grouped item (`Autocomplete`)
- `ds-change` is dispatched when a grouped item is selected (`ds-autocomplete`)
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-3339)
- Run the unit tests: `npm run test:unit && npm run test:unit:wc`
- Open the `Autocomplete` story in Storybook. Select a grouped item and verify the `Actions` tab shows the appropriate `onChange` …
> [wnmgds 3339] Fix `onChange` not firing for grouped items in `Autocomplete`

- packages/docs/content/components/checkbox.mdx
The checkbox page had two broken links:
1. "GOV.UK Checkbox/Radio buttons discussion" leads to a drop box page where you are prompted to log in
2. "Four steps for choosing form elements on the Web (PDF)" leads to a GoDaddy page
The "GOV.UK checkbox/radio buttons discussion" was removed from Dropbox, as shown in the screenshot below. Because of this, the link was removed.
After some sleuthing with the Wayback machine, the "four steps for choosing form elements" pdf was salvaged but I have removed the link for now until we decide where to host the pdf.
1. (Reminder for designers) Run the app locally and make sure you switch to my branch (you can copy it above, right under the title of this PR) in order to see my changes.
2. Check that both links have been removed
3. Order of sections should …
> [WNMGDS-3353] Remove two broken links on checkbox page

- packages/docs/content/components/checkbox.mdx
- packages/docs/content/components/date-field/date-picker.mdx
- packages/docs/content/components/date-field/multi-input-date-field.mdx
- packages/docs/content/components/date-field/single-input-date-field.mdx
- packages/docs/content/components/hint.mdx
- packages/docs/content/components/inline-error.mdx
- packages/docs/content/components/label.mdx
- packages/docs/content/components/month-picker.mdx
- packages/docs/content/components/radio.mdx
- packages/docs/content/components/text-field/masked-field.mdx
- packages/docs/content/components/text-field/text-field.mdx
- packages/docs/src/components/content/ComponentThemeOptions.tsx
- packages/docs/src/helpers/urlUtils.ts
- [Ticket](https://jira.cms.gov/browse/WNMGDS-3350)
- We attempt to render an additional styling table for form components, however there is no component named "form" in the Tokens lists (or in the design system, it is a pattern) so we are unable to render any additional form styling tables. 
- This ticket removes all mentions of `<ComponentThemeOptions componentname="form" />` in our MDX files, and the associated text providing context for those tables.
- I also took the liberty to add a little message for when no additional styling variables exist for a given component.
1. Search for `<ComponentThemeOptions componentname="form" />` in the codebase. There should be 0 results.
2. Fire up the doc site locally, and add `<ComponentThemeOptions componentname="form" />` to a random MDX page. …
> [WNMGDS-3350] Remove form components table

- packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.stories.tsx
- packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.tsx
- tests/browser/snapshots/storybook-docs/Docs-Web-Components-ds-autocomplete-Docs-prop-table-matches-snapshot-1.txt
- Removed `value` attribute from the public `ds-autocomplete` interface. There doesn't seem to be a clear use case for allowing external control of the input value. The previous storybook implementation appears to have masked the fact that forcibly passing a value breaks the expected behavior of the component. 
- Added missing [formAttrs](https://github.com/CMSgov/design-system/blob/main/packages/design-system/src/components/web-components/shared-attributes/form.ts#L1-L8) to `ds-autocomplete` storybook controls.
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-3189)
- Run storybook, open the ds-autocomplete stories, and verify that the missing [formAttrs](https://github.com/CMSgov/design-system/blob/main/packages/design-system/src/components/web-components/shared-attributes/form.ts#L1-L8) …
> [WNMGDS-3189] Fix `ds-autocomplete` storybook controls

- packages/docs/src/helpers/urlUtils.ts
- So yeah Kim had a really good point [here](https://github.com/CMSgov/design-system/pull/3566#discussion_r2079888694) and it bugged me that I didn't properly address it. So in this teeny tiny pr I'm trying to ease my conscience by setting this check to work on both the server and client. Note: this function will be called twice in some cases, since some of our code is both rendered statically at build time and on the client. But that should be ok so long as you aren't doing something like calling 'gatsby serve' locally (gatsby serve passes in 'production' as the node env). 
1. Add <ComponentThemeOptions componentname="form" /> to a random markdown page
2. Observe the warning in the console.
> [NO-TICKET] Update check for production to work on the server or client

- packages/docs/content/components/checkbox.mdx
- packages/docs/content/components/radio.mdx
- General a11y guidance is added to both the checkbox and radio component (see Jira ticket for content)
- The sections match the order of our [template](https://confluence.cms.gov/display/HCDSG/Doc+Site+Guidance%3A+Information+Architecture)
1. Run locally and confirm that the above criteria are met.
> [WNMGDS-3354] A11y guidance for radio and checkbox components

- packages/docs/content/components/idle-timeout.mdx
- Added new accessibility guidance to the idle timeout component page and reordered the sections of content to match our new template
- Jira ticket: [WNMGDS-3352](https://jira.cms.gov/browse/WNMGDS-3352)
1. Navigate to idle timeout component page and confirm that the new accessibility guidance is formatted correctly.
2. Confirm that the content sections are ordered correctly on the page.
3. Test the "accessibility documentation" link text works in the new accessibility guidance.
> [WNMGDS-3352] added a11y guidance idle timeout

- packages/docs/src/components/layout/Layout.tsx
The env variable is not being set properly on page load which is preventing our analytics script from working properly.
What I wanted to happen:
useEffect runs once on page load and updates the ref to the current environment, which then makes it’s way into the <head> element.
What is actually happening:
useEffect runs after page load and sets the ref value, but the page has already been rendered with null env variable from the initialized ref. Since it’s a ref, no rerender is scheduled and the updated value never makes it to the DOM.
I should've known this is what would happen. Anyway this change should fix it and will be released to the Doc site upon approval.
1. Same as in https://github.com/CMSgov/design-system/pull/3559
2. Confirm that there is a line in the <head> element that reads: …
> [NO-TICKET] Remove useRef and useEffect from Layout.tsx to correct analytics functioning

- packages/docs/src/components/layout/Layout.tsx
So this has been a little bit of a saga.
In #3559 I attempted to add some new analytics functionality for page views. This didn't really work because of my use of a ref to store the env variable.
In #3591 I tried to simplify things and get all the work done outside of a useEffect, just in the script. But since I didn't understand the fineries of how Gatsby does server rendering (and some of the distinctions between Gatsby's development and production build processes) we end up with an undefined variable on production (thank you @tamara-corbalt for catching).
Rolled #3591 back in #3592 and so now here we are going back to the original client side implementation with some more sophistication (thank you @kim-cmsds). 
Anyway, here we are.
1. The best way to test is using the debugger built …
> [NO-TICKET] Add in UTAG page view analytics

- packages/docs/src/components/layout/StatusIndicator.tsx
- packages/docs/src/helpers/graphQLTypes.ts
- Adds `StatusIndicator` components from [pr-3595](https://github.com/CMSgov/design-system/pull/3595), omitting any logic that wires it into the `PageHeader` while we wait for content approval on status badge text and contextual alerts.
[Jira ticket](https://jira.cms.gov/browse/WNMGDS-3360)
- Confirm the doc site builds locally without errors.
> [WNMGDS-3360] Add `StatusIndicator` component to docs. 

- packages/docs/content/foundation/layout-grid/responsive-design.mdx
- [Ticket](https://jira.cms.gov/browse/WNMGDS-3416)
- Fixes broken link
1. Navigate to /foundation/layout-grid/responsive-design/ 
2. Click the 'Typography' link near the bottom of the page
3. Make sure it goes to /foundation/typography/overview (in theory it should go to #responsive-typography but the theme query breaks it :( )
> [WNMGDS-3416] Fix broken link to Typography page

- packages/design-system/src/components/TextField/Mask.test.tsx
- packages/design-system/src/components/TextField/Mask.tsx
- [Ticket](https://jira.cms.gov/browse/CMSDS-3414)
- Problem: Chrome appends a `/v` modifier to pattern regexes. This means we need to escape certain characters. This modifier leads to the following console error:
Pattern attribute value [0-9-]* is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /[0-9-]*/v: Invalid character class
By escaping the `-` and `{}` characters we prevent this error. Note there is a double escape character because the regexes are turned into strings, and the original escape character is removed.
1. Run locally
2. Go to the `components-textfield--all-masked-fields` story under TextField in Storybook
3. Confirm there is no console error.
> [WNMGDS-3414] Fix Textfield regex patterns

- .storybook/preview.tsx
- package-lock.json
- packages/design-system/src/components/Tooltip/Tooltip.test.tsx
- packages/design-system/src/components/Tooltip/Tooltip.tsx
- packages/design-system/src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/design-system/src/components/Tooltip/useTooltipAnalytics.ts
- packages/design-system/src/components/config.ts
- packages/docs/content/components/analytics.mdx
- tests/browser/snapshots/storybook-docs/Docs-Components-Tooltip-Docs-prop-table-matches-snapshot-1.txt
- [Ticket](https://jira.cms.gov/browse/CMSDS-3412)
- Added analytics support to Tooltip 
- Based on [this contribution](https://github.com/CMSgov/design-system/pull/3618)
- Address the React portion of [this ticket](https://github.com/CMSgov/design-system/issues/3616)
- Web component work will be forthcoming
1. Run unit tests locally, confirm they work
2. Follow this procedure for examining analytics events:
3. The best way to test is using the debugger built into your Browser of choice, for Firefox:
4. Open the storybook site locally
5. Open dev tools and go to the Debugger tab
6. Press "Command + P" and search for "utag.js"
7. When that file is opened, search "Command + F" for track:
8. Place a break point at the line following the definition of the track function
9. Hover over the …
> [WNMGDS-3412] Add Analytics Support to Tooltip

- .storybook/main.ts
- We get this notice in the console on Storybook: `storybook/viewport was loaded twice, this could have bad side-effects`
- Turns out this is because we're loading the viewport addon twice. [It's included in the `@storybook/addon-essentials` package](https://storybook.js.org/docs/8/essentials/index), so we don't need it listed in the addons array in our main.ts file.
1. Run storybook locally
2. Make sure there is no warning in the console.
3. Make sure the viewport feature works
> [NO-TICKET] The viewport does not need to be listed as an addon

- package-lock.json
- package.json
- Storybook v9 continues to support `react-docgen-typescript`.
- The `react-docgen-typescript` package has released [v2.4.0](https://github.com/styleguidist/react-docgen-typescript/releases), which includes [this commit](https://github.com/styleguidist/react-docgen-typescript/pull/503) that ensures typeScript union types are consistently sorted.
- This version resolves the issue that previously required us to pin to a beta release and apply a package override. With the upgrade, this override is no longer necessary.
1. Run `npm run clean && npm install && npm run build` and verify that the project builds without errors.
2. Run `npm ls react-docgen-typescript` to confirm that version 2.4.0 is installed and used by both the root project and Storybook’s internal plugin …
> [CMSDS-3466] Upgrade `react-docgen-typescript` to v2.4.0

- packages/design-system/src/components/ChoiceList/ChoiceList.stories.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
- Updated the ChoiceList example to use the `hint` prop instead of the `requirementLabel` prop to render the hint text. `requirementLabel` is meant for that text that says "Required" or "Optional" before the hint text.
- CMSDS-3547
- Closes #3726 
1. Run `npm run storybook`
2. Navigate to the `ChoiceList` docs
3. Under the example, click "Show code"
4. Verify the second choice has a `hint` prop with the value "Choice hint text"
> [CMSDS-3547] Replace requiredLabel with hint on ChoiceList Story

- package-lock.json
- packages/docs/package.json
- Updated `gatsby-plugin-newrelic` to version 2.9.0
- [Ticket](https://jira.cms.gov/browse/CMSDS-3605)
1. Pull down this branch
2. Run `npm run clean && npm install && npm run start`
3. In the browser, inspect the doc site
4. Open the console
5. Type `newrelic`, press enter
6. Open the returned object
7. Open the `initializedAgents ` key
8. Open the first key available
9. View the `runtime` object
10. Confirm the version is `1.290`
> [CMSDS-3605] Update new relic browser app

- packages/design-system/src/components/Autocomplete/Autocomplete.tsx
- packages/design-system/src/components/Button/useButtonAnalytics.ts
- packages/design-system/src/components/ChoiceList/ChoiceList.tsx
- packages/design-system/src/components/DateField/SingleInputDateField.tsx
- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Dropdown/Dropdown.tsx
- packages/design-system/src/components/Dropdown/DropdownMenu.tsx
- packages/design-system/src/components/NativeDialog/useNativeDialogAnalytics.ts
- packages/design-system/src/components/Table/Table.tsx
- packages/design-system/src/components/ThirdPartyExternalLink/useThirdPartyExternalLinkAnalytics.ts
- packages/design-system/src/components/Tooltip/useTooltipAnalytics.ts
- packages/design-system/src/components/analytics/useAnalyticsContent.ts
- packages/design-system/src/components/utilities/useAutoFocus.ts
- packages/design-system/src/components/utilities/usePrevious.ts
- packages/ds-medicare-gov/src/components/SimpleFooter/SimpleFooter.tsx
- Updates all `useRef` initializers to pass in `null` as the default value, which is required by React 19 type definitions.
- This is **PR 1 of 5** in the broader effort to upgrade React types to v19.
[Jira ticket](https://jira.cms.gov/browse/CMSDS-3467)
- `npm run build`
- `npm run test`
This pr is the first in a stacked series. Please review and merge before [pr-3782](https://github.com/CMSgov/design-system/pull/3782) (JSX namespace migration).
> [CMSDS-3467] Pass null into useRef initializers to align with react 19 types 

- packages/design-system/src/components/Review/Review.tsx
- packages/design-system/src/components/utilities/findElementsOfType.ts
- packages/design-system/src/components/web-components/ds-autocomplete/ds-autocomplete.tsx
- packages/design-system/src/components/web-components/ds-choice/ds-choice-list.tsx
- packages/design-system/src/components/web-components/ds-date-field/ds-date-field.tsx
- packages/design-system/src/components/web-components/ds-drawer/ds-drawer.tsx
- packages/design-system/src/components/web-components/ds-review/ds-review.tsx
- packages/design-system/src/components/web-components/ds-tabs/ds-tabs.tsx
- packages/design-system/src/components/web-components/ds-third-party-external-link/ds-third-party-external-link.tsx
- packages/ds-medicare-gov/src/components/web-components/ds-simple-footer/ds-simple-footer.tsx
- Migrates all `JSX.IntrinsicElements` references to `React.JSX.IntrinsicElements`, which is required by React 19 type definitions.
- Adds custom element type support in `findElementsOfType` 
[Jira ticket](https://jira.cms.gov/browse/CMSDS-3467)
- Run `npm run build` 
- Run `npm run test`
- Run `npm run test:unit:wc` to validate web component typings and usage.
This is **PR 2 of 5** in the broader effort to upgrade React types to v19.
Please review after [pr-3781](https://github.com/CMSgov/design-system/pull/3781) (useRef fixes) has been merged.
> [CMSDS-3467] Migrate `JSX.IntrinsicElements` to `React.JSX.IntrinsicElements` and add custom element support

- packages/design-system/src/components/TextField/LabelMask.tsx
- packages/design-system/src/components/TextField/Mask.tsx
- packages/design-system/src/components/TextField/maskHelpers.test.ts
- packages/design-system/src/components/TextField/maskHelpers.ts
- Updates the `Mask` component to ensure field values are always treated as strings, in line with stricter React 19 type definitions.
- Adds a utility to coerce field values to a string type.
- Adds test coverage for the new utility
[Jira ticket](https://jira.cms.gov/browse/CMSDS-3467)
- Run `npm run build`
- Run `npm run test`
This is **PR 3 of 5** in the broader effort to upgrade React types to v19.  
Please review after [PR 3782](https://github.com/CMSgov/design-system/pull/3782) has been merged.
> [CMSDS-3467] Coerce field values to string and add `coerceToString` utility

- packages/design-system/src/components/ChoiceList/ChoiceList.test.tsx
- packages/design-system/src/components/ChoiceList/ChoiceList.tsx
- packages/design-system/src/components/InlineError/useInlineError.tsx
- packages/design-system/src/components/web-components/ds-choice/__snapshots__/ds-choice-list.test.tsx.snap
- The `aria-invalid` attribute is currently applied directly to the <fieldset> element on `ChoiceList` components. According to WAI-ARIA specifications, aria-invalid is a supported and valid attribute for elements with the "radiogroup" role, but not for fieldset elements that do not possess that role.
- This PR updates `ChoiceList` to only show the `aria-invalid` attribute when the `type` prop is set to 'radio'.
- [CMSDS-3444](https://jira.cms.gov/browse/CMSDS-3444)
> [CMSDS-3444] Remove aria-invalid attribute if ChoiceList is a checkbox group.

- packages/docs/content/components/date-field/date-picker.mdx
- Added a11y guidance for the calendar picker component
- [Ticket](https://jira.cms.gov/browse/CMSDS-3575)
1. Run locally
2. Confirm that the text on /components/date-field/date-picker/ matches the text in the PDF in the ticket. Except for the small alteration on line 56:
Previous: Tab: Moves between the date input field and calendar button. When the calendar is initially opened, pressing tab will move focus first from a previous month selection button then to the month selection dropdown, next the year selection dropdown and finally **the initially selected date or the first of the month**
Revision: Tab: Moves between the date input field and calendar button. When the calendar is initially opened, pressing tab will move focus first from a previous month selection button then to the month …
> [CMSDS-3575] Add a11y guidance for the Calendar Picker component

- package-lock.json
- package.json
- packages/design-system/package.json
- packages/docs/package.json
- packages/ds-cms-gov/package.json
- packages/ds-healthcare-gov/package.json
- packages/ds-medicare-gov/package.json
- Bump @types/react packages
[Jira ticket](https://jira.cms.gov/browse/CMSDS-3467)
- `npm run clean && npm install && npm run build`
- `npm run test`
- `npm run test:unit:wc`
- `npm run test:browser:all`
- `npm run start`
This is **PR 5 of 5** in the broader effort to upgrade React types to v19.  
Please review after [PR 3784](https://github.com/CMSgov/design-system/pull/3784) has been merged.
> [CMDS-3467] Bump `@types/react` packages

- examples/_shared/react/CardComponentExample.tsx
- examples/astro-react-18/src/pages/index.astro
- packages/design-system/src/components/Card/index.ts
- packages/design-system/src/components/index.ts
- packages/ds-medicare-gov/src/components/index.ts
- Adds missing entry points for the new Core `Card` component.  
- Adds `ComponentCardExample` – tests that the Core `Card` component can be imported and used in an application.  
1. `cd examples/astro-react-18` 
2. `npm run start`
3. Inspect Core Card component example.
> [NO-TICKET] Ensure `Card` is exported from Core
